[[plugins-inputs-cloudwatch]]
=== cloudwatch

NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-input-cloudwatch`.


Pull events from the Amazon Web Services CloudWatch API.

To use this plugin, you *must* have an AWS account, and the following policy

Typically, you should setup an IAM policy, create a user and apply the IAM policy to the user.
A sample policy for EC2 metrics is as follows:
[source,json]
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "Stmt1444715676000",
                "Effect": "Allow",
                "Action": [
                    "cloudwatch:GetMetricStatistics",
                    "cloudwatch:ListMetrics"
                ],
                "Resource": "*"
            },
            {
                "Sid": "Stmt1444716576170",
                "Effect": "Allow",
                "Action": [
                    "ec2:DescribeInstances"
                ],
                "Resource": "*"
            }
        ]
    }

See http://aws.amazon.com/iam/ for more details on setting up AWS identities.

# Configuration Example
[source, ruby]
    input {
      cloudwatch {
        namespace => "AWS/EC2"
        metrics => [ "CPUUtilization" ]
        filters => { "tag:Group" => "API-Production" }
        region => "us-east-1"
      }
    }

    input {
      cloudwatch {
        namespace => "AWS/EBS"
        metrics => ["VolumeQueueLength"]
        filters => { "tag:Monitoring" => "Yes" }
        region => "us-east-1"
      }
    }

    input {
      cloudwatch {
        namespace => "AWS/RDS"
        metrics => ["CPUUtilization", "CPUCreditUsage"]
        filters => { "EngineName" => "mysql" } # Only supports EngineName, DatabaseClass and DBInstanceIdentifier
        region => "us-east-1"
      }
    }


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
cloudwatch {
    filters => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-cloudwatch-access_key_id>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-cloudwatch-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-cloudwatch-combined>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-cloudwatch-filters>> |<<array,array>>|Yes|
| <<plugins-inputs-cloudwatch-interval>> |<<number,number>>|No|`900`
| <<plugins-inputs-cloudwatch-metrics>> |<<array,array>>|No|`["CPUUtilization", "DiskReadOps", "DiskWriteOps", "NetworkIn", "NetworkOut"]`
| <<plugins-inputs-cloudwatch-namespace>> |<<string,string>>|No|`"AWS/EC2"`
| <<plugins-inputs-cloudwatch-period>> |<<number,number>>|No|`300`
| <<plugins-inputs-cloudwatch-proxy_uri>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1"]`|No|`"us-east-1"`
| <<plugins-inputs-cloudwatch-secret_access_key>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-session_token>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-statistics>> |<<array,array>>|No|`["SampleCount", "Average", "Minimum", "Maximum", "Sum"]`
| <<plugins-inputs-cloudwatch-tags>> |<<array,array>>|No|
| <<plugins-inputs-cloudwatch-type>> |<<string,string>>|No|
| <<plugins-inputs-cloudwatch-use_ssl>> |<<boolean,boolean>>|No|`true`
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-cloudwatch-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order:

1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config
2. External credentials file specified by `aws_credentials_file`
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
5. IAM Instance Profile (available when running inside EC2)

[[plugins-inputs-cloudwatch-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-cloudwatch-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

[source,ruby]
----------------------------------
    :access_key_id: "12345"
    :secret_access_key: "54321"
----------------------------------


[[plugins-inputs-cloudwatch-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-cloudwatch-combined]]
===== `combined` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Use this for namespaces that need to combine the dimensions like S3 and SNS.

[[plugins-inputs-cloudwatch-filters]]
===== `filters` 

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

Specify the filters to apply when fetching resources:

This needs to follow the AWS convention of specifiying filters.
Instances: { 'instance-id' => 'i-12344321' }
Tags: { "tag:Environment" => "Production" }
Volumes: { 'attachment.status' => 'attached' }
Each namespace uniquely support certian dimensions. Please consult the documentation
to ensure you're using valid filters.

[[plugins-inputs-cloudwatch-interval]]
===== `interval` 

  * Value type is <<number,number>>
  * Default value is `900`

Set how frequently CloudWatch should be queried

The default, `900`, means check every 15 minutes. Setting this value too low
(generally less than 300) results in no metrics being returned from CloudWatch.

[[plugins-inputs-cloudwatch-metrics]]
===== `metrics` 

  * Value type is <<array,array>>
  * Default value is `["CPUUtilization", "DiskReadOps", "DiskWriteOps", "NetworkIn", "NetworkOut"]`

Specify the metrics to fetch for the namespace. The defaults are AWS/EC2 specific. See http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/aws-namespaces.html
for the available metrics for other namespaces.

[[plugins-inputs-cloudwatch-namespace]]
===== `namespace` 

  * Value type is <<string,string>>
  * Default value is `"AWS/EC2"`

If undefined, LogStash will complain, even if codec is unused.
The service namespace of the metrics to fetch.

The default is for the EC2 service. See http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/aws-namespaces.html
for valid values.

[[plugins-inputs-cloudwatch-period]]
===== `period` 

  * Value type is <<number,number>>
  * Default value is `300`

Set the granularity of the returned datapoints.

Must be at least 60 seconds and in multiples of 60.

[[plugins-inputs-cloudwatch-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-inputs-cloudwatch-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `ap-northeast-2`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`, `ap-south-1`
  * Default value is `"us-east-1"`

The AWS Region

[[plugins-inputs-cloudwatch-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-inputs-cloudwatch-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Session token for temporary credential

[[plugins-inputs-cloudwatch-statistics]]
===== `statistics` 

  * Value type is <<array,array>>
  * Default value is `["SampleCount", "Average", "Minimum", "Maximum", "Sum"]`

Specify the statistics to fetch for each namespace

[[plugins-inputs-cloudwatch-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-cloudwatch-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-cloudwatch-use_ssl]]
===== `use_ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Should we require (true) or disable (false) using SSL for communicating with the AWS API
The AWS SDK for Ruby defaults to SSL so we preserve that


