[[plugins-inputs-couchdb_changes]]
=== couchdb_changes



This CouchDB input allows you to automatically stream events from the
CouchDB http://guide.couchdb.org/draft/notifications.html[_changes] URI.
Moreover, any "future" changes will automatically be streamed as well making it easy to synchronize
your CouchDB data with any target destination

### Upsert and delete
You can use event metadata to allow for document deletion.
All non-delete operations are treated as upserts

### Starting at a Specific Sequence
The CouchDB input stores the last sequence number value in location defined by `sequence_path`.
You can use this fact to start or resume the stream at a particular sequence.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
couchdb_changes {
    db => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-couchdb_changes-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-couchdb_changes-always_reconnect>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-couchdb_changes-ca_file>> |a valid filesystem path|No|
| <<plugins-inputs-couchdb_changes-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-couchdb_changes-db>> |<<string,string>>|Yes|
| <<plugins-inputs-couchdb_changes-heartbeat>> |<<number,number>>|No|`1000`
| <<plugins-inputs-couchdb_changes-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-inputs-couchdb_changes-ignore_attachments>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-couchdb_changes-initial_sequence>> |<<number,number>>|No|
| <<plugins-inputs-couchdb_changes-keep_revision>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-couchdb_changes-password>> |<<password,password>>|No|`nil`
| <<plugins-inputs-couchdb_changes-port>> |<<number,number>>|No|`5984`
| <<plugins-inputs-couchdb_changes-reconnect_delay>> |<<number,number>>|No|`10`
| <<plugins-inputs-couchdb_changes-secure>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-couchdb_changes-sequence_path>> |<<string,string>>|No|
| <<plugins-inputs-couchdb_changes-tags>> |<<array,array>>|No|
| <<plugins-inputs-couchdb_changes-timeout>> |<<number,number>>|No|
| <<plugins-inputs-couchdb_changes-type>> |<<string,string>>|No|
| <<plugins-inputs-couchdb_changes-username>> |<<string,string>>|No|`nil`
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-couchdb_changes-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-couchdb_changes-always_reconnect]]
===== `always_reconnect` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Reconnect flag.  When true, always try to reconnect after a failure

[[plugins-inputs-couchdb_changes-ca_file]]
===== `ca_file` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

Path to a CA certificate file, used to validate certificates

[[plugins-inputs-couchdb_changes-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `ASCII-8BIT`, `Big5`, `Big5-HKSCS`, `Big5-UAO`, `CP949`, `Emacs-Mule`, `EUC-JP`, `EUC-KR`, `EUC-TW`, `GB18030`, `GBK`, `ISO-8859-1`, `ISO-8859-2`, `ISO-8859-3`, `ISO-8859-4`, `ISO-8859-5`, `ISO-8859-6`, `ISO-8859-7`, `ISO-8859-8`, `ISO-8859-9`, `ISO-8859-10`, `ISO-8859-11`, `ISO-8859-13`, `ISO-8859-14`, `ISO-8859-15`, `ISO-8859-16`, `KOI8-R`, `KOI8-U`, `Shift_JIS`, `US-ASCII`, `UTF-8`, `UTF-16BE`, `UTF-16LE`, `UTF-32BE`, `UTF-32LE`, `Windows-1251`, `GB2312`, `IBM437`, `IBM737`, `IBM775`, `CP850`, `IBM852`, `CP852`, `IBM855`, `CP855`, `IBM857`, `IBM860`, `IBM861`, `IBM862`, `IBM863`, `IBM864`, `IBM865`, `IBM866`, `IBM869`, `Windows-1258`, `GB1988`, `macCentEuro`, `macCroatian`, `macCyrillic`, `macGreek`, `macIceland`, `macRoman`, `macRomania`, `macThai`, `macTurkish`, `macUkraine`, `CP950`, `CP951`, `stateless-ISO-2022-JP`, `eucJP-ms`, `CP51932`, `GB12345`, `ISO-2022-JP`, `ISO-2022-JP-2`, `CP50220`, `CP50221`, `Windows-1252`, `Windows-1250`, `Windows-1256`, `Windows-1253`, `Windows-1255`, `Windows-1254`, `TIS-620`, `Windows-874`, `Windows-1257`, `Windows-31J`, `MacJapanese`, `UTF-7`, `UTF8-MAC`, `UTF-16`, `UTF-32`, `UTF8-DoCoMo`, `SJIS-DoCoMo`, `UTF8-KDDI`, `SJIS-KDDI`, `ISO-2022-JP-KDDI`, `stateless-ISO-2022-JP-KDDI`, `UTF8-SoftBank`, `SJIS-SoftBank`, `BINARY`, `CP437`, `CP737`, `CP775`, `IBM850`, `CP857`, `CP860`, `CP861`, `CP862`, `CP863`, `CP864`, `CP865`, `CP866`, `CP869`, `CP1258`, `Big5-HKSCS:2008`, `eucJP`, `euc-jp-ms`, `eucKR`, `eucTW`, `EUC-CN`, `eucCN`, `CP936`, `ISO2022-JP`, `ISO2022-JP2`, `ISO8859-1`, `CP1252`, `ISO8859-2`, `CP1250`, `ISO8859-3`, `ISO8859-4`, `ISO8859-5`, `ISO8859-6`, `CP1256`, `ISO8859-7`, `CP1253`, `ISO8859-8`, `CP1255`, `ISO8859-9`, `CP1254`, `ISO8859-10`, `ISO8859-11`, `CP874`, `ISO8859-13`, `CP1257`, `ISO8859-14`, `ISO8859-15`, `ISO8859-16`, `CP878`, `CP932`, `csWindows31J`, `SJIS`, `PCK`, `MacJapan`, `ASCII`, `ANSI_X3.4-1968`, `646`, `CP65000`, `CP65001`, `UTF-8-MAC`, `UTF-8-HFS`, `UCS-2BE`, `UCS-4BE`, `UCS-4LE`, `CP1251`, `external`, `locale`
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-couchdb_changes-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-couchdb_changes-db]]
===== `db` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The CouchDB db to connect to.
Required parameter.

[[plugins-inputs-couchdb_changes-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-couchdb_changes-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-couchdb_changes-heartbeat]]
===== `heartbeat` 

  * Value type is <<number,number>>
  * Default value is `1000`

Logstash connects to CouchDB's _changes with feed=continuous
The heartbeat is how often (in milliseconds) Logstash will ping
CouchDB to ensure the connection is maintained.  Changing this
setting is not recommended unless you know what you are doing.

[[plugins-inputs-couchdb_changes-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

IP or hostname of your CouchDB instance

[[plugins-inputs-couchdb_changes-ignore_attachments]]
===== `ignore_attachments` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Future feature! Until implemented, changing this from the default
will not do anything.

Ignore attachments associated with CouchDB documents.

[[plugins-inputs-couchdb_changes-initial_sequence]]
===== `initial_sequence` 

  * Value type is <<number,number>>
  * There is no default value for this setting.

If unspecified, Logstash will attempt to read the last sequence number
from the `sequence_path` file.  If that is empty or non-existent, it will
begin with 0 (the beginning).

If you specify this value, it is anticipated that you will
only be doing so for an initial read under special circumstances
and that you will unset this value afterwards.

[[plugins-inputs-couchdb_changes-keep_revision]]
===== `keep_revision` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Preserve the CouchDB document revision "_rev" value in the
output.

[[plugins-inputs-couchdb_changes-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-couchdb_changes-password]]
===== `password` 

  * Value type is <<password,password>>
  * Default value is `nil`

Password, if authentication is needed to connect to
CouchDB

[[plugins-inputs-couchdb_changes-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `5984`

Port of your CouchDB instance.

[[plugins-inputs-couchdb_changes-reconnect_delay]]
===== `reconnect_delay` 

  * Value type is <<number,number>>
  * Default value is `10`

Reconnect delay: time between reconnect attempts, in seconds.

[[plugins-inputs-couchdb_changes-secure]]
===== `secure` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Connect to CouchDB's _changes feed securely (via https)
Default: false (via http)

[[plugins-inputs-couchdb_changes-sequence_path]]
===== `sequence_path` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

File path where the last sequence number in the _changes
stream is stored. If unset it will write to `$HOME/.couchdb_seq`

[[plugins-inputs-couchdb_changes-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-couchdb_changes-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * There is no default value for this setting.

Timeout: Number of milliseconds to wait for new data before
terminating the connection.  If a timeout is set it will disable
the heartbeat configuration option.

[[plugins-inputs-couchdb_changes-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-couchdb_changes-username]]
===== `username` 

  * Value type is <<string,string>>
  * Default value is `nil`

Username, if authentication is needed to connect to
CouchDB


