[[plugins-inputs-elasticsearch]]
=== elasticsearch



Read from an Elasticsearch cluster, based on search query results.
This is useful for replaying test logs, reindexing, etc.

Example:
[source,ruby]
    input {
      # Read all documents from Elasticsearch matching the given query
      elasticsearch {
        host => "localhost"
        query => '{ "query": { "match": { "statuscode": 200 } } }'
      }
    }

This would create an Elasticsearch query with the following format:
[source,json]
    curl 'http://localhost:9200/logstash-*/_search?&scroll=1m&size=1000' -d '{
      "query": {
        "match": {
          "statuscode": 200
        }
      }
    }'


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
elasticsearch {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-elasticsearch-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-elasticsearch-ca_file>> |a valid filesystem path|No|
| <<plugins-inputs-elasticsearch-codec>> |<<codec,codec>>|No|`"json"`
| <<plugins-inputs-elasticsearch-docinfo>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-elasticsearch-docinfo_fields>> |<<array,array>>|No|`["_index", "_type", "_id"]`
| <<plugins-inputs-elasticsearch-docinfo_target>> |<<string,string>>|No|`"@metadata"`
| <<plugins-inputs-elasticsearch-hosts>> |<<array,array>>|No|
| <<plugins-inputs-elasticsearch-index>> |<<string,string>>|No|`"logstash-*"`
| <<plugins-inputs-elasticsearch-password>> |<<password,password>>|No|
| <<plugins-inputs-elasticsearch-port>> |<<number,number>>|No|`9200`
| <<plugins-inputs-elasticsearch-query>> |<<string,string>>|No|`"{\"query\": { \"match_all\": {} } }"`
| <<plugins-inputs-elasticsearch-scan>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-elasticsearch-scroll>> |<<string,string>>|No|`"1m"`
| <<plugins-inputs-elasticsearch-size>> |<<number,number>>|No|`1000`
| <<plugins-inputs-elasticsearch-ssl>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-elasticsearch-tags>> |<<array,array>>|No|
| <<plugins-inputs-elasticsearch-type>> |<<string,string>>|No|
| <<plugins-inputs-elasticsearch-user>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-elasticsearch-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-elasticsearch-ca_file]]
===== `ca_file` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL Certificate Authority file

[[plugins-inputs-elasticsearch-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `ASCII-8BIT`, `Big5`, `Big5-HKSCS`, `Big5-UAO`, `CP949`, `Emacs-Mule`, `EUC-JP`, `EUC-KR`, `EUC-TW`, `GB18030`, `GBK`, `ISO-8859-1`, `ISO-8859-2`, `ISO-8859-3`, `ISO-8859-4`, `ISO-8859-5`, `ISO-8859-6`, `ISO-8859-7`, `ISO-8859-8`, `ISO-8859-9`, `ISO-8859-10`, `ISO-8859-11`, `ISO-8859-13`, `ISO-8859-14`, `ISO-8859-15`, `ISO-8859-16`, `KOI8-R`, `KOI8-U`, `Shift_JIS`, `US-ASCII`, `UTF-8`, `UTF-16BE`, `UTF-16LE`, `UTF-32BE`, `UTF-32LE`, `Windows-1251`, `GB2312`, `IBM437`, `IBM737`, `IBM775`, `CP850`, `IBM852`, `CP852`, `IBM855`, `CP855`, `IBM857`, `IBM860`, `IBM861`, `IBM862`, `IBM863`, `IBM864`, `IBM865`, `IBM866`, `IBM869`, `Windows-1258`, `GB1988`, `macCentEuro`, `macCroatian`, `macCyrillic`, `macGreek`, `macIceland`, `macRoman`, `macRomania`, `macThai`, `macTurkish`, `macUkraine`, `CP950`, `CP951`, `stateless-ISO-2022-JP`, `eucJP-ms`, `CP51932`, `GB12345`, `ISO-2022-JP`, `ISO-2022-JP-2`, `CP50220`, `CP50221`, `Windows-1252`, `Windows-1250`, `Windows-1256`, `Windows-1253`, `Windows-1255`, `Windows-1254`, `TIS-620`, `Windows-874`, `Windows-1257`, `Windows-31J`, `MacJapanese`, `UTF-7`, `UTF8-MAC`, `UTF-16`, `UTF-32`, `UTF8-DoCoMo`, `SJIS-DoCoMo`, `UTF8-KDDI`, `SJIS-KDDI`, `ISO-2022-JP-KDDI`, `stateless-ISO-2022-JP-KDDI`, `UTF8-SoftBank`, `SJIS-SoftBank`, `BINARY`, `CP437`, `CP737`, `CP775`, `IBM850`, `CP857`, `CP860`, `CP861`, `CP862`, `CP863`, `CP864`, `CP865`, `CP866`, `CP869`, `CP1258`, `Big5-HKSCS:2008`, `eucJP`, `euc-jp-ms`, `eucKR`, `eucTW`, `EUC-CN`, `eucCN`, `CP936`, `ISO2022-JP`, `ISO2022-JP2`, `ISO8859-1`, `CP1252`, `ISO8859-2`, `CP1250`, `ISO8859-3`, `ISO8859-4`, `ISO8859-5`, `ISO8859-6`, `CP1256`, `ISO8859-7`, `CP1253`, `ISO8859-8`, `CP1255`, `ISO8859-9`, `CP1254`, `ISO8859-10`, `ISO8859-11`, `CP874`, `ISO8859-13`, `CP1257`, `ISO8859-14`, `ISO8859-15`, `ISO8859-16`, `CP878`, `CP932`, `csWindows31J`, `SJIS`, `PCK`, `MacJapan`, `ASCII`, `ANSI_X3.4-1968`, `646`, `CP65000`, `CP65001`, `UTF-8-MAC`, `UTF-8-HFS`, `UCS-2BE`, `UCS-4BE`, `UCS-4LE`, `CP1251`, `external`, `locale`
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-elasticsearch-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"json"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-elasticsearch-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-elasticsearch-docinfo]]
===== `docinfo` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If set, include Elasticsearch document information such as index, type, and
the id in the event.

It might be important to note, with regards to metadata, that if you're
ingesting documents with the intent to re-index them (or just update them)
that the `action` option in the elasticsearch output want's to know how to
handle those things. It can be dynamically assigned with a field 
added to the metadata.

Example
[source, ruby]
    input {
      elasticsearch {
        host => "es.production.mysite.org"
        index => "mydata-2018.09.*"
        query => "*"
        size => 500
        scroll => "5m"
        docinfo => true
      }
    }
    output {
      elasticsearch {
        index => "copy-of-production.%{[@metadata][_index]}"
        index_type => "%{[@metadata][_type]}"
        document_id => "%{[@metadata][_id]}"
      }
    }


[[plugins-inputs-elasticsearch-docinfo_fields]]
===== `docinfo_fields` 

  * Value type is <<array,array>>
  * Default value is `["_index", "_type", "_id"]`

List of document metadata to move to the `docinfo_target` field
To learn more about Elasticsearch metadata fields read
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_document_metadata.html

[[plugins-inputs-elasticsearch-docinfo_target]]
===== `docinfo_target` 

  * Value type is <<string,string>>
  * Default value is `"@metadata"`

Where to move the Elasticsearch document information by default we use the @metadata field.

[[plugins-inputs-elasticsearch-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-elasticsearch-hosts]]
===== `hosts` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

List of elasticsearch hosts to use for querying.

[[plugins-inputs-elasticsearch-index]]
===== `index` 

  * Value type is <<string,string>>
  * Default value is `"logstash-*"`

The index or alias to search.

[[plugins-inputs-elasticsearch-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-elasticsearch-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Basic Auth - password

[[plugins-inputs-elasticsearch-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `9200`

The HTTP port of your Elasticsearch server's REST interface.

[[plugins-inputs-elasticsearch-query]]
===== `query` 

  * Value type is <<string,string>>
  * Default value is `"{\"query\": { \"match_all\": {} } }"`

The query to be executed.

[[plugins-inputs-elasticsearch-scan]]
===== `scan` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Enable the Elasticsearch "scan" search type.  This will disable
sorting but increase speed and performance.

[[plugins-inputs-elasticsearch-scroll]]
===== `scroll` 

  * Value type is <<string,string>>
  * Default value is `"1m"`

This parameter controls the keepalive time in seconds of the scrolling
request and initiates the scrolling process. The timeout applies per
round trip (i.e. between the previous scan scroll request, to the next).

[[plugins-inputs-elasticsearch-size]]
===== `size` 

  * Value type is <<number,number>>
  * Default value is `1000`

This allows you to set the maximum number of hits returned per scroll.

[[plugins-inputs-elasticsearch-ssl]]
===== `ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

SSL

[[plugins-inputs-elasticsearch-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-elasticsearch-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-elasticsearch-user]]
===== `user` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Basic Auth - username


