[[plugins-inputs-eventlog]]
=== eventlog



This input will pull events from a http://msdn.microsoft.com/en-us/library/windows/desktop/bb309026%28v=vs.85%29.aspx[Windows Event Log]. Note that Windows Event Logs are stored on disk in a binary format and are only accessible from the Win32 API. This means Losgtash needs to be running as an agent on Windows servers where you wish to collect logs from, and will not be accesible across the network.

To collect Events from the System Event Log, use a config like:
[source,ruby]
    input {
      eventlog {
        type  => 'Win32-EventLog'
        logfile  => 'System'
      }
    }

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
eventlog {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-eventlog-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-eventlog-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-eventlog-logfile>> |<<string,string>>|No|`"Application"`
| <<plugins-inputs-eventlog-interval>> |<<number,number>>|No|`1000`
| <<plugins-inputs-eventlog-tags>> |<<array,array>>|No|
| <<plugins-inputs-eventlog-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-eventlog-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-eventlog-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-eventlog-logfile]]
===== `logfile` 

  * Value type is <<array,array>>
  * Default value is `["Application", "Security", "System"]`

Event Log Name. System and Security may require that privileges are given to the user running Logstash.
For more information, see: https://social.technet.microsoft.com/forums/windowsserver/en-US/d2f813db-6142-4b5b-8d86-253ebb740473/easy-way-to-read-security-log

[[plugins-inputs-eventlog-interval]]
===== `interval` 

  * Value type is <<number,number>>
  * Default value is `1000`
  
How frequently should tail check for new event logs in milliseconds

[[plugins-inputs-eventlog-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-eventlog-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


