[[plugins-inputs-gelf]]
=== gelf



This input will read GELF messages as events over the network,
making it a good choice if you already use Graylog2 today.

The main use case for this input is to leverage existing GELF
logging libraries such as the GELF log4j appender.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
gelf {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-gelf-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-gelf-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-gelf-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-gelf-port>> |<<number,number>>|No|`12201`
| <<plugins-inputs-gelf-remap>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-gelf-strip_leading_underscore>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-gelf-tags>> |<<array,array>>|No|
| <<plugins-inputs-gelf-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-gelf-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-gelf-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-gelf-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The IP address or hostname to listen on.

[[plugins-inputs-gelf-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `12201`

The port to listen on. Remember that ports less than 1024 (privileged
ports) may require root to use.

[[plugins-inputs-gelf-remap]]
===== `remap` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Whether or not to remap the GELF message fields to Logstash event fields or
leave them intact.

Remapping converts the following GELF fields to Logstash equivalents:

* `full\_message` becomes `event["message"]`.
* if there is no `full\_message`, `short\_message` becomes `event["message"]`.

[[plugins-inputs-gelf-strip_leading_underscore]]
===== `strip_leading_underscore` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Whether or not to remove the leading `\_` in GELF fields or leave them
in place. (Logstash < 1.2 did not remove them by default.). Note that
GELF version 1.1 format now requires all non-standard fields to be added
as an "additional" field, beginning with an underscore.

e.g. `\_foo` becomes `foo`


[[plugins-inputs-gelf-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-gelf-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


