[[plugins-inputs-gelf]]
=== gelf

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-input-gelf/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This input will read GELF messages as events over the network,
making it a good choice if you already use Graylog2 today.

The main use case for this input is to leverage existing GELF
logging libraries such as the GELF log4j appender. A library used
by this plugin has a bug which prevents it parsing uncompressed data.
If you use the log4j appender you need to configure it like this to force
gzip even for small messages:

  <Socket name="logstash" protocol="udp" host="logstash.example.com" port="5001">
     <GelfLayout compressionType="GZIP" compressionThreshold="1" />
  </Socket>



&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
gelf {
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-inputs-gelf-add_field>> |<<hash,hash>>|No
| <<plugins-inputs-gelf-codec>> |<<codec,codec>>|No
| <<plugins-inputs-gelf-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-inputs-gelf-host>> |<<string,string>>|No
| <<plugins-inputs-gelf-id>> |<<string,string>>|No
| <<plugins-inputs-gelf-port>> |<<number,number>>|No
| <<plugins-inputs-gelf-remap>> |<<boolean,boolean>>|No
| <<plugins-inputs-gelf-strip_leading_underscore>> |<<boolean,boolean>>|No
| <<plugins-inputs-gelf-tags>> |<<array,array>>|No
| <<plugins-inputs-gelf-type>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-gelf-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-gelf-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-gelf-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-gelf-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The IP address or hostname to listen on.

[[plugins-inputs-gelf-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-inputs-gelf-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `12201`

The port to listen on. Remember that ports less than 1024 (privileged
ports) may require root to use.

[[plugins-inputs-gelf-remap]]
===== `remap` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Whether or not to remap the GELF message fields to Logstash event fields or
leave them intact.

Remapping converts the following GELF fields to Logstash equivalents:

* `full\_message` becomes `event["message"]`.
* if there is no `full\_message`, `short\_message` becomes `event["message"]`.

[[plugins-inputs-gelf-strip_leading_underscore]]
===== `strip_leading_underscore` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Whether or not to remove the leading `\_` in GELF fields or leave them
in place. (Logstash < 1.2 did not remove them by default.). Note that
GELF version 1.1 format now requires all non-standard fields to be added
as an "additional" field, beginning with an underscore.

e.g. `\_foo` becomes `foo`


[[plugins-inputs-gelf-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-gelf-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This is the base class for Logstash inputs.
Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


