[[plugins-inputs-generator]]
=== generator

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-input-generator/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



Generate random log events.

The general intention of this is to test performance of plugins.

An event is generated first

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
generator {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-generator-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-generator-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-generator-count>> |<<number,number>>|No|`0`
| <<plugins-inputs-generator-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-generator-id>> |<<string,string>>|No|
| <<plugins-inputs-generator-lines>> |<<array,array>>|No|
| <<plugins-inputs-generator-message>> |<<string,string>>|No|`"Hello world!"`
| <<plugins-inputs-generator-tags>> |<<array,array>>|No|
| <<plugins-inputs-generator-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-generator-type>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-generator-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-generator-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-generator-count]]
===== `count` 

  * Value type is <<number,number>>
  * Default value is `0`

Set how many messages should be generated.

The default, `0`, means generate an unlimited number of events.

[[plugins-inputs-generator-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-generator-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-generator-lines]]
===== `lines` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

The lines to emit, in order. This option cannot be used with the 'message'
setting.

Example:
[source,ruby]
    input {
      generator {
        lines => [
          "line 1",
          "line 2",
          "line 3"
        ]
        # Emit all lines 3 times.
        count => 3
      }
    }

The above will emit `line 1` then `line 2` then `line`, then `line 1`, etc...

[[plugins-inputs-generator-message]]
===== `message` 

  * Value type is <<string,string>>
  * Default value is `"Hello world!"`

The message string to use in the event.

If you set this to `stdin` then this plugin will read a single line from
stdin and use that as the message string for every event.

Otherwise, this value will be used verbatim as the event message.

[[plugins-inputs-generator-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-generator-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`



[[plugins-inputs-generator-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


