[[plugins-inputs-graphite]]
=== graphite

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-input-graphite/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



Receive graphite metrics. This plugin understands the text-based graphite
carbon protocol. Both `N` and `specific-timestamp` forms are supported, example:
[source,ruby]
    mysql.slow_query.count 204 N
    haproxy.live_backends 7 1364608909

`N` means `now` for a timestamp. This plugin also supports having the time
specified in the metric payload:

For every metric received from a client, a single event will be emitted with
the metric name as the field (like `mysql.slow_query.count`) and the metric
value as the field's value.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
graphite {
    port => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-graphite-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-graphite-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-graphite-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-graphite-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-graphite-id>> |<<string,string>>|No|
| <<plugins-inputs-graphite-mode>> |<<string,string>>, one of `["server", "client"]`|No|`"server"`
| <<plugins-inputs-graphite-port>> |<<number,number>>|Yes|
| <<plugins-inputs-graphite-proxy_protocol>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-graphite-ssl_cert>> |a valid filesystem path|No|
| <<plugins-inputs-graphite-ssl_enable>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-graphite-ssl_extra_chain_certs>> |<<array,array>>|No|`[]`
| <<plugins-inputs-graphite-ssl_key>> |a valid filesystem path|No|
| <<plugins-inputs-graphite-ssl_key_passphrase>> |<<password,password>>|No|`nil`
| <<plugins-inputs-graphite-ssl_verify>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-graphite-tags>> |<<array,array>>|No|
| <<plugins-inputs-graphite-type>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-graphite-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-graphite-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-graphite-data_timeout]]
===== `data_timeout`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<number,number>>
  * Default value is `-1`



[[plugins-inputs-graphite-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-graphite-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

When mode is `server`, the address to listen on.
When mode is `client`, the address to connect to.

[[plugins-inputs-graphite-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-graphite-mode]]
===== `mode` 

  * Value can be any of: `server`, `client`
  * Default value is `"server"`

Mode to operate in. `server` listens for client connections,
`client` connects to a server.

[[plugins-inputs-graphite-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

When mode is `server`, the port to listen on.
When mode is `client`, the port to connect to.

[[plugins-inputs-graphite-proxy_protocol]]
===== `proxy_protocol` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Proxy protocol support, only v1 is supported at this time
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

[[plugins-inputs-graphite-ssl_cacert]]
===== `ssl_cacert`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<path,path>>
  * There is no default value for this setting.

The SSL CA certificate, chainfile or CA path. The system CA path is automatically included.

[[plugins-inputs-graphite-ssl_cert]]
===== `ssl_cert` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL certificate path

[[plugins-inputs-graphite-ssl_enable]]
===== `ssl_enable` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Enable SSL (must be set for other `ssl_` options to take effect).

[[plugins-inputs-graphite-ssl_extra_chain_certs]]
===== `ssl_extra_chain_certs` 

  * Value type is <<array,array>>
  * Default value is `[]`

An Array of extra X509 certificates to be added to the certificate chain.
Useful when the CA chain is not necessary in the system store.

[[plugins-inputs-graphite-ssl_key]]
===== `ssl_key` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL key path

[[plugins-inputs-graphite-ssl_key_passphrase]]
===== `ssl_key_passphrase` 

  * Value type is <<password,password>>
  * Default value is `nil`

SSL key passphrase

[[plugins-inputs-graphite-ssl_verify]]
===== `ssl_verify` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Verify the identity of the other end of the SSL connection against the CA.
For input, sets the field `sslsubject` to that of the client certificate.

[[plugins-inputs-graphite-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-graphite-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


