[[plugins-inputs-http]]
=== http



Using this input you can receive single or multiline events over http(s).
Applications can send a HTTP POST request with a body to the endpoint started by this
input and Logstash will convert it into an event for subsequent processing. Users 
can pass plain text, JSON, or any formatted data and use a corresponding codec with this
input. For Content-Type `application/json` the `json` codec is used, but for all other
data formats, `plain` codec is used.

This input can also be used to receive webhook requests to integrate with other services
and applications. By taking advantage of the vast plugin ecosystem available in Logstash
you can trigger actionable events right from your application.

==== Security
This plugin supports standard HTTP basic authentication headers to identify the requester.
You can pass in an username, password combination while sending data to this input

You can also setup SSL and send data securely over https, with an option of validating 
the client's certificate. Currently, the certificate setup is through 
https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html[Java Keystore 
format]


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
http {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-http-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-http-additional_codecs>> |<<hash,hash>>|No|`{"application/json"=>"json"}`
| <<plugins-inputs-http-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-http-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-http-keystore>> |a valid filesystem path|No|
| <<plugins-inputs-http-keystore_password>> |<<password,password>>|No|
| <<plugins-inputs-http-password>> |<<password,password>>|No|
| <<plugins-inputs-http-port>> |<<number,number>>|No|`8080`
| <<plugins-inputs-http-ssl>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-http-tags>> |<<array,array>>|No|
| <<plugins-inputs-http-threads>> |<<number,number>>|No|`4`
| <<plugins-inputs-http-type>> |<<string,string>>|No|
| <<plugins-inputs-http-user>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-http-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-http-additional_codecs]]
===== `additional_codecs` 

  * Value type is <<hash,hash>>
  * Default value is `{"application/json"=>"json"}`

Here you can set how to decode specific content-types in the body of the request.
By default, the plain codec will be used

[[plugins-inputs-http-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  <li> Value type is <<string,string>>
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-http-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-http-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-http-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-http-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The host or ip to bind

[[plugins-inputs-http-keystore]]
===== `keystore` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

The JKS keystore to validate the client's certificates

[[plugins-inputs-http-keystore_password]]
===== `keystore_password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Set the truststore password

[[plugins-inputs-http-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-http-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password for basic authentication

[[plugins-inputs-http-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `8080`

The TCP port to bind to

[[plugins-inputs-http-ssl]]
===== `ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Enable SSL

[[plugins-inputs-http-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-http-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `4`

Maximum number of threads to use

[[plugins-inputs-http-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-http-user]]
===== `user` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Username for basic authorization


