[[plugins-inputs-kafka]]
=== kafka



This input will read events from a Kafka topic. It uses the the newly designed
0.9 version of https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design[consumer API] 
provided by Kafka to read messages from the broker.

NOTE: This plugin version (3.0.0) is not backward compatible with 0.8.x brokers and needs a 0.9 broker.

The Logstash Kafka consumer handles group management and uses the default offset management
strategy using Kafka topics.

Logstash instances by default form a single logical group to subscribe to Kafka topics
Each Logstash Kafka consumer can run multiple threads to increase read throughput. Alternatively, 
you could run multiple Logstash instances with the same `group_id` to spread the load across
physical machines. Messages in a topic will be distributed to all Logstash instances with 
the same `group_id`.

Ideally you should have as many threads as the number of partitions for a perfect balance --
more threads than partitions means that some threads will be idle

For more information see http://kafka.apache.org/documentation.html#theconsumer

Kafka consumer configuration: http://kafka.apache.org/documentation.html#consumerconfigs

This version also adds support for SSL/TLS security connection to Kafka. By default SSL is 
disabled but can be turned on as needed.

Breaking change: This version also changes the default codec from json to plain

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
kafka {
    topics => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-kafka-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-kafka-auto_commit_interval_ms>> |<<string,string>>|No|`"10"`
| <<plugins-inputs-kafka-auto_offset_reset>> |<<string,string>>|No|
| <<plugins-inputs-kafka-bootstrap_servers>> |<<string,string>>|No|`"localhost:9092"`
| <<plugins-inputs-kafka-check_crcs>> |<<string,string>>|No|
| <<plugins-inputs-kafka-client_id>> |<<string,string>>|No|`"logstash"`
| <<plugins-inputs-kafka-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-kafka-connections_max_idle_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-consumer_threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-kafka-enable_auto_commit>> |<<string,string>>|No|`"true"`
| <<plugins-inputs-kafka-fetch_max_wait_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-fetch_min_bytes>> |<<string,string>>|No|
| <<plugins-inputs-kafka-group_id>> |<<string,string>>|No|`"logstash"`
| <<plugins-inputs-kafka-heartbeat_interval_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-key_deserializer_class>> |<<string,string>>|No|`"org.apache.kafka.common.serialization.StringDeserializer"`
| <<plugins-inputs-kafka-max_partition_fetch_bytes>> |<<string,string>>|No|
| <<plugins-inputs-kafka-partition_assignment_strategy>> |<<string,string>>|No|
| <<plugins-inputs-kafka-poll_timeout_ms>> |<<number,number>>|No|`100`
| <<plugins-inputs-kafka-receive_buffer_bytes>> |<<string,string>>|No|
| <<plugins-inputs-kafka-reconnect_backoff_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-request_timeout_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-retry_backoff_ms>> |<<string,string>>|No|
| <<plugins-inputs-kafka-session_timeout_ms>> |<<string,string>>|No|`"30000"`
| <<plugins-inputs-kafka-ssl>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-kafka-ssl_keystore_location>> |a valid filesystem path|No|
| <<plugins-inputs-kafka-ssl_keystore_password>> |<<password,password>>|No|
| <<plugins-inputs-kafka-ssl_truststore_location>> |a valid filesystem path|No|
| <<plugins-inputs-kafka-ssl_truststore_password>> |<<password,password>>|No|
| <<plugins-inputs-kafka-tags>> |<<array,array>>|No|
| <<plugins-inputs-kafka-topics>> |<<array,array>>|Yes|
| <<plugins-inputs-kafka-type>> |<<string,string>>|No|
| <<plugins-inputs-kafka-value_deserializer_class>> |<<string,string>>|No|`"org.apache.kafka.common.serialization.StringDeserializer"`
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-kafka-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-kafka-auto_commit_interval_ms]]
===== `auto_commit_interval_ms` 

  * Value type is <<string,string>>
  * Default value is `"10"`

The frequency in milliseconds that the consumer offsets are committed to Kafka.

[[plugins-inputs-kafka-auto_offset_reset]]
===== `auto_offset_reset` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

What to do when there is no initial offset in Kafka or if an offset is out of range:

* earliest: automatically reset the offset to the earliest offset
* latest: automatically reset the offset to the latest offset
* none: throw exception to the consumer if no previous offset is found for the consumer's group
* anything else: throw exception to the consumer.

[[plugins-inputs-kafka-bootstrap_servers]]
===== `bootstrap_servers` 

  * Value type is <<string,string>>
  * Default value is `"localhost:9092"`

A list of URLs to use for establishing the initial connection to the cluster. 
This list should be in the form of `host1:port1,host2:port2` These urls are just used 
for the initial connection to discover the full cluster membership (which may change dynamically) 
so this list need not contain the full set of servers (you may want more than one, though, in 
case a server is down).

[[plugins-inputs-kafka-check_crcs]]
===== `check_crcs` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Automatically check the CRC32 of the records consumed. This ensures no on-the-wire or on-disk 
corruption to the messages occurred. This check adds some overhead, so it may be 
disabled in cases seeking extreme performance.

[[plugins-inputs-kafka-client_id]]
===== `client_id` 

  * Value type is <<string,string>>
  * Default value is `"logstash"`

The id string to pass to the server when making requests. The purpose of this 
is to be able to track the source of requests beyond just ip/port by allowing 
a logical application name to be included.

[[plugins-inputs-kafka-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-kafka-connections_max_idle_ms]]
===== `connections_max_idle_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Close idle connections after the number of milliseconds specified by this config.

[[plugins-inputs-kafka-consumer_threads]]
===== `consumer_threads` 

  * Value type is <<number,number>>
  * Default value is `1`

Ideally you should have as many threads as the number of partitions for a perfect 
balance — more threads than partitions means that some threads will be idle

[[plugins-inputs-kafka-enable_auto_commit]]
===== `enable_auto_commit` 

  * Value type is <<string,string>>
  * Default value is `"true"`

If true, periodically commit to Kafka the offsets of messages already returned by the consumer. 
This committed offset will be used when the process fails as the position from 
which the consumption will begin.

[[plugins-inputs-kafka-fetch_max_wait_ms]]
===== `fetch_max_wait_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The maximum amount of time the server will block before answering the fetch request if 
there isn't sufficient data to immediately satisfy `fetch_min_bytes`. This 
should be less than or equal to the timeout used in `poll_timeout_ms`

[[plugins-inputs-kafka-fetch_min_bytes]]
===== `fetch_min_bytes` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The minimum amount of data the server should return for a fetch request. If insufficient 
data is available the request will wait for that much data to accumulate
before answering the request.

[[plugins-inputs-kafka-group_id]]
===== `group_id` 

  * Value type is <<string,string>>
  * Default value is `"logstash"`

The identifier of the group this consumer belongs to. Consumer group is a single logical subscriber 
that happens to be made up of multiple processors. Messages in a topic will be distributed to all 
Logstash instances with the same `group_id`

[[plugins-inputs-kafka-heartbeat_interval_ms]]
===== `heartbeat_interval_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The expected time between heartbeats to the consumer coordinator. Heartbeats are used to ensure 
that the consumer's session stays active and to facilitate rebalancing when new
consumers join or leave the group. The value must be set lower than 
`session.timeout.ms`, but typically should be set no higher than 1/3 of that value. 
It can be adjusted even lower to control the expected time for normal rebalances.

[[plugins-inputs-kafka-key_deserializer_class]]
===== `key_deserializer_class` 

  * Value type is <<string,string>>
  * Default value is `"org.apache.kafka.common.serialization.StringDeserializer"`

Java Class used to deserialize the record's key

[[plugins-inputs-kafka-max_partition_fetch_bytes]]
===== `max_partition_fetch_bytes` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The maximum amount of data per-partition the server will return. The maximum total memory used for a 
request will be <code>#partitions * max.partition.fetch.bytes</code>. This size must be at least 
as large as the maximum message size the server allows or else it is possible for the producer to 
send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying 
to fetch a large message on a certain partition.

[[plugins-inputs-kafka-partition_assignment_strategy]]
===== `partition_assignment_strategy` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The class name of the partition assignment strategy that the client will use to distribute 
partition ownership amongst consumer instances

[[plugins-inputs-kafka-poll_timeout_ms]]
===== `poll_timeout_ms` 

  * Value type is <<number,number>>
  * Default value is `100`

Time kafka consumer will wait to receive new messages from topics

[[plugins-inputs-kafka-receive_buffer_bytes]]
===== `receive_buffer_bytes` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The size of the TCP receive buffer (SO_RCVBUF) to use when reading data.

[[plugins-inputs-kafka-reconnect_backoff_ms]]
===== `reconnect_backoff_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The amount of time to wait before attempting to reconnect to a given host. 
This avoids repeatedly connecting to a host in a tight loop. 
This backoff applies to all requests sent by the consumer to the broker.

[[plugins-inputs-kafka-request_timeout_ms]]
===== `request_timeout_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The configuration controls the maximum amount of time the client will wait 
for the response of a request. If the response is not received before the timeout 
elapses the client will resend the request if necessary or fail the request if 
retries are exhausted.

[[plugins-inputs-kafka-retry_backoff_ms]]
===== `retry_backoff_ms` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The amount of time to wait before attempting to retry a failed fetch request 
to a given topic partition. This avoids repeated fetching-and-failing in a tight loop.

[[plugins-inputs-kafka-session_timeout_ms]]
===== `session_timeout_ms` 

  * Value type is <<string,string>>
  * Default value is `"30000"`

The timeout after which, if the `poll_timeout_ms` is not invoked, the consumer is marked dead 
and a rebalance operation is triggered for the group identified by `group_id`

[[plugins-inputs-kafka-ssl]]
===== `ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Enable SSL/TLS secured communication to Kafka broker. Note that secure communication 
is only available with a broker running v0.9 of Kafka.

[[plugins-inputs-kafka-ssl_keystore_location]]
===== `ssl_keystore_location` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If client authentication is required, this setting stores the keystore path.

[[plugins-inputs-kafka-ssl_keystore_password]]
===== `ssl_keystore_password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

If client authentication is required, this setting stores the keystore password

[[plugins-inputs-kafka-ssl_truststore_location]]
===== `ssl_truststore_location` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

The JKS truststore path to validate the Kafka broker's certificate.

[[plugins-inputs-kafka-ssl_truststore_password]]
===== `ssl_truststore_password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

The truststore password

[[plugins-inputs-kafka-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-kafka-topics]]
===== `topics` 

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

A list of topics to subscribe to.

[[plugins-inputs-kafka-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-kafka-value_deserializer_class]]
===== `value_deserializer_class` 

  * Value type is <<string,string>>
  * Default value is `"org.apache.kafka.common.serialization.StringDeserializer"`

Java Class used to deserialize the record's value


