[[plugins-inputs-log4j]]
=== log4j



Read events over a TCP socket from a Log4j SocketAppender. This plugin works only with log4j version 1.x.

Can either accept connections from clients or connect to a server,
depending on `mode`. Depending on which `mode` is configured,
you need a matching SocketAppender or a SocketHubAppender
on the remote side.

One event is created per received log4j LoggingEvent with the following schema:

* `timestamp` => the number of milliseconds elapsed from 1/1/1970 until logging event was created.
* `path` => the name of the logger
* `priority` => the level of this event
* `logger_name` => the name of the logger
* `thread` => the thread name making the logging request
* `class` => the fully qualified class name of the caller making the logging request.
* `file` => the source file name and line number of the caller making the logging request in a colon-separated format "fileName:lineNumber".
* `method` => the method name of the caller making the logging request.
* `NDC` => the NDC string
* `stack_trace` => the multi-line stack-trace

Also if the original log4j LoggingEvent contains MDC hash entries, they will be merged in the event as fields.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
log4j {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-log4j-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-log4j-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-log4j-data_timeout>> |<<number,number>>|No|`5`
| <<plugins-inputs-log4j-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-log4j-mode>> |<<string,string>>, one of `["server", "client"]`|No|`"server"`
| <<plugins-inputs-log4j-port>> |<<number,number>>|No|`4560`
| <<plugins-inputs-log4j-tags>> |<<array,array>>|No|
| <<plugins-inputs-log4j-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-log4j-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-log4j-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-log4j-data_timeout]]
===== `data_timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

Read timeout in seconds. If a particular TCP connection is
idle for more than this timeout period, we will assume
it is dead and close it.
If you never want to timeout, use -1.

[[plugins-inputs-log4j-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

When mode is `server`, the address to listen on.
When mode is `client`, the address to connect to.

[[plugins-inputs-log4j-mode]]
===== `mode` 

  * Value can be any of: `server`, `client`
  * Default value is `"server"`

Mode to operate in. `server` listens for client connections,
`client` connects to a server.

[[plugins-inputs-log4j-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `4560`

When mode is `server`, the port to listen on.
When mode is `client`, the port to connect to.

[[plugins-inputs-log4j-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-log4j-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


