[[plugins-inputs-lumberjack]]
=== lumberjack

* Version: 3.1.1
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-input-lumberjack/blob/master/CHANGELOG.md#311[Changelog]



Receive events using the lumberjack protocol.

This is mainly to receive events shipped with lumberjack[http://github.com/jordansissel/lumberjack],
now represented primarily via the
https://github.com/elasticsearch/logstash-forwarder[Logstash-forwarder].


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
lumberjack {
    port => ...
    ssl_certificate => ...
    ssl_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-lumberjack-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-lumberjack-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-lumberjack-congestion_threshold>> |<<number,number>>|No|`5`
| <<plugins-inputs-lumberjack-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-lumberjack-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-lumberjack-id>> |<<string,string>>|No|
| <<plugins-inputs-lumberjack-port>> |<<number,number>>|Yes|
| <<plugins-inputs-lumberjack-ssl_certificate>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key_passphrase>> |<<password,password>>|No|
| <<plugins-inputs-lumberjack-tags>> |<<array,array>>|No|
| <<plugins-inputs-lumberjack-type>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-lumberjack-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-lumberjack-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-lumberjack-congestion_threshold]]
===== `congestion_threshold` 

  * Value type is <<number,number>>
  * Default value is `5`

The number of seconds before we raise a timeout,
this option is useful to control how much time to wait if something is blocking the pipeline.

[[plugins-inputs-lumberjack-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-lumberjack-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The IP address to listen on.

[[plugins-inputs-lumberjack-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-inputs-lumberjack-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

The port to listen on.

[[plugins-inputs-lumberjack-ssl_certificate]]
===== `ssl_certificate` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL certificate to use.

[[plugins-inputs-lumberjack-ssl_key]]
===== `ssl_key` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL key to use.

[[plugins-inputs-lumberjack-ssl_key_passphrase]]
===== `ssl_key_passphrase` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

SSL key passphrase to use.

[[plugins-inputs-lumberjack-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-lumberjack-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


