[[plugins-inputs-lumberjack]]
=== lumberjack

Receive events using the Lumberjack protocol.

This input can be used to reliably and securely transport
events between Logstash instances. To do so, use the
<<plugins-outputs-lumberjack,lumberjack output plugin>>
in the sending Logstash instance(s).

It can also be used to receive events from the deprecated
https://github.com/elastic/logstash-forwarder[logstash-forwarder]
tool that has been replaced by
https://github.com/elastic/beats/tree/master/filebeat[Filebeat].

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
lumberjack {
    port => ...
    ssl_certificate => ...
    ssl_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-lumberjack-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-lumberjack-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-lumberjack-congestion_threshold>> |<<number,number>>|No|`5`
| <<plugins-inputs-lumberjack-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-lumberjack-port>> |<<number,number>>|Yes|
| <<plugins-inputs-lumberjack-ssl_certificate>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key_passphrase>> |<<password,password>>|No|
| <<plugins-inputs-lumberjack-tags>> |<<array,array>>|No|
| <<plugins-inputs-lumberjack-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-lumberjack-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-lumberjack-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-lumberjack-congestion_threshold]]
===== `congestion_threshold` 

  * Value type is <<number,number>>
  * Default value is `5`

The number of seconds before we raise a timeout,
this option is useful to control how much time to wait if something is blocking the pipeline.

[[plugins-inputs-lumberjack-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The IP address to listen on.

[[plugins-inputs-lumberjack-max_clients]]
===== `max_clients`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<number,number>>
  * There is no default value for this setting.

This setting no longer has any effect and will be removed in a future release.

[[plugins-inputs-lumberjack-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

The port to listen on.

[[plugins-inputs-lumberjack-ssl_certificate]]
===== `ssl_certificate` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL certificate to use.

[[plugins-inputs-lumberjack-ssl_key]]
===== `ssl_key` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL key to use.

[[plugins-inputs-lumberjack-ssl_key_passphrase]]
===== `ssl_key_passphrase` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

SSL key passphrase to use.

[[plugins-inputs-lumberjack-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-lumberjack-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


