[[plugins-inputs-redis]]
=== redis

Version: 3.1.1
Released on: 2016-07-14
https://github.com/logstash-plugins/logstash-input-redis/blob/master/CHANGELOG.md#311[Changelog]
Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



This input will read events from a Redis instance; it supports both Redis channels and lists.
The list command (BLPOP) used by Logstash is supported in Redis v1.3.1+, and
the channel commands used by Logstash are found in Redis v1.3.8+.
While you may be able to make these Redis versions work, the best performance
and stability will be found in more recent stable versions.  Versions 2.6.0+
are recommended.

For more information about Redis, see <http://redis.io/>

`batch_count` note: If you use the `batch_count` setting, you *must* use a Redis version 2.6.0 or
newer. Anything older does not support the operations used by batching.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
redis {
    data_type => ...
    key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-redis-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-redis-batch_count>> |<<number,number>>|No|`125`
| <<plugins-inputs-redis-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-redis-data_type>> |<<string,string>>, one of `["list", "channel", "pattern_channel"]`|Yes|
| <<plugins-inputs-redis-db>> |<<number,number>>|No|`0`
| <<plugins-inputs-redis-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-redis-host>> |<<string,string>>|No|`"127.0.0.1"`
| <<plugins-inputs-redis-id>> |<<string,string>>|No|
| <<plugins-inputs-redis-key>> |<<string,string>>|Yes|
| <<plugins-inputs-redis-password>> |<<password,password>>|No|
| <<plugins-inputs-redis-port>> |<<number,number>>|No|`6379`
| <<plugins-inputs-redis-tags>> |<<array,array>>|No|
| <<plugins-inputs-redis-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-redis-timeout>> |<<number,number>>|No|`5`
| <<plugins-inputs-redis-type>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-redis-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-redis-batch_count]]
===== `batch_count` 

  * Value type is <<number,number>>
  * Default value is `125`

The number of events to return from Redis using EVAL.

[[plugins-inputs-redis-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-redis-data_type]]
===== `data_type` 

  * This is a required setting.
  * Value can be any of: `list`, `channel`, `pattern_channel`
  * There is no default value for this setting.

Specify either list or channel.  If `redis\_type` is `list`, then we will BLPOP the
key.  If `redis\_type` is `channel`, then we will SUBSCRIBE to the key.
If `redis\_type` is `pattern_channel`, then we will PSUBSCRIBE to the key.

[[plugins-inputs-redis-db]]
===== `db` 

  * Value type is <<number,number>>
  * Default value is `0`

The Redis database number.

[[plugins-inputs-redis-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-redis-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"127.0.0.1"`

The hostname of your Redis server.

[[plugins-inputs-redis-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-redis-key]]
===== `key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of a Redis list or channel.

[[plugins-inputs-redis-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password to authenticate with. There is no authentication by default.

[[plugins-inputs-redis-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `6379`

The port to connect on.

[[plugins-inputs-redis-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-redis-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`



[[plugins-inputs-redis-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

Initial connection timeout in seconds.

[[plugins-inputs-redis-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


