[[plugins-inputs-redis]]
=== redis



This input will read events from a Redis instance; it supports both Redis channels and lists.
The list command (BLPOP) used by Logstash is supported in Redis v1.3.1+, and
the channel commands used by Logstash are found in Redis v1.3.8+.
While you may be able to make these Redis versions work, the best performance
and stability will be found in more recent stable versions.  Versions 2.6.0+
are recommended.

For more information about Redis, see <http://redis.io/>

`batch_count` note: If you use the `batch_count` setting, you *must* use a Redis version 2.6.0 or
newer. Anything older does not support the operations used by batching.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
redis {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-redis-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-redis-batch_count>> |<<number,number>>|No|`1`
| <<plugins-inputs-redis-codec>> |<<codec,codec>>|No|`"json"`
| <<plugins-inputs-redis-data_type>> |<<string,string>>, one of `["list", "channel", "pattern_channel"]`|No|
| <<plugins-inputs-redis-db>> |<<number,number>>|No|`0`
| <<plugins-inputs-redis-host>> |<<string,string>>|No|`"127.0.0.1"`
| <<plugins-inputs-redis-key>> |<<string,string>>|No|
| <<plugins-inputs-redis-password>> |<<password,password>>|No|
| <<plugins-inputs-redis-port>> |<<number,number>>|No|`6379`
| <<plugins-inputs-redis-tags>> |<<array,array>>|No|
| <<plugins-inputs-redis-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-redis-timeout>> |<<number,number>>|No|`5`
| <<plugins-inputs-redis-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-redis-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-redis-batch_count]]
===== `batch_count` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of events to return from Redis using EVAL.

[[plugins-inputs-redis-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `ASCII-8BIT`, `Big5`, `Big5-HKSCS`, `Big5-UAO`, `CP949`, `Emacs-Mule`, `EUC-JP`, `EUC-KR`, `EUC-TW`, `GB18030`, `GBK`, `ISO-8859-1`, `ISO-8859-2`, `ISO-8859-3`, `ISO-8859-4`, `ISO-8859-5`, `ISO-8859-6`, `ISO-8859-7`, `ISO-8859-8`, `ISO-8859-9`, `ISO-8859-10`, `ISO-8859-11`, `ISO-8859-13`, `ISO-8859-14`, `ISO-8859-15`, `ISO-8859-16`, `KOI8-R`, `KOI8-U`, `Shift_JIS`, `US-ASCII`, `UTF-8`, `UTF-16BE`, `UTF-16LE`, `UTF-32BE`, `UTF-32LE`, `Windows-1251`, `GB2312`, `IBM437`, `IBM737`, `IBM775`, `CP850`, `IBM852`, `CP852`, `IBM855`, `CP855`, `IBM857`, `IBM860`, `IBM861`, `IBM862`, `IBM863`, `IBM864`, `IBM865`, `IBM866`, `IBM869`, `Windows-1258`, `GB1988`, `macCentEuro`, `macCroatian`, `macCyrillic`, `macGreek`, `macIceland`, `macRoman`, `macRomania`, `macThai`, `macTurkish`, `macUkraine`, `CP950`, `CP951`, `stateless-ISO-2022-JP`, `eucJP-ms`, `CP51932`, `GB12345`, `ISO-2022-JP`, `ISO-2022-JP-2`, `CP50220`, `CP50221`, `Windows-1252`, `Windows-1250`, `Windows-1256`, `Windows-1253`, `Windows-1255`, `Windows-1254`, `TIS-620`, `Windows-874`, `Windows-1257`, `Windows-31J`, `MacJapanese`, `UTF-7`, `UTF8-MAC`, `UTF-16`, `UTF-32`, `UTF8-DoCoMo`, `SJIS-DoCoMo`, `UTF8-KDDI`, `SJIS-KDDI`, `ISO-2022-JP-KDDI`, `stateless-ISO-2022-JP-KDDI`, `UTF8-SoftBank`, `SJIS-SoftBank`, `BINARY`, `CP437`, `CP737`, `CP775`, `IBM850`, `CP857`, `CP860`, `CP861`, `CP862`, `CP863`, `CP864`, `CP865`, `CP866`, `CP869`, `CP1258`, `Big5-HKSCS:2008`, `eucJP`, `euc-jp-ms`, `eucKR`, `eucTW`, `EUC-CN`, `eucCN`, `CP936`, `ISO2022-JP`, `ISO2022-JP2`, `ISO8859-1`, `CP1252`, `ISO8859-2`, `CP1250`, `ISO8859-3`, `ISO8859-4`, `ISO8859-5`, `ISO8859-6`, `CP1256`, `ISO8859-7`, `CP1253`, `ISO8859-8`, `CP1255`, `ISO8859-9`, `CP1254`, `ISO8859-10`, `ISO8859-11`, `CP874`, `ISO8859-13`, `CP1257`, `ISO8859-14`, `ISO8859-15`, `ISO8859-16`, `CP878`, `CP932`, `csWindows31J`, `SJIS`, `PCK`, `MacJapan`, `ASCII`, `ANSI_X3.4-1968`, `646`, `CP65000`, `CP65001`, `UTF-8-MAC`, `UTF-8-HFS`, `UCS-2BE`, `UCS-4BE`, `UCS-4LE`, `CP1251`, `external`, `locale`
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-redis-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"json"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-redis-data_type]]
===== `data_type` 

  * Value can be any of: `list`, `channel`, `pattern_channel`
  * There is no default value for this setting.

Specify either list or channel.  If `redis\_type` is `list`, then we will BLPOP the
key.  If `redis\_type` is `channel`, then we will SUBSCRIBE to the key.
If `redis\_type` is `pattern_channel`, then we will PSUBSCRIBE to the key.
TODO: change required to true

[[plugins-inputs-redis-db]]
===== `db` 

  * Value type is <<number,number>>
  * Default value is `0`

The Redis database number.

[[plugins-inputs-redis-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-redis-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-redis-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"127.0.0.1"`

The hostname of your Redis server.

[[plugins-inputs-redis-key]]
===== `key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of a Redis list or channel.
TODO: change required to true

[[plugins-inputs-redis-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-redis-name]]
===== `name`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `"default"`

The `name` configuration is used for logging in case there are multiple instances.
This feature has no real function and will be removed in future versions.

[[plugins-inputs-redis-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password to authenticate with. There is no authentication by default.

[[plugins-inputs-redis-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `6379`

The port to connect on.

[[plugins-inputs-redis-queue]]
===== `queue`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the Redis queue (we'll use BLPOP against this).
TODO: remove soon.

[[plugins-inputs-redis-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-redis-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`

Set this to the number of threads you want this input to spawn.
This is the same as declaring the input multiple times

[[plugins-inputs-redis-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

Initial connection timeout in seconds.

[[plugins-inputs-redis-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in the web interface.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at 
the shipper stays with that event for its life even
when sent to another Logstash server.


