[[plugins-inputs-rss]]
=== rss


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-input-rss`.


Run command line tools and capture the whole output as an event.

Notes:

* The `@source` of this event will be the command run.
* The `@message` of this event will be the entire stdout of the command
  as one event.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
rss {
    interval => ...
    url => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-rss-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-rss-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-rss-interval>> |<<number,number>>|Yes|
| <<plugins-inputs-rss-tags>> |<<array,array>>|No|
| <<plugins-inputs-rss-type>> |<<string,string>>|No|
| <<plugins-inputs-rss-url>> |<<string,string>>|Yes|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-rss-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-rss-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-rss-interval]]
===== `interval` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

Interval to run the command. Value is in seconds.

[[plugins-inputs-rss-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-rss-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-rss-url]]
===== `url` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

RSS/Atom feed URL


