[[plugins-inputs-salesforce]]
=== salesforce

* Version: 3.0.0
* Released on: 2017-01-24
* https://github.com/logstash-plugins/logstash-input-salesforce/blob/master/CHANGELOG.md#300[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4


NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-input-salesforce`.


This Logstash input plugin allows you to query Salesforce using SOQL and puts the results
into Logstash, one row per event. You can configure it to pull entire sObjects or only
specific fields.

NOTE: This input plugin will stop after all the results of the query are processed and will
need to be re-run to fetch new results. It does not utilize the streaming API.

In order to use this plugin, you will need to create a new SFDC Application using
oauth. More details can be found here:
https://help.salesforce.com/apex/HTViewHelpDoc?id=connected_app_create.htm

You will also need a username, password, and security token for your salesforce instance.
More details for generating a token can be found here:
https://help.salesforce.com/apex/HTViewHelpDoc?id=user_security_token.htm

In addition to specifying an sObject, you can also supply a list of API fields
that will be used in the SOQL query.

==== Example
This example prints all the Salesforce Opportunities to standard out

[source,ruby]
----------------------------------
input {
  salesforce {
    client_id => 'OAUTH CLIENT ID FROM YOUR SFDC APP'
    client_secret => 'OAUTH CLIENT SECRET FROM YOUR SFDC APP'
    username => 'email@example.com'
    password => 'super-secret'
    security_token => 'SECURITY TOKEN FOR THIS USER'
    sfdc_object_name => 'Opportunity'
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
----------------------------------

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
salesforce {
    client_id => ...
    client_secret => ...
    password => ...
    security_token => ...
    sfdc_object_name => ...
    username => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-salesforce-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-salesforce-api_version>> |<<string,string>>|No|
| <<plugins-inputs-salesforce-client_id>> |<<string,string>>|Yes|
| <<plugins-inputs-salesforce-client_secret>> |<<string,string>>|Yes|
| <<plugins-inputs-salesforce-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-salesforce-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-salesforce-id>> |<<string,string>>|No|
| <<plugins-inputs-salesforce-password>> |<<string,string>>|Yes|
| <<plugins-inputs-salesforce-security_token>> |<<string,string>>|Yes|
| <<plugins-inputs-salesforce-sfdc_fields>> |<<array,array>>|No|`[]`
| <<plugins-inputs-salesforce-sfdc_filters>> |<<string,string>>|No|`""`
| <<plugins-inputs-salesforce-sfdc_object_name>> |<<string,string>>|Yes|
| <<plugins-inputs-salesforce-tags>> |<<array,array>>|No|
| <<plugins-inputs-salesforce-to_underscores>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-salesforce-type>> |<<string,string>>|No|
| <<plugins-inputs-salesforce-use_test_sandbox>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-salesforce-username>> |<<string,string>>|Yes|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-salesforce-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-salesforce-api_version]]
===== `api_version` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

By default, this uses the default Restforce API version.
To override this, set this to something like "32.0" for example

[[plugins-inputs-salesforce-client_id]]
===== `client_id` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Consumer Key for authentication. You must set up a new SFDC
connected app with oath to use this output. More information
can be found here:
https://help.salesforce.com/apex/HTViewHelpDoc?id=connected_app_create.htm

[[plugins-inputs-salesforce-client_secret]]
===== `client_secret` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Consumer Secret from your oauth enabled connected app

[[plugins-inputs-salesforce-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-salesforce-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-salesforce-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-salesforce-password]]
===== `password` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The password used to login to sfdc

[[plugins-inputs-salesforce-security_token]]
===== `security_token` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The security token for this account. For more information about
generting a security token, see:
https://help.salesforce.com/apex/HTViewHelpDoc?id=user_security_token.htm

[[plugins-inputs-salesforce-sfdc_fields]]
===== `sfdc_fields` 

  * Value type is <<array,array>>
  * Default value is `[]`

These are the field names to return in the Salesforce query
If this is empty, all fields are returned.

[[plugins-inputs-salesforce-sfdc_filters]]
===== `sfdc_filters` 

  * Value type is <<string,string>>
  * Default value is `""`

These options will be added to the WHERE clause in the
SOQL statement. Additional fields can be filtered on by
adding field1 = value1 AND field2 = value2 AND...

[[plugins-inputs-salesforce-sfdc_object_name]]
===== `sfdc_object_name` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the salesforce object you are creating or updating

[[plugins-inputs-salesforce-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-salesforce-to_underscores]]
===== `to_underscores` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Setting this to true will convert SFDC's NamedFields__c to named_fields__c

[[plugins-inputs-salesforce-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-salesforce-use_test_sandbox]]
===== `use_test_sandbox` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Set this to true to connect to a sandbox sfdc instance
logging in through test.salesforce.com

[[plugins-inputs-salesforce-username]]
===== `username` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

A valid salesforce user name, usually your email address.
Used for authentication and will be the user all objects
are created or modified by


