[[plugins-inputs-sqs]]
=== sqs

Pull events from an Amazon Web Services Simple Queue Service (SQS) queue.

SQS is a simple, scalable queue system that is part of the
Amazon Web Services suite of tools.

Although SQS is similar to other queuing systems like AMQP, it
uses a custom API and requires that you have an AWS account.
See http://aws.amazon.com/sqs/ for more details on how SQS works,
what the pricing schedule looks like and how to setup a queue.

To use this plugin, you *must*:

 * Have an AWS account
 * Setup an SQS queue
 * Create an identify that has access to consume messages from the queue.

The "consumer" identity must have the following permissions on the queue:

 * `sqs:ChangeMessageVisibility`
 * `sqs:ChangeMessageVisibilityBatch`
 * `sqs:DeleteMessage`
 * `sqs:DeleteMessageBatch`
 * `sqs:GetQueueAttributes`
 * `sqs:GetQueueUrl`
 * `sqs:ListQueues`
 * `sqs:ReceiveMessage`

Typically, you should setup an IAM policy, create a user and apply the IAM policy to the user.
A sample policy is as follows:
[source,json]
    {
      "Statement": [
        {
          "Action": [
            "sqs:ChangeMessageVisibility",
            "sqs:ChangeMessageVisibilityBatch",
            "sqs:GetQueueAttributes",
            "sqs:GetQueueUrl",
            "sqs:ListQueues",
            "sqs:SendMessage",
            "sqs:SendMessageBatch"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:sqs:us-east-1:123456789012:Logstash"
          ]
        }
      ]
    }

See http://aws.amazon.com/iam/ for more details on setting up AWS identities.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
sqs {
    queue => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-sqs-access_key_id>> |<<string,string>>|No|
| <<plugins-inputs-sqs-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-sqs-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-inputs-sqs-codec>> |<<codec,codec>>|No|`"json"`
| <<plugins-inputs-sqs-id_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-md5_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-proxy_uri>> |<<string,string>>|No|
| <<plugins-inputs-sqs-queue>> |<<string,string>>|Yes|
| <<plugins-inputs-sqs-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1"]`|No|`"us-east-1"`
| <<plugins-inputs-sqs-secret_access_key>> |<<string,string>>|No|
| <<plugins-inputs-sqs-sent_timestamp_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-tags>> |<<array,array>>|No|
| <<plugins-inputs-sqs-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-sqs-type>> |<<string,string>>|No|
| <<plugins-inputs-sqs-use_ssl>> |<<boolean,boolean>>|No|`true`
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-sqs-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order...   
1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config   
2. External credentials file specified by `aws_credentials_file`   
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`   
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`   
5. IAM Instance Profile (available when running inside EC2)   

[[plugins-inputs-sqs-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-sqs-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.   
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

    :access_key_id: "12345"
    :secret_access_key: "54321"


[[plugins-inputs-sqs-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `ASCII-8BIT`, `Big5`, `Big5-HKSCS`, `Big5-UAO`, `CP949`, `Emacs-Mule`, `EUC-JP`, `EUC-KR`, `EUC-TW`, `GB18030`, `GBK`, `ISO-8859-1`, `ISO-8859-2`, `ISO-8859-3`, `ISO-8859-4`, `ISO-8859-5`, `ISO-8859-6`, `ISO-8859-7`, `ISO-8859-8`, `ISO-8859-9`, `ISO-8859-10`, `ISO-8859-11`, `ISO-8859-13`, `ISO-8859-14`, `ISO-8859-15`, `ISO-8859-16`, `KOI8-R`, `KOI8-U`, `Shift_JIS`, `US-ASCII`, `UTF-8`, `UTF-16BE`, `UTF-16LE`, `UTF-32BE`, `UTF-32LE`, `Windows-1251`, `GB2312`, `IBM437`, `IBM737`, `IBM775`, `CP850`, `IBM852`, `CP852`, `IBM855`, `CP855`, `IBM857`, `IBM860`, `IBM861`, `IBM862`, `IBM863`, `IBM864`, `IBM865`, `IBM866`, `IBM869`, `Windows-1258`, `GB1988`, `macCentEuro`, `macCroatian`, `macCyrillic`, `macGreek`, `macIceland`, `macRoman`, `macRomania`, `macThai`, `macTurkish`, `macUkraine`, `CP950`, `CP951`, `stateless-ISO-2022-JP`, `eucJP-ms`, `CP51932`, `GB12345`, `ISO-2022-JP`, `ISO-2022-JP-2`, `CP50220`, `CP50221`, `Windows-1252`, `Windows-1250`, `Windows-1256`, `Windows-1253`, `Windows-1255`, `Windows-1254`, `TIS-620`, `Windows-874`, `Windows-1257`, `Windows-31J`, `MacJapanese`, `UTF-7`, `UTF8-MAC`, `UTF-16`, `UTF-32`, `UTF8-DoCoMo`, `SJIS-DoCoMo`, `UTF8-KDDI`, `SJIS-KDDI`, `ISO-2022-JP-KDDI`, `stateless-ISO-2022-JP-KDDI`, `UTF8-SoftBank`, `SJIS-SoftBank`, `BINARY`, `CP437`, `CP737`, `CP775`, `IBM850`, `CP857`, `CP860`, `CP861`, `CP862`, `CP863`, `CP864`, `CP865`, `CP866`, `CP869`, `CP1258`, `Big5-HKSCS:2008`, `eucJP`, `euc-jp-ms`, `eucKR`, `eucTW`, `EUC-CN`, `eucCN`, `CP936`, `ISO2022-JP`, `ISO2022-JP2`, `ISO8859-1`, `CP1252`, `ISO8859-2`, `CP1250`, `ISO8859-3`, `ISO8859-4`, `ISO8859-5`, `ISO8859-6`, `CP1256`, `ISO8859-7`, `CP1253`, `ISO8859-8`, `CP1255`, `ISO8859-9`, `CP1254`, `ISO8859-10`, `ISO8859-11`, `CP874`, `ISO8859-13`, `CP1257`, `ISO8859-14`, `ISO8859-15`, `ISO8859-16`, `CP878`, `CP932`, `csWindows31J`, `SJIS`, `PCK`, `MacJapan`, `ASCII`, `ANSI_X3.4-1968`, `646`, `CP65000`, `CP65001`, `UTF-8-MAC`, `UTF-8-HFS`, `UCS-2BE`, `UCS-4BE`, `UCS-4LE`, `CP1251`, `external`, `locale`
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-sqs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"json"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-sqs-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-sqs-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-sqs-id_field]]
===== `id_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the SQS message ID

[[plugins-inputs-sqs-md5_field]]
===== `md5_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the SQS message MD5 checksum

[[plugins-inputs-sqs-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-sqs-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-inputs-sqs-queue]]
===== `queue` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the SQS Queue name to pull messages from. Note that this is just the name of the queue, not the URL or ARN.

[[plugins-inputs-sqs-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `sa-east-1`, `us-gov-west-1`
  * Default value is `"us-east-1"`

The AWS Region

[[plugins-inputs-sqs-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-inputs-sqs-sent_timestamp_field]]
===== `sent_timestamp_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the  SQS message Sent Timestamp

[[plugins-inputs-sqs-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-sqs-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`

Set this to the number of threads you want this input to spawn.
This is the same as declaring the input multiple times

[[plugins-inputs-sqs-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in the web interface.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at 
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-sqs-use_ssl]]
===== `use_ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Should we require (true) or disable (false) using SSL for communicating with the AWS API   
The AWS SDK for Ruby defaults to SSL so we preserve that

