[[plugins-inputs-sqs]]
=== sqs

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-input-sqs/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.2, 5.1.1, 5.0.0, 2.4.1, 2.4.0




Pull events from an Amazon Web Services Simple Queue Service (SQS) queue.

SQS is a simple, scalable queue system that is part of the
Amazon Web Services suite of tools.

Although SQS is similar to other queuing systems like AMQP, it
uses a custom API and requires that you have an AWS account.
See http://aws.amazon.com/sqs/ for more details on how SQS works,
what the pricing schedule looks like and how to setup a queue.

To use this plugin, you *must*:

 * Have an AWS account
 * Setup an SQS queue
 * Create an identify that has access to consume messages from the queue.

The "consumer" identity must have the following permissions on the queue:

 * `sqs:ChangeMessageVisibility`
 * `sqs:ChangeMessageVisibilityBatch`
 * `sqs:DeleteMessage`
 * `sqs:DeleteMessageBatch`
 * `sqs:GetQueueAttributes`
 * `sqs:GetQueueUrl`
 * `sqs:ListQueues`
 * `sqs:ReceiveMessage`

Typically, you should setup an IAM policy, create a user and apply the IAM policy to the user.
A sample policy is as follows:
[source,json]
    {
      "Statement": [
        {
          "Action": [
            "sqs:ChangeMessageVisibility",
            "sqs:ChangeMessageVisibilityBatch",
            "sqs:GetQueueAttributes",
            "sqs:GetQueueUrl",
            "sqs:ListQueues",
            "sqs:SendMessage",
            "sqs:SendMessageBatch"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:sqs:us-east-1:123456789012:Logstash"
          ]
        }
      ]
    }

See http://aws.amazon.com/iam/ for more details on setting up AWS identities.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
sqs {
    queue => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-sqs-access_key_id>> |<<string,string>>|No|
| <<plugins-inputs-sqs-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-sqs-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-inputs-sqs-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-sqs-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-sqs-id>> |<<string,string>>|No|
| <<plugins-inputs-sqs-id_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-md5_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-polling_frequency>> |<<number,number>>|No|`20`
| <<plugins-inputs-sqs-proxy_uri>> |<<string,string>>|No|
| <<plugins-inputs-sqs-queue>> |<<string,string>>|Yes|
| <<plugins-inputs-sqs-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1"]`|No|`"us-east-1"`
| <<plugins-inputs-sqs-secret_access_key>> |<<string,string>>|No|
| <<plugins-inputs-sqs-sent_timestamp_field>> |<<string,string>>|No|
| <<plugins-inputs-sqs-session_token>> |<<string,string>>|No|
| <<plugins-inputs-sqs-tags>> |<<array,array>>|No|
| <<plugins-inputs-sqs-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-sqs-type>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-sqs-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order:

1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config
2. External credentials file specified by `aws_credentials_file`
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
5. IAM Instance Profile (available when running inside EC2)

[[plugins-inputs-sqs-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-sqs-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

[source,ruby]
----------------------------------
    :access_key_id: "12345"
    :secret_access_key: "54321"
----------------------------------


[[plugins-inputs-sqs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-sqs-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric collection and reporting for this specific plugin instance. 
By default we record metrics from all plugins, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-sqs-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique named `ID` to the plugin instance. This `ID` is used for tracking
information for a specific configuration of the plugin and will be useful for 
debugging purposes.

[source,sh]
--------------------------------------------------
output {
 stdout {
   id => "debug_stdout"
 }
}
--------------------------------------------------

If you don't explicitly set this field, Logstash will generate a unique name.

[[plugins-inputs-sqs-id_field]]
===== `id_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the SQS message ID

[[plugins-inputs-sqs-md5_field]]
===== `md5_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the SQS message MD5 checksum

[[plugins-inputs-sqs-polling_frequency]]
===== `polling_frequency` 

  * Value type is <<number,number>>
  * Default value is `20`

Polling frequency, default is 20 seconds

[[plugins-inputs-sqs-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-inputs-sqs-queue]]
===== `queue` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the SQS Queue name to pull messages from. Note that this is just the name of the queue, not the URL or ARN.

[[plugins-inputs-sqs-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `ap-northeast-2`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`, `ap-south-1`
  * Default value is `"us-east-1"`

The AWS Region

[[plugins-inputs-sqs-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-inputs-sqs-sent_timestamp_field]]
===== `sent_timestamp_field` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of the event field in which to store the SQS message Sent Timestamp

[[plugins-inputs-sqs-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Session token for temporary credential

[[plugins-inputs-sqs-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-sqs-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`



[[plugins-inputs-sqs-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


