[[plugins-inputs-syslog]]
=== syslog



Read syslog messages as events over the network.

This input is a good choice if you already use syslog today.
It is also a good choice if you want to receive logs from
appliances and network devices where you cannot run your own
log collector.

Of course, 'syslog' is a very muddy term. This input only supports `RFC3164`
syslog with some small modifications. The date format is allowed to be
`RFC3164` style or `ISO8601`. Otherwise the rest of `RFC3164` must be obeyed.
If you do not use `RFC3164`, do not use this input.

For more information see the http://www.ietf.org/rfc/rfc3164.txt[RFC3164 page].

Note: This input will start listeners on both TCP and UDP.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
syslog {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-syslog-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-syslog-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-syslog-facility_labels>> |<<array,array>>|No|`["kernel", "user-level", "mail", "system", "security/authorization", "syslogd", "line printer", "network news", "UUCP", "clock", "security/authorization", "FTP", "NTP", "log audit", "log alert", "clock", "local0", "local1", "local2", "local3", "local4", "local5", "local6", "local7"]`
| <<plugins-inputs-syslog-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-syslog-locale>> |<<string,string>>|No|
| <<plugins-inputs-syslog-port>> |<<number,number>>|No|`514`
| <<plugins-inputs-syslog-severity_labels>> |<<array,array>>|No|`["Emergency", "Alert", "Critical", "Error", "Warning", "Notice", "Informational", "Debug"]`
| <<plugins-inputs-syslog-tags>> |<<array,array>>|No|
| <<plugins-inputs-syslog-timezone>> |<<string,string>>|No|
| <<plugins-inputs-syslog-type>> |<<string,string>>|No|
| <<plugins-inputs-syslog-use_labels>> |<<boolean,boolean>>|No|`true`
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-syslog-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-syslog-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-syslog-facility_labels]]
===== `facility_labels` 

  * Value type is <<array,array>>
  * Default value is `["kernel", "user-level", "mail", "system", "security/authorization", "syslogd", "line printer", "network news", "UUCP", "clock", "security/authorization", "FTP", "NTP", "log audit", "log alert", "clock", "local0", "local1", "local2", "local3", "local4", "local5", "local6", "local7"]`

Labels for facility levels. These are defined in RFC3164.

[[plugins-inputs-syslog-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The address to listen on.

[[plugins-inputs-syslog-locale]]
===== `locale` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Specify a locale to be used for date parsing using either IETF-BCP47 or POSIX language tag.
Simple examples are `en`,`en-US` for BCP47 or `en_US` for POSIX.
If not specified, the platform default will be used.

The locale is mostly necessary to be set for parsing month names (pattern with MMM) and
weekday names (pattern with EEE).


[[plugins-inputs-syslog-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `514`

The port to listen on. Remember that ports less than 1024 (privileged
ports) may require root to use.

[[plugins-inputs-syslog-severity_labels]]
===== `severity_labels` 

  * Value type is <<array,array>>
  * Default value is `["Emergency", "Alert", "Critical", "Error", "Warning", "Notice", "Informational", "Debug"]`

Labels for severity levels. These are defined in RFC3164.

[[plugins-inputs-syslog-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-syslog-timezone]]
===== `timezone` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Specify a time zone canonical ID to be used for date parsing.
The valid IDs are listed on the [Joda.org available time zones page](http://joda-time.sourceforge.net/timezones.html).
This is useful in case the time zone cannot be extracted from the value,
and is not the platform default.
If this is not specified the platform default will be used.
Canonical ID is good as it takes care of daylight saving time for you
For example, `America/Los_Angeles` or `Europe/France` are valid IDs.

[[plugins-inputs-syslog-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-syslog-use_labels]]
===== `use_labels` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Use label parsing for severity and facility levels.


