[[plugins-inputs-twitter]]
=== twitter

Version: 3.0.3
Released on: 2016-10-13
https://github.com/logstash-plugins/logstash-input-twitter/blob/master/CHANGELOG.md#303[Changelog]
Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



Ingest events from the Twitter Streaming API.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
twitter {
    consumer_key => ...
    consumer_secret => ...
    oauth_token => ...
    oauth_token_secret => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-twitter-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-twitter-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-twitter-consumer_key>> |<<string,string>>|Yes|
| <<plugins-inputs-twitter-consumer_secret>> |<<password,password>>|Yes|
| <<plugins-inputs-twitter-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-twitter-follows>> |<<array,array>>|No|
| <<plugins-inputs-twitter-full_tweet>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-twitter-id>> |<<string,string>>|No|
| <<plugins-inputs-twitter-ignore_retweets>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-twitter-keywords>> |<<array,array>>|No|
| <<plugins-inputs-twitter-languages>> |<<array,array>>|No|
| <<plugins-inputs-twitter-locations>> |<<string,string>>|No|
| <<plugins-inputs-twitter-oauth_token>> |<<string,string>>|Yes|
| <<plugins-inputs-twitter-oauth_token_secret>> |<<password,password>>|Yes|
| <<plugins-inputs-twitter-proxy_address>> |<<string,string>>|No|`"127.0.0.1"`
| <<plugins-inputs-twitter-proxy_port>> |<<number,number>>|No|`3128`
| <<plugins-inputs-twitter-rate_limit_reset_in>> |<<number,number>>|No|`300`
| <<plugins-inputs-twitter-tags>> |<<array,array>>|No|
| <<plugins-inputs-twitter-type>> |<<string,string>>|No|
| <<plugins-inputs-twitter-use_proxy>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-twitter-use_samples>> |<<boolean,boolean>>|No|`false`
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-twitter-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-twitter-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-twitter-consumer_key]]
===== `consumer_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your Twitter App's consumer key

Don't know what this is? You need to create an "application"
on Twitter, see this url: <https://dev.twitter.com/apps/new>

[[plugins-inputs-twitter-consumer_secret]]
===== `consumer_secret` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

Your Twitter App's consumer secret

If you don't have one of these, you can create one by
registering a new application with Twitter:
<https://dev.twitter.com/apps/new>

[[plugins-inputs-twitter-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-twitter-follows]]
===== `follows` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

A comma separated list of user IDs, indicating the users to
return statuses for in the Twitter stream.
See https://dev.twitter.com/streaming/overview/request-parameters#follow
for more details.

[[plugins-inputs-twitter-full_tweet]]
===== `full_tweet` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Record full tweet object as given to us by the Twitter Streaming API.

[[plugins-inputs-twitter-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-twitter-ignore_retweets]]
===== `ignore_retweets` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Lets you ingore the retweets coming out of the Twitter API. Default => false

[[plugins-inputs-twitter-keywords]]
===== `keywords` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Any keywords to track in the Twitter stream. For multiple keywords, use
the syntax ["foo", "bar"]. There's a logical OR between each keyword 
string listed and a logical AND between words separated by spaces per
keyword string.
See https://dev.twitter.com/streaming/overview/request-parameters#track 
for more details.

The wildcard "*" option is not supported. To ingest a sample stream of 
all tweets, the use_samples option is recommended. 

[[plugins-inputs-twitter-languages]]
===== `languages` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

A list of BCP 47 language identifiers corresponding to any of the languages listed
on Twitter’s advanced search page will only return tweets that have been detected 
as being written in the specified languages.

[[plugins-inputs-twitter-locations]]
===== `locations` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

A comma-separated list of longitude, latitude pairs specifying a set
of bounding boxes to filter tweets by.
See https://dev.twitter.com/streaming/overview/request-parameters#locations
for more details.

[[plugins-inputs-twitter-oauth_token]]
===== `oauth_token` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your oauth token.

To get this, login to Twitter with whatever account you want,
then visit <https://dev.twitter.com/apps>

Click on your app (used with the consumer_key and consumer_secret settings)
Then at the bottom of the page, click 'Create my access token' which
will create an oauth token and secret bound to your account and that
application.

[[plugins-inputs-twitter-oauth_token_secret]]
===== `oauth_token_secret` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

Your oauth token secret.

To get this, login to Twitter with whatever account you want,
then visit <https://dev.twitter.com/apps>

Click on your app (used with the consumer_key and consumer_secret settings)
Then at the bottom of the page, click 'Create my access token' which
will create an oauth token and secret bound to your account and that
application.

[[plugins-inputs-twitter-proxy_address]]
===== `proxy_address` 

  * Value type is <<string,string>>
  * Default value is `"127.0.0.1"`

Location of the proxy, by default the same machine as the one running this LS instance

[[plugins-inputs-twitter-proxy_port]]
===== `proxy_port` 

  * Value type is <<number,number>>
  * Default value is `3128`

Port where the proxy is listening, by default 3128 (squid)

[[plugins-inputs-twitter-rate_limit_reset_in]]
===== `rate_limit_reset_in` 

  * Value type is <<number,number>>
  * Default value is `300`

Duration in seconds to wait before retrying a connection when twitter responds with a 429 TooManyRequests
In some cases the 'x-rate-limit-reset' header is not set in the response and <error>.rate_limit.reset_in
is nil. If this occurs then we use the integer specified here. The default is 5 minutes.

[[plugins-inputs-twitter-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-twitter-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-twitter-use_proxy]]
===== `use_proxy` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

When to use a proxy to handle the connections

[[plugins-inputs-twitter-use_samples]]
===== `use_samples` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Returns a small random sample of all public statuses. The tweets returned
by the default access level are the same, so if two different clients connect
to this endpoint, they will see the same tweets. If set to true, the keywords, 
follows, locations, and languages options will be ignored. Default => false


