[[plugins-inputs-twitter]]
=== twitter



Read events from the twitter streaming api.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
twitter {
    consumer_key => ...
    consumer_secret => ...
    keywords => ...
    oauth_token => ...
    oauth_token_secret => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-twitter-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-twitter-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-twitter-consumer_key>> |<<string,string>>|Yes|
| <<plugins-inputs-twitter-consumer_secret>> |<<password,password>>|Yes|
| <<plugins-inputs-twitter-full_tweet>> |<<boolean,boolean>>|No|`false`
| <<plugins-inputs-twitter-keywords>> |<<array,array>>|Yes|
| <<plugins-inputs-twitter-oauth_token>> |<<string,string>>|Yes|
| <<plugins-inputs-twitter-oauth_token_secret>> |<<password,password>>|Yes|
| <<plugins-inputs-twitter-tags>> |<<array,array>>|No|
| <<plugins-inputs-twitter-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-twitter-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-twitter-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-twitter-consumer_key]]
===== `consumer_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your twitter app's consumer key

Don't know what this is? You need to create an "application"
on twitter, see this url: <https://dev.twitter.com/apps/new>

[[plugins-inputs-twitter-consumer_secret]]
===== `consumer_secret` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

Your twitter app's consumer secret

If you don't have one of these, you can create one by
registering a new application with twitter:
<https://dev.twitter.com/apps/new>

[[plugins-inputs-twitter-full_tweet]]
===== `full_tweet` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Record full tweet object as given to us by the Twitter stream api.

[[plugins-inputs-twitter-keywords]]
===== `keywords` 

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

Any keywords to track in the twitter stream

[[plugins-inputs-twitter-oauth_token]]
===== `oauth_token` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your oauth token.

To get this, login to twitter with whatever account you want,
then visit <https://dev.twitter.com/apps>

Click on your app (used with the consumer_key and consumer_secret settings)
Then at the bottom of the page, click 'Create my access token' which
will create an oauth token and secret bound to your account and that
application.

[[plugins-inputs-twitter-oauth_token_secret]]
===== `oauth_token_secret` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

Your oauth token secret.

To get this, login to twitter with whatever account you want,
then visit <https://dev.twitter.com/apps>

Click on your app (used with the consumer_key and consumer_secret settings)
Then at the bottom of the page, click 'Create my access token' which
will create an oauth token and secret bound to your account and that
application.

[[plugins-inputs-twitter-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-twitter-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


