[[plugins-inputs-udp]]
=== udp

* Version: 3.1.0
* Released on: November 24, 2016
* https://github.com/logstash-plugins/logstash-input-udp/blob/master/CHANGELOG.md#310[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

Read messages as events over the network via udp. The only required
configuration item is `port`, which specifies the udp port logstash
will listen on for event streams.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
udp {
    port => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-inputs-udp-add_field>> |<<hash,hash>>|No
| <<plugins-inputs-udp-buffer_size>> |<<number,number>>|No
| <<plugins-inputs-udp-codec>> |<<codec,codec>>|No
| <<plugins-inputs-udp-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-inputs-udp-host>> |<<string,string>>|No
| <<plugins-inputs-udp-id>> |<<string,string>>|No
| <<plugins-inputs-udp-port>> |<<number,number>>|Yes
| <<plugins-inputs-udp-queue_size>> |<<number,number>>|No
| <<plugins-inputs-udp-receive_buffer_bytes>> |<<number,number>>|No
| <<plugins-inputs-udp-tags>> |<<array,array>>|No
| <<plugins-inputs-udp-type>> |<<string,string>>|No
| <<plugins-inputs-udp-workers>> |<<number,number>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-udp-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-udp-buffer_size]]
===== `buffer_size` 

  * Value type is <<number,number>>
  * Default value is `65536`

The maximum packet size to read from the network

[[plugins-inputs-udp-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-udp-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-udp-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The address which logstash will listen on.

[[plugins-inputs-udp-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-inputs-udp-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

The port which logstash will listen on. Remember that ports less
than 1024 (privileged ports) may require root or elevated privileges to use.

[[plugins-inputs-udp-queue_size]]
===== `queue_size` 

  * Value type is <<number,number>>
  * Default value is `2000`

This is the number of unprocessed UDP packets you can hold in memory
before packets will start dropping.

[[plugins-inputs-udp-receive_buffer_bytes]]
===== `receive_buffer_bytes` 

  * Value type is <<number,number>>
  * There is no default value for this setting.

The socket receive buffer size in bytes.
If option is not set, the operating system default is used.
The operating system will use the max allowed value if receive_buffer_bytes is larger than allowed.
Consult your operating system documentation if you need to increase this max allowed value.

[[plugins-inputs-udp-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-udp-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This is the base class for Logstash inputs.
Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-udp-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `2`

Number of threads processing packets


