[[plugins-inputs-udp]]
=== udp



Read messages as events over the network via udp. The only required
configuration item is `port`, which specifies the udp port logstash
will listen on for event streams.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
udp {
    port => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-udp-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-udp-buffer_size>> |<<number,number>>|No|`8192`
| <<plugins-inputs-udp-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-udp-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-udp-port>> |<<number,number>>|Yes|
| <<plugins-inputs-udp-queue_size>> |<<number,number>>|No|`2000`
| <<plugins-inputs-udp-tags>> |<<array,array>>|No|
| <<plugins-inputs-udp-type>> |<<string,string>>|No|
| <<plugins-inputs-udp-workers>> |<<number,number>>|No|`2`
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-udp-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-udp-buffer_size]]
===== `buffer_size` 

  * Value type is <<number,number>>
  * Default value is `8192`

The maximum packet size to read from the network

[[plugins-inputs-udp-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-udp-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The address which logstash will listen on.

[[plugins-inputs-udp-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

The port which logstash will listen on. Remember that ports less
than 1024 (privileged ports) may require root or elevated privileges to use.

[[plugins-inputs-udp-queue_size]]
===== `queue_size` 

  * Value type is <<number,number>>
  * Default value is `2000`

This is the number of unprocessed UDP packets you can hold in memory
before packets will start dropping.

[[plugins-inputs-udp-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-udp-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-udp-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `2`

Number of threads processing packets


