[[plugins-inputs-unix]]
=== unix

* Version: 3.0.3
* Released on: February 20, 2017
* https://github.com/logstash-plugins/logstash-input-unix/blob/master/CHANGELOG.md#303[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

Read events over a UNIX socket.

Like `stdin` and `file` inputs, each event is assumed to be one line of text.

Can either accept connections from clients or connect to a server,
depending on `mode`.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
unix {
    path => ...
    socket_not_present_retry_interval_seconds => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-inputs-unix-add_field>> |<<hash,hash>>|No
| <<plugins-inputs-unix-codec>> |<<codec,codec>>|No
| <<plugins-inputs-unix-data_timeout>> |<<number,number>>|No
| <<plugins-inputs-unix-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-inputs-unix-force_unlink>> |<<boolean,boolean>>|No
| <<plugins-inputs-unix-id>> |<<string,string>>|No
| <<plugins-inputs-unix-mode>> |<<string,string>>, one of `["server", "client"]`|No
| <<plugins-inputs-unix-path>> |<<string,string>>|Yes
| <<plugins-inputs-unix-socket_not_present_retry_interval_seconds>> |<<number,number>>|Yes
| <<plugins-inputs-unix-tags>> |<<array,array>>|No
| <<plugins-inputs-unix-type>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-unix-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-unix-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-unix-data_timeout]]
===== `data_timeout` 

  * Value type is <<number,number>>
  * Default value is `-1`

The 'read' timeout in seconds. If a particular connection is idle for
more than this timeout period, we will assume it is dead and close it.

If you never want to timeout, use -1.

[[plugins-inputs-unix-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-unix-force_unlink]]
===== `force_unlink` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Remove socket file in case of EADDRINUSE failure

[[plugins-inputs-unix-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-inputs-unix-mode]]
===== `mode` 

  * Value can be any of: `server`, `client`
  * Default value is `"server"`

Mode to operate in. `server` listens for client connections,
`client` connects to a server.

[[plugins-inputs-unix-path]]
===== `path` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

When mode is `server`, the path to listen on.
When mode is `client`, the path to connect to.

[[plugins-inputs-unix-socket_not_present_retry_interval_seconds]]
===== `socket_not_present_retry_interval_seconds` 

  * This is a required setting.
  * Value type is <<number,number>>
  * Default value is `5`

Amount of time in seconds to wait if the socket file is not present, before retrying.
Only positive values are allowed.

This setting is only used if `mode` is `client`.

[[plugins-inputs-unix-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-unix-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This is the base class for Logstash inputs.
Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


