[[plugins-inputs-websocket]]
=== Websocket input plugin


NOTE: This plugin cannot be installed on the current version of Logstash. We are working on resolving this problem.

Read events over the websocket protocol.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
websocket {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-websocket-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-websocket-codec>> |<<codec,codec>>|No|`"json"`
| <<plugins-inputs-websocket-mode>> |<<string,string>>, one of `["server", "client"]`|No|`"client"`
| <<plugins-inputs-websocket-tags>> |<<array,array>>|No|
| <<plugins-inputs-websocket-type>> |<<string,string>>|No|
| <<plugins-inputs-websocket-url>> |<<string,string>>|No|`"0.0.0.0"`
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-websocket-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-websocket-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"json"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-websocket-mode]]
===== `mode` 

  * Value can be any of: `server`, `client`
  * Default value is `"client"`

Operate as a client or a server.

Client mode causes this plugin to connect as a websocket client
to the URL given. It expects to receive events as websocket messages.

(NOT IMPLEMENTED YET) Server mode causes this plugin to listen on
the given URL for websocket clients. It expects to receive events
as websocket messages from these clients.

[[plugins-inputs-websocket-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-websocket-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-websocket-url]]
===== `url` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The url to connect to or serve from


