[[plugins-inputs-wmi]]
=== wmi


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-input-wmi`.


Collect data from WMI query

This is useful for collecting performance metrics and other data
which is accessible via WMI on a Windows host

Example:
[source,ruby]
    input {
      wmi {
        query => "select * from Win32_Process"
        interval => 10
      }
      wmi {
        query => "select PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor where name = '_Total'"
      }
    }

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
wmi {
    query => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-wmi-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-wmi-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-wmi-interval>> |<<number,number>>|No|`10`
| <<plugins-inputs-wmi-query>> |<<string,string>>|Yes|
| <<plugins-inputs-wmi-tags>> |<<array,array>>|No|
| <<plugins-inputs-wmi-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-wmi-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-wmi-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-wmi-interval]]
===== `interval` 

  * Value type is <<number,number>>
  * Default value is `10`

Polling interval

[[plugins-inputs-wmi-query]]
===== `query` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

WMI query

[[plugins-inputs-wmi-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-wmi-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


