[[plugins-inputs-wmi]]
=== wmi

* Version: 3.0.0
* Released on: 2016-09-10
* https://github.com/logstash-plugins/logstash-input-wmi/blob/master/CHANGELOG.md#300[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4


NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-input-wmi`.


Collect data from WMI query

This is useful for collecting performance metrics and other data
which is accessible via WMI on a Windows host

Example:
[source,ruby]
    input {
      wmi {
        query => "select * from Win32_Process"
        interval => 10
      }
      wmi {
        query => "select PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor where name = '_Total'"
      }
      wmi { # Connect to a remote host
        query => "select * from Win32_Process"
        host => "MyRemoteHost"
        user => "mydomain\myuser"
        password => "Password"
      }
    }

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
wmi {
    query => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-wmi-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-wmi-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-wmi-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-inputs-wmi-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-inputs-wmi-id>> |<<string,string>>|No|
| <<plugins-inputs-wmi-interval>> |<<number,number>>|No|`10`
| <<plugins-inputs-wmi-namespace>> |<<string,string>>|No|`"root\\cimv2"`
| <<plugins-inputs-wmi-password>> |<<password,password>>|No|
| <<plugins-inputs-wmi-query>> |<<string,string>>|Yes|
| <<plugins-inputs-wmi-tags>> |<<array,array>>|No|
| <<plugins-inputs-wmi-type>> |<<string,string>>|No|
| <<plugins-inputs-wmi-user>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-inputs-wmi-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-wmi-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-wmi-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-inputs-wmi-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

Host to connect to ( Defaults to localhost )

[[plugins-inputs-wmi-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-inputs-wmi-interval]]
===== `interval` 

  * Value type is <<number,number>>
  * Default value is `10`

Polling interval

[[plugins-inputs-wmi-namespace]]
===== `namespace` 

  * Value type is <<string,string>>
  * Default value is `"root\\cimv2"`

Namespace when doing remote connections

[[plugins-inputs-wmi-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password when doing remote connections

[[plugins-inputs-wmi-query]]
===== `query` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

WMI query

[[plugins-inputs-wmi-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-wmi-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.

[[plugins-inputs-wmi-user]]
===== `user` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Username when doing remote connections


