[[logstash-reference]]
= Logstash Plugins only

include::{docs-root}/shared/versions/stack/{source_branch}.asciidoc[]
include::{docs-root}/shared/attributes.asciidoc[]
include::./include/attributes-ls.asciidoc[]
include::./include/attributes-lsplugins.asciidoc[]

:include-xpack:         true
:lang:                  en
:xls-repo-dir:          {docdir}/../x-pack/docs/{lang}
:log-repo-dir:          {docdir}
:plugins-repo-dir:      {docdir}/../../logstash-docs/docs
:docker-repo:           docker.elastic.co/logstash/logstash
:docker-image:          {docker-repo}:{logstash_version}

:versioned_docs:        false

:jdk:                   1.8.0
:lsissue:               https://github.com/elastic/logstash/issues
:lsplugindocs:          https://www.elastic.co/guide/en/logstash-versioned-plugins/current
:tab-widget-dir:         {docdir}/static/tab-widgets


[[introduction]]
== Logstash Plugins

Some sort of intro goes here.

[[string]]
[discrete]
==== String

A string must be a single character sequence. Note that string values are
enclosed in quotes, either double or single.

[[array]]
[discrete]
==== Array

This type is now mostly deprecated in favor of using a standard type like `string` with the plugin defining the `:list => true` property for better type checking. It is still needed to handle lists of hashes or mixed types where type checking is not desired.

[[number]]
[discrete]
==== Number

Numbers must be valid numeric values (floating point or integer).

[[boolean]]
[discrete]
==== Boolean

A boolean must be either `true` or `false`. Note that the `true` and `false` keywords
are not enclosed in quotes.

[[password]]
[discrete]
==== Password

A password is a string with a single value that is not logged or printed.

[[path]]
[discrete]
==== Path

A path is a string that represents a valid operating system path.

[[hash]]
[discrete]
==== Hash

A hash is a collection of key value pairs specified in the format `"field1" => "value1"`.
Note that multiple key value entries are separated by spaces rather than commas.

[[uri]]
[discrete]
==== URI

A URI can be anything from a full URL like 'http://elastic.co/' to a simple identifier
like 'foobar'. If the URI contains a password such as 'http://user:pass@example.net' the password
portion of the URI will not be logged or printed.

[[bytes]]
[discrete]
==== Bytes

A bytes field is a string field that represents a valid unit of bytes. It is a
convenient way to declare specific sizes in your plugin options. Both SI (k M G T P E Z Y)
and Binary (Ki Mi Gi Ti Pi Ei Zi Yi) units are supported. Binary units are in
base-1024 and SI units are in base-1000. This field is case-insensitive
and accepts space between the value and the unit. If no unit is specified, the integer string
represents the number of bytes.

[[logstash-config-field-references]]
[discrete]
==== CFR

words

[[event-api]]
[discrete]
==== Event API

words

include::integrations.asciidoc[]

include::inputs.asciidoc[]

include::outputs.asciidoc[]

include::filters.asciidoc[]

include::codecs.asciidoc[]

// AsciiDoc "redirects"

include::static/other/dead-letter-queues.asciidoc[]