[[plugins-filters-dns]]
=== dns

* Version: 3.0.3
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-filter-dns/blob/master/CHANGELOG.md#303[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

The DNS filter performs a lookup (either an A record/CNAME record lookup
or a reverse lookup at the PTR record) on records specified under the
`reverse` arrays or respectively under the `resolve` arrays.

The config should look like this:
[source,ruby]
    filter {
      dns {
        reverse => [ "source_host", "field_with_address" ]
        resolve => [ "field_with_fqdn" ]
        action => "replace"
      }
    }

This filter, like all filters, only processes 1 event at a time, so the use
of this plugin can significantly slow down your pipeline's throughput if you
have a high latency network. By way of example, if each DNS lookup takes 2
milliseconds, the maximum throughput you can achieve with a single filter
worker is 500 events per second (1000 milliseconds / 2 milliseconds).

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
dns {
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-filters-dns-action>> |<<string,string>>, one of `["append", "replace"]`|No
| <<plugins-filters-dns-add_field>> |<<hash,hash>>|No
| <<plugins-filters-dns-add_tag>> |<<array,array>>|No
| <<plugins-filters-dns-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-filters-dns-failed_cache_size>> |<<number,number>>|No
| <<plugins-filters-dns-failed_cache_ttl>> |<<number,number>>|No
| <<plugins-filters-dns-hit_cache_size>> |<<number,number>>|No
| <<plugins-filters-dns-hit_cache_ttl>> |<<number,number>>|No
| <<plugins-filters-dns-hostsfile>> |<<array,array>>|No
| <<plugins-filters-dns-id>> |<<string,string>>|No
| <<plugins-filters-dns-max_retries>> |<<number,number>>|No
| <<plugins-filters-dns-nameserver>> |<<array,array>>|No
| <<plugins-filters-dns-periodic_flush>> |<<boolean,boolean>>|No
| <<plugins-filters-dns-remove_field>> |<<array,array>>|No
| <<plugins-filters-dns-remove_tag>> |<<array,array>>|No
| <<plugins-filters-dns-resolve>> |<<array,array>>|No
| <<plugins-filters-dns-reverse>> |<<array,array>>|No
| <<plugins-filters-dns-timeout>> |<<number,number>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-filters-dns-action]]
===== `action` 

  * Value can be any of: `append`, `replace`
  * Default value is `"append"`

Determine what action to do: append or replace the values in the fields
specified under `reverse` and `resolve`.

[[plugins-filters-dns-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

If this filter is successful, add any arbitrary fields to this event.
Field names can be dynamic and include parts of the event using the `%{field}`.

Example:
[source,ruby]
    filter {
      dns {
        add_field => { "foo_%{somefield}" => "Hello world, from %{host}" }
      }
    }
[source,ruby]
    # You can also add multiple fields at once:
    filter {
      dns {
        add_field => {
          "foo_%{somefield}" => "Hello world, from %{host}"
          "new_field" => "new_static_value"
        }
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add field `foo_hello` if it is present, with the
value above and the `%{host}` piece replaced with that value from the
event. The second example would also add a hardcoded field.

[[plugins-filters-dns-add_tag]]
===== `add_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, add arbitrary tags to the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      dns {
        add_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also add multiple tags at once:
    filter {
      dns {
        add_tag => [ "foo_%{somefield}", "taggedy_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add a tag `foo_hello` (and the second example would of course add a `taggedy_tag` tag).

[[plugins-filters-dns-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-filters-dns-failed_cache_size]]
===== `failed_cache_size` 

  * Value type is <<number,number>>
  * Default value is `0`

cache size for failed requests

[[plugins-filters-dns-failed_cache_ttl]]
===== `failed_cache_ttl` 

  * Value type is <<number,number>>
  * Default value is `5`

how long to cache failed requests (in seconds)

[[plugins-filters-dns-hit_cache_size]]
===== `hit_cache_size` 

  * Value type is <<number,number>>
  * Default value is `0`

set the size of cache for successful requests

[[plugins-filters-dns-hit_cache_ttl]]
===== `hit_cache_ttl` 

  * Value type is <<number,number>>
  * Default value is `60`

how long to cache successful requests (in seconds)

[[plugins-filters-dns-hostsfile]]
===== `hostsfile` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Use custom hosts file(s). For example: `["/var/db/my_custom_hosts"]`

[[plugins-filters-dns-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-filters-dns-max_retries]]
===== `max_retries` 

  * Value type is <<number,number>>
  * Default value is `2`

number of times to retry a failed resolve/reverse

[[plugins-filters-dns-nameserver]]
===== `nameserver` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Use custom nameserver(s). For example: `["8.8.8.8", "8.8.4.4"]`

[[plugins-filters-dns-periodic_flush]]
===== `periodic_flush` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Call the filter flush method at regular interval.
Optional.

[[plugins-filters-dns-remove_field]]
===== `remove_field` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary fields from this event.
Fields names can be dynamic and include parts of the event using the %{field}
Example:
[source,ruby]
    filter {
      dns {
        remove_field => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple fields at once:
    filter {
      dns {
        remove_field => [ "foo_%{somefield}", "my_extraneous_field" ]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the field with name `foo_hello` if it is present. The second
example would remove an additional, non-dynamic field.

[[plugins-filters-dns-remove_tag]]
===== `remove_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary tags from the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      dns {
        remove_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple tags at once:
    filter {
      dns {
        remove_tag => [ "foo_%{somefield}", "sad_unwanted_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the tag `foo_hello` if it is present. The second example
would remove a sad, unwanted tag as well.

[[plugins-filters-dns-resolve]]
===== `resolve` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Forward resolve one or more fields.

[[plugins-filters-dns-reverse]]
===== `reverse` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Reverse resolve one or more fields.

[[plugins-filters-dns-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `0.5`

`resolv` calls will be wrapped in a timeout instance


