[[plugins-filters-emoji]]
=== emoji

* Version: 1.0.0
* Released on: March 8, 2017
* https://github.com/logstash-plugins/logstash-filter-emoji/blob/master/CHANGELOG.md#100[Changelog]


==== Installation

For plugins not bundled by default, it is easy to install by running `bin/logstash-plugin install logstash-filter-emoji`. See <<working-with-plugins>> for more details.


==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This plugin maps the severity names or numeric codes as defined in
https://tools.ietf.org/html/rfc3164#section-4.1.1[RFC 3164] and
https://tools.ietf.org/html/rfc5424#section-6.2.1[RFC 5424] to the emoji
as defined in the configuration.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
emoji {
    field => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-filters-emoji-add_field>> |<<hash,hash>>|No
| <<plugins-filters-emoji-add_tag>> |<<array,array>>|No
| <<plugins-filters-emoji-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-filters-emoji-fallback>> |<<string,string>>|No
| <<plugins-filters-emoji-field>> |<<string,string>>|Yes
| <<plugins-filters-emoji-id>> |<<string,string>>|No
| <<plugins-filters-emoji-override>> |<<boolean,boolean>>|No
| <<plugins-filters-emoji-periodic_flush>> |<<boolean,boolean>>|No
| <<plugins-filters-emoji-remove_field>> |<<array,array>>|No
| <<plugins-filters-emoji-remove_tag>> |<<array,array>>|No
| <<plugins-filters-emoji-sev_alert>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_critical>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_debug>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_emergency>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_error>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_info>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_notice>> |<<string,string>>|No
| <<plugins-filters-emoji-sev_warning>> |<<string,string>>|No
| <<plugins-filters-emoji-target>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-filters-emoji-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

If this filter is successful, add any arbitrary fields to this event.
Field names can be dynamic and include parts of the event using the `%{field}`.

Example:
[source,ruby]
    filter {
      emoji {
        add_field => { "foo_%{somefield}" => "Hello world, from %{host}" }
      }
    }
[source,ruby]
    # You can also add multiple fields at once:
    filter {
      emoji {
        add_field => {
          "foo_%{somefield}" => "Hello world, from %{host}"
          "new_field" => "new_static_value"
        }
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add field `foo_hello` if it is present, with the
value above and the `%{host}` piece replaced with that value from the
event. The second example would also add a hardcoded field.

[[plugins-filters-emoji-add_tag]]
===== `add_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, add arbitrary tags to the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      emoji {
        add_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also add multiple tags at once:
    filter {
      emoji {
        add_tag => [ "foo_%{somefield}", "taggedy_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add a tag `foo_hello` (and the second example would of course add a `taggedy_tag` tag).

[[plugins-filters-emoji-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-filters-emoji-fallback]]
===== `fallback` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

In case no match is found in the event, this will add a default emoji, which
will always populate `target`, if the match failed.

For example, if we have configured `fallback => "`❓`"`, using this
dictionary:
[source,ruby]
    foo: 👤

Then, if logstash received an event with the field `foo` set to 👤, the
target field would be set to 👤. However, if logstash received an event with
`foo` set to `nope`, then the target field would still be populated, but
with the value of ❓.
This configuration can be dynamic and include parts of the event using the
`%{field}` syntax.

[[plugins-filters-emoji-field]]
===== `field` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the logstash event field containing the value to be compared for
a match by the emoji filter (e.g. `severity`).

If this field is an array, only the first value will be used.

[[plugins-filters-emoji-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-filters-emoji-override]]
===== `override` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If the target field already exists, this configuration item specifies
whether the filter should skip being rewritten as an emoji (default) or
overwrite the target field value with the emoji value.

[[plugins-filters-emoji-periodic_flush]]
===== `periodic_flush` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Call the filter flush method at regular interval.
Optional.

[[plugins-filters-emoji-remove_field]]
===== `remove_field` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary fields from this event.
Fields names can be dynamic and include parts of the event using the %{field}
Example:
[source,ruby]
    filter {
      emoji {
        remove_field => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple fields at once:
    filter {
      emoji {
        remove_field => [ "foo_%{somefield}", "my_extraneous_field" ]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the field with name `foo_hello` if it is present. The second
example would remove an additional, non-dynamic field.

[[plugins-filters-emoji-remove_tag]]
===== `remove_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary tags from the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      emoji {
        remove_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple tags at once:
    filter {
      emoji {
        remove_tag => [ "foo_%{somefield}", "sad_unwanted_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the tag `foo_hello` if it is present. The second example
would remove a sad, unwanted tag as well.

[[plugins-filters-emoji-sev_alert]]
===== `sev_alert` 

  * Value type is <<string,string>>
  * Default value is `"🚨"`

`sev_alert` selects the emoji/unicode character for Alert severity

[[plugins-filters-emoji-sev_critical]]
===== `sev_critical` 

  * Value type is <<string,string>>
  * Default value is `"🔥"`

`sev_critical` selects the emoji/unicode character for Critical severity

[[plugins-filters-emoji-sev_debug]]
===== `sev_debug` 

  * Value type is <<string,string>>
  * Default value is `"🐛"`

`sev_debug` selects the emoji/unicode character for Debug severity

[[plugins-filters-emoji-sev_emergency]]
===== `sev_emergency` 

  * Value type is <<string,string>>
  * Default value is `"💥"`

`sev_emergency` selects the emoji/unicode character for Emergency severity

[[plugins-filters-emoji-sev_error]]
===== `sev_error` 

  * Value type is <<string,string>>
  * Default value is `"❌"`

`sev_error` selects the emoji/unicode character for Error severity

[[plugins-filters-emoji-sev_info]]
===== `sev_info` 

  * Value type is <<string,string>>
  * Default value is `"ℹ️"`

`sev_info` selects the emoji/unicode character for Informational severity

[[plugins-filters-emoji-sev_notice]]
===== `sev_notice` 

  * Value type is <<string,string>>
  * Default value is `"👀"`

`sev_notice` selects the emoji/unicode character for Notice severity

[[plugins-filters-emoji-sev_warning]]
===== `sev_warning` 

  * Value type is <<string,string>>
  * Default value is `"⚠️"`

`sev_warning` selects the emoji/unicode character for Warning severity

[[plugins-filters-emoji-target]]
===== `target` 

  * Value type is <<string,string>>
  * Default value is `"emoji"`

The target field you wish to populate with the emoji. The default
is a field named `emoji`. Set this to the same value as the source (`field`)
if you want to do a substitution, in this case filter will allways succeed.
This will overwrite the old value of the source field!


