[[plugins-filters-kv]]
=== kv

* Version: 4.0.0
* Released on: February 6, 2017
* https://github.com/logstash-plugins/logstash-filter-kv/blob/master/CHANGELOG.md#400[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This filter helps automatically parse messages (or specific event fields)
which are of the `foo=bar` variety.

For example, if you have a log message which contains `ip=1.2.3.4
error=REFUSED`, you can parse those automatically by configuring:
[source,ruby]
    filter {
      kv { }
    }

The above will result in a message of `ip=1.2.3.4 error=REFUSED` having
the fields:

* `ip: 1.2.3.4`
* `error: REFUSED`

This is great for postfix, iptables, and other types of logs that
tend towards `key=value` syntax.

You can configure any arbitrary strings to split your data on,
in case your data is not structured using `=` signs and whitespace.
For example, this filter can also be used to parse query parameters like
`foo=bar&baz=fizz` by setting the `field_split` parameter to `&`.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
kv {
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-filters-kv-add_field>> |<<hash,hash>>|No
| <<plugins-filters-kv-add_tag>> |<<array,array>>|No
| <<plugins-filters-kv-allow_duplicate_values>> |<<boolean,boolean>>|No
| <<plugins-filters-kv-default_keys>> |<<hash,hash>>|No
| <<plugins-filters-kv-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-filters-kv-exclude_keys>> |<<array,array>>|No
| <<plugins-filters-kv-field_split>> |<<string,string>>|No
| <<plugins-filters-kv-id>> |<<string,string>>|No
| <<plugins-filters-kv-include_brackets>> |<<boolean,boolean>>|No
| <<plugins-filters-kv-include_keys>> |<<array,array>>|No
| <<plugins-filters-kv-periodic_flush>> |<<boolean,boolean>>|No
| <<plugins-filters-kv-prefix>> |<<string,string>>|No
| <<plugins-filters-kv-recursive>> |<<boolean,boolean>>|No
| <<plugins-filters-kv-remove_char_key>> |<<string,string>>|No
| <<plugins-filters-kv-remove_char_value>> |<<string,string>>|No
| <<plugins-filters-kv-remove_field>> |<<array,array>>|No
| <<plugins-filters-kv-remove_tag>> |<<array,array>>|No
| <<plugins-filters-kv-source>> |<<string,string>>|No
| <<plugins-filters-kv-target>> |<<string,string>>|No
| <<plugins-filters-kv-transform_key>> |<<string,string>>, one of `["lowercase", "uppercase", "capitalize"]`|No
| <<plugins-filters-kv-transform_value>> |<<string,string>>, one of `["lowercase", "uppercase", "capitalize"]`|No
| <<plugins-filters-kv-trim_key>> |<<string,string>>|No
| <<plugins-filters-kv-trim_value>> |<<string,string>>|No
| <<plugins-filters-kv-value_split>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-filters-kv-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

If this filter is successful, add any arbitrary fields to this event.
Field names can be dynamic and include parts of the event using the `%{field}`.

Example:
[source,ruby]
    filter {
      kv {
        add_field => { "foo_%{somefield}" => "Hello world, from %{host}" }
      }
    }
[source,ruby]
    # You can also add multiple fields at once:
    filter {
      kv {
        add_field => {
          "foo_%{somefield}" => "Hello world, from %{host}"
          "new_field" => "new_static_value"
        }
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add field `foo_hello` if it is present, with the
value above and the `%{host}` piece replaced with that value from the
event. The second example would also add a hardcoded field.

[[plugins-filters-kv-add_tag]]
===== `add_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, add arbitrary tags to the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      kv {
        add_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also add multiple tags at once:
    filter {
      kv {
        add_tag => [ "foo_%{somefield}", "taggedy_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add a tag `foo_hello` (and the second example would of course add a `taggedy_tag` tag).

[[plugins-filters-kv-allow_duplicate_values]]
===== `allow_duplicate_values` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

A bool option for removing duplicate key/value pairs. When set to false, only
one unique key/value pair will be preserved.

For example, consider a source like `from=me from=me`. `[from]` will map to
an Array with two elements: `["me", "me"]`. To only keep unique key/value pairs,
you could use this configuration:
[source,ruby]
    filter {
      kv {
        allow_duplicate_values => false
      }
    }

[[plugins-filters-kv-default_keys]]
===== `default_keys` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

A hash specifying the default keys and their values which should be added to the event
in case these keys do not exist in the source field being parsed.
[source,ruby]
    filter {
      kv {
        default_keys => [ "from", "logstash@example.com",
                         "to", "default@dev.null" ]
      }
    }

[[plugins-filters-kv-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-filters-kv-exclude_keys]]
===== `exclude_keys` 

  * Value type is <<array,array>>
  * Default value is `[]`

An array specifying the parsed keys which should not be added to the event.
By default no keys will be excluded.

For example, consider a source like `Hey, from=<abc>, to=def foo=bar`.
To exclude `from` and `to`, but retain the `foo` key, you could use this configuration:
[source,ruby]
    filter {
      kv {
        exclude_keys => [ "from", "to" ]
      }
    }

[[plugins-filters-kv-field_split]]
===== `field_split` 

  * Value type is <<string,string>>
  * Default value is `" "`

A string of characters to use as delimiters for parsing out key-value pairs.

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

*Example with URL Query Strings*

For example, to split out the args from a url query string such as
`?pin=12345~0&d=123&e=foo@bar.com&oq=bobo&ss=12345`:
[source,ruby]
    filter {
      kv {
        field_split => "&?"
      }
    }

The above splits on both `&` and `?` characters, giving you the following
fields:

* `pin: 12345~0`
* `d: 123`
* `e: foo@bar.com`
* `oq: bobo`
* `ss: 12345`

[[plugins-filters-kv-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-filters-kv-include_brackets]]
===== `include_brackets` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

A boolean specifying whether to treat square brackets, angle brackets,
and parentheses as value "wrappers" that should be removed from the value.
[source,ruby]
    filter {
      kv {
        include_brackets => true
      }
    }

For example, the result of this line:
`bracketsone=(hello world) bracketstwo=[hello world] bracketsthree=<hello world>`

will be:

* bracketsone: hello world
* bracketstwo: hello world
* bracketsthree: hello world

instead of:

* bracketsone: (hello
* bracketstwo: [hello
* bracketsthree: <hello


[[plugins-filters-kv-include_keys]]
===== `include_keys` 

  * Value type is <<array,array>>
  * Default value is `[]`

An array specifying the parsed keys which should be added to the event.
By default all keys will be added.

For example, consider a source like `Hey, from=<abc>, to=def foo=bar`.
To include `from` and `to`, but exclude the `foo` key, you could use this configuration:
[source,ruby]
    filter {
      kv {
        include_keys => [ "from", "to" ]
      }
    }

[[plugins-filters-kv-periodic_flush]]
===== `periodic_flush` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Call the filter flush method at regular interval.
Optional.

[[plugins-filters-kv-prefix]]
===== `prefix` 

  * Value type is <<string,string>>
  * Default value is `""`

A string to prepend to all of the extracted keys.

For example, to prepend arg_ to all keys:
[source,ruby]
    filter { kv { prefix => "arg_" } }

[[plugins-filters-kv-recursive]]
===== `recursive` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

A boolean specifying whether to drill down into values
and recursively get more key-value pairs from it.
The extra key-value pairs will be stored as subkeys of the root key.

Default is not to recursive values.
[source,ruby]
    filter {
      kv {
        recursive => "true"
      }
    }


[[plugins-filters-kv-remove_char_key]]
===== `remove_char_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

A string of characters to remove from the key.

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

Contrary to trim option, all characters are removed from the key, whatever their position.

For example, to remove `<` `>` `[` `]` and `,` characters from keys:
[source,ruby]
    filter {
      kv {
        remove_char_key => "<>\[\],"
      }
    }

[[plugins-filters-kv-remove_char_value]]
===== `remove_char_value` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

A string of characters to remove from the value.

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

Contrary to trim option, all characters are removed from the value, whatever their position.

For example, to remove `<`, `>`, `[`, `]` and `,` characters from values:
[source,ruby]
    filter {
      kv {
        remove_char_value => "<>\[\],"
      }
    }

[[plugins-filters-kv-remove_field]]
===== `remove_field` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary fields from this event.
Fields names can be dynamic and include parts of the event using the %{field}
Example:
[source,ruby]
    filter {
      kv {
        remove_field => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple fields at once:
    filter {
      kv {
        remove_field => [ "foo_%{somefield}", "my_extraneous_field" ]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the field with name `foo_hello` if it is present. The second
example would remove an additional, non-dynamic field.

[[plugins-filters-kv-remove_tag]]
===== `remove_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary tags from the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      kv {
        remove_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple tags at once:
    filter {
      kv {
        remove_tag => [ "foo_%{somefield}", "sad_unwanted_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the tag `foo_hello` if it is present. The second example
would remove a sad, unwanted tag as well.

[[plugins-filters-kv-source]]
===== `source` 

  * Value type is <<string,string>>
  * Default value is `"message"`

The field to perform `key=value` searching on

For example, to process the `not_the_message` field:
[source,ruby]
    filter { kv { source => "not_the_message" } }

[[plugins-filters-kv-target]]
===== `target` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the container to put all of the key-value pairs into.

If this setting is omitted, fields will be written to the root of the
event, as individual fields.

For example, to place all keys into the event field kv:
[source,ruby]
    filter { kv { target => "kv" } }

[[plugins-filters-kv-transform_key]]
===== `transform_key` 

  * Value can be any of: `lowercase`, `uppercase`, `capitalize`
  * There is no default value for this setting.

Transform keys to lower case, upper case or capitals.

For example, to lowercase all keys:
[source,ruby]
    filter {
      kv {
        transform_key => "lowercase"
      }
    }

[[plugins-filters-kv-transform_value]]
===== `transform_value` 

  * Value can be any of: `lowercase`, `uppercase`, `capitalize`
  * There is no default value for this setting.

Transform values to lower case, upper case or capitals.

For example, to capitalize all values:
[source,ruby]
    filter {
      kv {
        transform_value => "capitalize"
      }
    }

[[plugins-filters-kv-trim_key]]
===== `trim_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

A string of characters to trim from the key. This is useful if your
keys are wrapped in brackets or start with space.

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

Only leading and trailing characters are trimed from the key.

For example, to trim `<` `>` `[` `]` and `,` characters from keys:
[source,ruby]
    filter {
      kv {
        trim_key => "<>\[\],"
      }
    }

[[plugins-filters-kv-trim_value]]
===== `trim_value` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Constants used for transform check
A string of characters to trim from the value. This is useful if your
values are wrapped in brackets or are terminated with commas (like postfix
logs).

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

Only leading and trailing characters are trimed from the value.

For example, to trim `<`, `>`, `[`, `]` and `,` characters from values:
[source,ruby]
    filter {
      kv {
        trim_value => "<>\[\],"
      }
    }

[[plugins-filters-kv-value_split]]
===== `value_split` 

  * Value type is <<string,string>>
  * Default value is `"="`

A non-empty string of characters to use as delimiters for identifying key-value relations.

These characters form a regex character class and thus you must escape special regex
characters like `[` or `]` using `\`.

For example, to identify key-values such as
`key1:value1 key2:value2`:
[source,ruby]
    filter { kv { value_split => ":" } }


