[[plugins-filters-throttle]]
=== throttle



The throttle filter is for throttling the number of events received. The filter
is configured with a lower bound, the `before_count`, and upper bound, the `after_count`,
and a period of time. All events passing through the filter will be counted based on 
a key. As long as the count is less than the `before_count` or greater than the 
`after_count`, the event will be "throttled" which means the filter will be considered 
successful and any tags or fields will be added.

For example, if you wanted to throttle events so you only receive an event after 2 
occurrences and you get no more than 3 in 10 minutes, you would use the 
configuration:
[source,ruby]
    period => 600
    before_count => 3
    after_count => 5

Which would result in:
==========================
    event 1 - throttled (successful filter, period start)
    event 2 - throttled (successful filter)
    event 3 - not throttled
    event 4 - not throttled
    event 5 - not throttled
    event 6 - throttled (successful filter)
    event 7 - throttled (successful filter)
    event x - throttled (successful filter)
    period end
    event 1 - throttled (successful filter, period start)
    event 2 - throttled (successful filter)
    event 3 - not throttled
    event 4 - not throttled
    event 5 - not throttled
    event 6 - throttled (successful filter)
    ...
==========================
Another example is if you wanted to throttle events so you only receive 1 event per 
hour, you would use the configuration:
[source,ruby]
    period => 3600
    before_count => -1
    after_count => 1

Which would result in:
==========================
    event 1 - not throttled (period start)
    event 2 - throttled (successful filter)
    event 3 - throttled (successful filter)
    event 4 - throttled (successful filter)
    event x - throttled (successful filter)
    period end
    event 1 - not throttled (period start)
    event 2 - throttled (successful filter)
    event 3 - throttled (successful filter)
    event 4 - throttled (successful filter)
    ...
==========================
A common use case would be to use the throttle filter to throttle events before 3 and 
after 5 while using multiple fields for the key and then use the drop filter to remove 
throttled events. This configuration might appear as:
[source,ruby]
    filter {
      throttle {
        before_count => 3
        after_count => 5
        period => 3600
        key => "%{host}%{message}"
        add_tag => "throttled"
      }
      if "throttled" in [tags] {
        drop { }
      }
    }

Another case would be to store all events, but only email non-throttled 
events so the op's inbox isn't flooded with emails in the event of a system error. 
This configuration might appear as:
[source,ruby]
    filter {
      throttle {
        before_count => 3
        after_count => 5
        period => 3600
        key => "%{message}"
        add_tag => "throttled"
      }
    }
    output {
      if "throttled" not in [tags] {
        email {
   	    from => "logstash@mycompany.com"
   	    subject => "Production System Alert"
   	    to => "ops@mycompany.com"
   	    via => "sendmail"
   	    body => "Alert on %{host} from path %{path}:\n\n%{message}"
   	    options => { "location" => "/usr/sbin/sendmail" }
        }
      }
      elasticsearch_http {
        host => "localhost"
        port => "19200"
      }
    }

The event counts are cleared after the configured period elapses since the 
first instance of the event. That is, all the counts don't reset at the same 
time but rather the throttle period is per unique key value.

Mike Pilone (@mikepilone)


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
throttle {
    key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-filters-throttle-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-filters-throttle-add_tag>> |<<array,array>>|No|`[]`
| <<plugins-filters-throttle-after_count>> |<<number,number>>|No|`-1`
| <<plugins-filters-throttle-before_count>> |<<number,number>>|No|`-1`
| <<plugins-filters-throttle-key>> |<<string,string>>|Yes|
| <<plugins-filters-throttle-max_counters>> |<<number,number>>|No|`100000`
| <<plugins-filters-throttle-period>> |<<string,string>>|No|`"3600"`
| <<plugins-filters-throttle-periodic_flush>> |<<boolean,boolean>>|No|`false`
| <<plugins-filters-throttle-remove_field>> |<<array,array>>|No|`[]`
| <<plugins-filters-throttle-remove_tag>> |<<array,array>>|No|`[]`
|=======================================================================



==== Details

&nbsp;

[[plugins-filters-throttle-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

If this filter is successful, add any arbitrary fields to this event.
Field names can be dynamic and include parts of the event using the `%{field}`.

Example:
[source,ruby]
    filter {
      throttle {
        add_field => { "foo_%{somefield}" => "Hello world, from %{host}" }
      }
    }
[source,ruby]
    # You can also add multiple fields at once:
    filter {
      throttle {
        add_field => {
          "foo_%{somefield}" => "Hello world, from %{host}"
          "new_field" => "new_static_value"
        }
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add field `foo_hello` if it is present, with the
value above and the `%{host}` piece replaced with that value from the
event. The second example would also add a hardcoded field.

[[plugins-filters-throttle-add_tag]]
===== `add_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, add arbitrary tags to the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      throttle {
        add_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also add multiple tags at once:
    filter {
      throttle {
        add_tag => [ "foo_%{somefield}", "taggedy_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would add a tag `foo_hello` (and the second example would of course add a `taggedy_tag` tag).

[[plugins-filters-throttle-after_count]]
===== `after_count` 

  * Value type is <<number,number>>
  * Default value is `-1`

Events greater than this count will be throttled. Setting this value to -1, the 
default, will cause no messages to be throttled based on the upper bound.

[[plugins-filters-throttle-before_count]]
===== `before_count` 

  * Value type is <<number,number>>
  * Default value is `-1`

Events less than this count will be throttled. Setting this value to -1, the 
default, will cause no messages to be throttled based on the lower bound.

[[plugins-filters-throttle-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-filters-throttle-key]]
===== `key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name to use in configuration files.
The key used to identify events. Events with the same key will be throttled
as a group.  Field substitutions are allowed, so you can combine multiple
fields.

[[plugins-filters-throttle-max_counters]]
===== `max_counters` 

  * Value type is <<number,number>>
  * Default value is `100000`

The maximum number of counters to store before the oldest counter is purged. Setting 
this value to -1 will prevent an upper bound no constraint on the number of counters  
and they will only be purged after expiration. This configuration value should only 
be used as a memory control mechanism and can cause early counter expiration if the 
value is reached. It is recommended to leave the default value and ensure that your 
key is selected such that it limits the number of counters required (i.e. don't 
use UUID as the key!)

[[plugins-filters-throttle-period]]
===== `period` 

  * Value type is <<string,string>>
  * Default value is `"3600"`

The period in seconds after the first occurrence of an event until the count is 
reset for the event. This period is tracked per unique key value.  Field
substitutions are allowed in this value.  They will be evaluated when the _first_
event for a given key is seen.  This allows you to specify that certain kinds
of events throttle for a specific period.

[[plugins-filters-throttle-periodic_flush]]
===== `periodic_flush` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Call the filter flush method at regular interval.
Optional.

[[plugins-filters-throttle-remove_field]]
===== `remove_field` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary fields from this event.
Fields names can be dynamic and include parts of the event using the %{field}
Example:
[source,ruby]
    filter {
      throttle {
        remove_field => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple fields at once:
    filter {
      throttle {
        remove_field => [ "foo_%{somefield}", "my_extraneous_field" ]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the field with name `foo_hello` if it is present. The second
example would remove an additional, non-dynamic field.

[[plugins-filters-throttle-remove_tag]]
===== `remove_tag` 

  * Value type is <<array,array>>
  * Default value is `[]`

If this filter is successful, remove arbitrary tags from the event.
Tags can be dynamic and include parts of the event using the `%{field}`
syntax.

Example:
[source,ruby]
    filter {
      throttle {
        remove_tag => [ "foo_%{somefield}" ]
      }
    }
[source,ruby]
    # You can also remove multiple tags at once:
    filter {
      throttle {
        remove_tag => [ "foo_%{somefield}", "sad_unwanted_tag"]
      }
    }

If the event has field `"somefield" == "hello"` this filter, on success,
would remove the tag `foo_hello` if it is present. The second example
would remove a sad, unwanted tag as well.

[[plugins-filters-throttle-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-filters-throttle-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

Note that all of the specified routing options (`type`,`tags`,`exclude_tags`,`include_fields`,
`exclude_fields`) must be met in order for the event to be handled by the filter.
The type to act on. If a type is given, then this filter will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.


