[[plugins-outputs-circonus]]
=== circonus

* Version: 3.0.0
* Released on: 2016-09-09
* https://github.com/logstash-plugins/logstash-output-circonus/blob/master/CHANGELOG.md#300[Changelog]



NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-circonus`.




&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
circonus {
    annotation => ...
    api_token => ...
    app_name => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-circonus-annotation>> |<<hash,hash>>|Yes|`{}`
| <<plugins-outputs-circonus-api_token>> |<<string,string>>|Yes|
| <<plugins-outputs-circonus-app_name>> |<<string,string>>|Yes|
| <<plugins-outputs-circonus-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-circonus-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-circonus-id>> |<<string,string>>|No|
| <<plugins-outputs-circonus-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-circonus-annotation]]
===== `annotation` 

  * This is a required setting.
  * Value type is <<hash,hash>>
  * Default value is `{}`

Annotations
Registers an annotation with Circonus
The only required field is `title` and `description`.
`start` and `stop` will be set to the event timestamp.
You can add any other optional annotation values as well.
All values will be passed through `event.sprintf`

Example:
[source,ruby]
  ["title":"Logstash event", "description":"Logstash event for %{host}"]
or
[source,ruby]
  ["title":"Logstash event", "description":"Logstash event for %{host}", "parent_id", "1"]

[[plugins-outputs-circonus-api_token]]
===== `api_token` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

This output lets you send annotations to
Circonus based on Logstash events

Your Circonus API Token

[[plugins-outputs-circonus-app_name]]
===== `app_name` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your Circonus App name
This will be passed through `event.sprintf`
so variables are allowed here:

Example:
 `app_name => "%{myappname}"`

[[plugins-outputs-circonus-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-circonus-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-circonus-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-circonus-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


