[[plugins-outputs-circonus]]
=== circonus


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-output-circonus`.




&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
circonus {
    annotation => ...
    api_token => ...
    app_name => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-circonus-annotation>> |<<hash,hash>>|Yes|`{}`
| <<plugins-outputs-circonus-api_token>> |<<string,string>>|Yes|
| <<plugins-outputs-circonus-app_name>> |<<string,string>>|Yes|
| <<plugins-outputs-circonus-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-circonus-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-circonus-annotation]]
===== `annotation` 

  * This is a required setting.
  * Value type is <<hash,hash>>
  * Default value is `{}`

Annotations
Registers an annotation with Circonus
The only required field is `title` and `description`.
`start` and `stop` will be set to `event["@timestamp"]`
You can add any other optional annotation values as well.
All values will be passed through `event.sprintf`

Example:
[source,ruby]
  ["title":"Logstash event", "description":"Logstash event for %{host}"]
or
[source,ruby]
  ["title":"Logstash event", "description":"Logstash event for %{host}", "parent_id", "1"]

[[plugins-outputs-circonus-api_token]]
===== `api_token` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

This output lets you send annotations to
Circonus based on Logstash events

Your Circonus API Token

[[plugins-outputs-circonus-app_name]]
===== `app_name` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your Circonus App name
This will be passed through `event.sprintf`
so variables are allowed here:

Example:
 `app_name => "%{myappname}"`

[[plugins-outputs-circonus-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-circonus-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


