[[plugins-outputs-graphtastic]]
=== graphtastic


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-output-graphtastic`.


A plugin for a newly developed Java/Spring Metrics application
I didn't really want to code this project but I couldn't find
a respectable alternative that would also run on any Windows
machine - which is the problem and why I am not going with Graphite
and statsd.  This application provides multiple integration options
so as to make its use under your network requirements possible. 
This includes a REST option that is always enabled for your use
in case you want to write a small script to send the occasional 
metric data. 

Find GraphTastic here : https://github.com/NickPadilla/GraphTastic

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
graphtastic {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-graphtastic-batch_number>> |<<number,number>>|No|`60`
| <<plugins-outputs-graphtastic-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-graphtastic-context>> |<<string,string>>|No|`"graphtastic"`
| <<plugins-outputs-graphtastic-error_file>> |<<string,string>>|No|`""`
| <<plugins-outputs-graphtastic-host>> |<<string,string>>|No|`"127.0.0.1"`
| <<plugins-outputs-graphtastic-integration>> |<<string,string>>, one of `["udp", "tcp", "rmi", "rest"]`|No|`"udp"`
| <<plugins-outputs-graphtastic-metrics>> |<<hash,hash>>|No|`{}`
| <<plugins-outputs-graphtastic-port>> |<<number,number>>|No|
| <<plugins-outputs-graphtastic-retries>> |<<number,number>>|No|`1`
| <<plugins-outputs-graphtastic-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-graphtastic-batch_number]]
===== `batch_number` 

  * Value type is <<number,number>>
  * Default value is `60`

the number of metrics to send to GraphTastic at one time. 60 seems to be the perfect 
amount for UDP, with default packet size. 

[[plugins-outputs-graphtastic-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-graphtastic-context]]
===== `context` 

  * Value type is <<string,string>>
  * Default value is `"graphtastic"`

if using rest as your end point you need to also provide the application url
it defaults to localhost/graphtastic.  You can customize the application url
by changing the name of the .war file.  There are other ways to change the 
application context, but they vary depending on the Application Server in use.
Please consult your application server documentation for more on application
contexts.

[[plugins-outputs-graphtastic-error_file]]
===== `error_file` 

  * Value type is <<string,string>>
  * Default value is `""`

setting allows you to specify where we save errored transactions
this makes the most sense at this point - will need to decide
on how we reintegrate these error metrics
NOT IMPLEMENTED!

[[plugins-outputs-graphtastic-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-graphtastic-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"127.0.0.1"`

host for the graphtastic server - defaults to 127.0.0.1

[[plugins-outputs-graphtastic-integration]]
===== `integration` 

  * Value can be any of: `udp`, `tcp`, `rmi`, `rest`
  * Default value is `"udp"`

options are udp(fastest - default) - rmi(faster) - rest(fast) - tcp(don't use TCP yet - some problems - errors out on linux)

[[plugins-outputs-graphtastic-metrics]]
===== `metrics` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

metrics hash - you will provide a name for your metric and the metric 
data as key value pairs.  so for example:

[source,ruby]
metrics => { "Response" => "%{response}" } 

example for the logstash config

[source,ruby]
metrics => [ "Response", "%{response}" ]

NOTE: you can also use the dynamic fields for the key value as well as the actual value

[[plugins-outputs-graphtastic-port]]
===== `port` 

  * Value type is <<number,number>>
  * There is no default value for this setting.

port for the graphtastic instance - defaults to 1199 for RMI, 1299 for TCP, 1399 for UDP, and 8080 for REST

[[plugins-outputs-graphtastic-retries]]
===== `retries` 

  * Value type is <<number,number>>
  * Default value is `1`

number of attempted retry after send error - currently only way to integrate
errored transactions - should try and save to a file or later consumption
either by graphtastic utility or by this program after connectivity is
ensured to be established. 

[[plugins-outputs-graphtastic-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-graphtastic-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-graphtastic-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


