[[plugins-outputs-http]]
=== http

* Version: 4.1.0
* Released on: February 13, 2017
* https://github.com/logstash-plugins/logstash-output-http/blob/master/CHANGELOG.md#410[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description



&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
http {
    http_method => ...
    url => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-http-automatic_retries>> |<<number,number>>|No
| <<plugins-outputs-http-cacert>> |a valid filesystem path|No
| <<plugins-outputs-http-client_cert>> |a valid filesystem path|No
| <<plugins-outputs-http-client_key>> |a valid filesystem path|No
| <<plugins-outputs-http-codec>> |<<codec,codec>>|No
| <<plugins-outputs-http-connect_timeout>> |<<number,number>>|No
| <<plugins-outputs-http-content_type>> |<<string,string>>|No
| <<plugins-outputs-http-cookies>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-follow_redirects>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-format>> |<<string,string>>, one of `["json", "form", "message"]`|No
| <<plugins-outputs-http-headers>> |<<hash,hash>>|No
| <<plugins-outputs-http-http_method>> |<<string,string>>, one of `["put", "post", "patch", "delete", "get", "head"]`|Yes
| <<plugins-outputs-http-id>> |<<string,string>>|No
| <<plugins-outputs-http-ignorable_codes>> |<<number,number>>|No
| <<plugins-outputs-http-keepalive>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-keystore>> |a valid filesystem path|No
| <<plugins-outputs-http-keystore_password>> |<<password,password>>|No
| <<plugins-outputs-http-keystore_type>> |<<string,string>>|No
| <<plugins-outputs-http-mapping>> |<<hash,hash>>|No
| <<plugins-outputs-http-message>> |<<string,string>>|No
| <<plugins-outputs-http-pool_max>> |<<number,number>>|No
| <<plugins-outputs-http-pool_max_per_route>> |<<number,number>>|No
| <<plugins-outputs-http-proxy>> |<<,>>|No
| <<plugins-outputs-http-request_timeout>> |<<number,number>>|No
| <<plugins-outputs-http-retry_failed>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-retry_non_idempotent>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-retryable_codes>> |<<number,number>>|No
| <<plugins-outputs-http-socket_timeout>> |<<number,number>>|No
| <<plugins-outputs-http-ssl_certificate_validation>> |<<boolean,boolean>>|No
| <<plugins-outputs-http-truststore>> |a valid filesystem path|No
| <<plugins-outputs-http-truststore_password>> |<<password,password>>|No
| <<plugins-outputs-http-truststore_type>> |<<string,string>>|No
| <<plugins-outputs-http-url>> |<<string,string>>|Yes
| <<plugins-outputs-http-validate_after_inactivity>> |<<number,number>>|No
| <<plugins-outputs-http-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-http-automatic_retries]]
===== `automatic_retries` 

  * Value type is <<number,number>>
  * Default value is `1`

How many times should the client retry a failing URL. We highly recommend NOT setting this value
to zero if keepalive is enabled. Some servers incorrectly end keepalives early requiring a retry!
Note: if `retry_non_idempotent` is set only GET, HEAD, PUT, DELETE, OPTIONS, and TRACE requests will be retried.

[[plugins-outputs-http-cacert]]
===== `cacert` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If you need to use a custom X.509 CA (.pem certs) specify the path to that here

[[plugins-outputs-http-client_cert]]
===== `client_cert` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If you'd like to use a client certificate (note, most people don't want this) set the path to the x509 cert here

[[plugins-outputs-http-client_key]]
===== `client_key` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If you're using a client certificate specify the path to the encryption key here

[[plugins-outputs-http-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-http-connect_timeout]]
===== `connect_timeout` 

  * Value type is <<number,number>>
  * Default value is `10`

Timeout (in seconds) to wait for a connection to be established. Default is `10s`

[[plugins-outputs-http-content_type]]
===== `content_type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Content type

If not specified, this defaults to the following:

* if format is "json", "application/json"
* if format is "form", "application/x-www-form-urlencoded"

[[plugins-outputs-http-cookies]]
===== `cookies` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Enable cookie support. With this enabled the client will persist cookies
across requests as a normal web browser would. Enabled by default

[[plugins-outputs-http-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-http-follow_redirects]]
===== `follow_redirects` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Should redirects be followed? Defaults to `true`

[[plugins-outputs-http-format]]
===== `format` 

  * Value can be any of: `json`, `form`, `message`
  * Default value is `"json"`

Set the format of the http body.

If form, then the body will be the mapping (or whole event) converted
into a query parameter string, e.g. `foo=bar&baz=fizz...`

If message, then the body will be the result of formatting the event according to message

Otherwise, the event is sent as json.

[[plugins-outputs-http-headers]]
===== `headers` 

  * Value type is <<hash,hash>>
  * There is no default value for this setting.

Custom headers to use
format is `headers => ["X-My-Header", "%{host}"]`

[[plugins-outputs-http-http_method]]
===== `http_method` 

  * This is a required setting.
  * Value can be any of: `put`, `post`, `patch`, `delete`, `get`, `head`
  * There is no default value for this setting.

The HTTP Verb. One of "put", "post", "patch", "delete", "get", "head"

[[plugins-outputs-http-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-http-ignorable_codes]]
===== `ignorable_codes` 

  * Value type is <<number,number>>
  * There is no default value for this setting.

If you would like to consider some non-2xx codes to be successes 
enumerate them here. Responses returning these codes will be considered successes

[[plugins-outputs-http-keepalive]]
===== `keepalive` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Turn this on to enable HTTP keepalive support. We highly recommend setting `automatic_retries` to at least
one with this to fix interactions with broken keepalive implementations.

[[plugins-outputs-http-keystore]]
===== `keystore` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If you need to use a custom keystore (`.jks`) specify that here. This does not work with .pem keys!

[[plugins-outputs-http-keystore_password]]
===== `keystore_password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Specify the keystore password here.
Note, most .jks files created with keytool require a password!

[[plugins-outputs-http-keystore_type]]
===== `keystore_type` 

  * Value type is <<string,string>>
  * Default value is `"JKS"`

Specify the keystore type here. One of `JKS` or `PKCS12`. Default is `JKS`

[[plugins-outputs-http-mapping]]
===== `mapping` 

  * Value type is <<hash,hash>>
  * There is no default value for this setting.

This lets you choose the structure and parts of the event that are sent.


For example:
[source,ruby]
   mapping => {"foo" => "%{host}"
              "bar" => "%{type}"}

[[plugins-outputs-http-message]]
===== `message` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-http-pool_max]]
===== `pool_max` 

  * Value type is <<number,number>>
  * Default value is `50`

Max number of concurrent connections. Defaults to `50`

[[plugins-outputs-http-pool_max_per_route]]
===== `pool_max_per_route` 

  * Value type is <<number,number>>
  * Default value is `25`

Max number of concurrent connections to a single host. Defaults to `25`

[[plugins-outputs-http-proxy]]
===== `proxy` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

If you'd like to use an HTTP proxy . This supports multiple configuration syntaxes:

1. Proxy host in form: `http://proxy.org:1234`
2. Proxy host in form: `{host => "proxy.org", port => 80, scheme => 'http', user => 'username@host', password => 'password'}`
3. Proxy host in form: `{url =>  'http://proxy.org:1234', user => 'username@host', password => 'password'}`

[[plugins-outputs-http-request_timeout]]
===== `request_timeout` 

  * Value type is <<number,number>>
  * Default value is `60`

This module makes it easy to add a very fully configured HTTP client to logstash
based on [Manticore](https://github.com/cheald/manticore).
For an example of its usage see https://github.com/logstash-plugins/logstash-input-http_poller
Timeout (in seconds) for the entire request

[[plugins-outputs-http-retry_failed]]
===== `retry_failed` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Set this to false if you don't want this output to retry failed requests

[[plugins-outputs-http-retry_non_idempotent]]
===== `retry_non_idempotent` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If `automatic_retries` is enabled this will cause non-idempotent HTTP verbs (such as POST) to be retried.

[[plugins-outputs-http-retryable_codes]]
===== `retryable_codes` 

  * Value type is <<number,number>>
  * Default value is `[429, 500, 502, 503, 504]`

If encountered as response codes this plugin will retry these requests

[[plugins-outputs-http-socket_timeout]]
===== `socket_timeout` 

  * Value type is <<number,number>>
  * Default value is `10`

Timeout (in seconds) to wait for data on the socket. Default is `10s`

[[plugins-outputs-http-ssl_certificate_validation]]
===== `ssl_certificate_validation` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Set this to false to disable SSL/TLS certificate validation
Note: setting this to false is generally considered insecure!

[[plugins-outputs-http-truststore]]
===== `truststore` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

If you need to use a custom truststore (`.jks`) specify that here. This does not work with .pem certs!

[[plugins-outputs-http-truststore_password]]
===== `truststore_password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Specify the truststore password here.
Note, most .jks files created with keytool require a password!

[[plugins-outputs-http-truststore_type]]
===== `truststore_type` 

  * Value type is <<string,string>>
  * Default value is `"JKS"`

Specify the truststore type here. One of `JKS` or `PKCS12`. Default is `JKS`

[[plugins-outputs-http-url]]
===== `url` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

This output lets you send events to a
generic HTTP(S) endpoint

This output will execute up to 'pool_max' requests in parallel for performance.
Consider this when tuning this plugin for performance.

Additionally, note that when parallel execution is used strict ordering of events is not
guaranteed!

Beware, this gem does not yet support codecs. Please use the 'format' option for now.
URL to use

[[plugins-outputs-http-validate_after_inactivity]]
===== `validate_after_inactivity` 

  * Value type is <<number,number>>
  * Default value is `200`

How long to wait before checking if the connection is stale before executing a request on a connection using keepalive.
# You may want to set this lower, possibly to 0 if you get connection errors regularly
Quoting the Apache commons docs (this client is based Apache Commmons):
'Defines period of inactivity in milliseconds after which persistent connections must be re-validated prior to being leased to the consumer. Non-positive value passed to this method disables connection validation. This check helps detect connections that have become stale (half-closed) while kept inactive in the pool.'
See https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html#setValidateAfterInactivity(int)[these docs for more info]

[[plugins-outputs-http-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


