[[plugins-outputs-juggernaut]]
=== juggernaut

Push messages to the juggernaut websockets server:

* https://github.com/maccman/juggernaut

Wraps Websockets and supports other methods (including xhr longpolling) This
is basically, just an extension of the redis output (Juggernaut pulls
messages from redis).  But it pushes messages to a particular channel and
formats the messages in the way juggernaut expects.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
juggernaut {
    channels => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-juggernaut-channels>> |<<array,array>>|Yes|
| <<plugins-outputs-juggernaut-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-juggernaut-db>> |<<number,number>>|No|`0`
| <<plugins-outputs-juggernaut-host>> |<<string,string>>|No|`"127.0.0.1"`
| <<plugins-outputs-juggernaut-message_format>> |<<string,string>>|No|
| <<plugins-outputs-juggernaut-password>> |<<password,password>>|No|
| <<plugins-outputs-juggernaut-port>> |<<number,number>>|No|`6379`
| <<plugins-outputs-juggernaut-timeout>> |<<number,number>>|No|`5`
| <<plugins-outputs-juggernaut-workers>> |<<number,number>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-juggernaut-channels]]
===== `channels` 

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

List of channels to which to publish. Dynamic names are
valid here, for example `logstash-%{type}`.

[[plugins-outputs-juggernaut-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-juggernaut-db]]
===== `db` 

  * Value type is <<number,number>>
  * Default value is `0`

The redis database number.

[[plugins-outputs-juggernaut-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags. Note this check is additional to type and tags.

[[plugins-outputs-juggernaut-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"127.0.0.1"`

The hostname of the redis server to which juggernaut is listening.

[[plugins-outputs-juggernaut-message_format]]
===== `message_format` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

How should the message be formatted before pushing to the websocket.

[[plugins-outputs-juggernaut-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password to authenticate with.  There is no authentication by default.

[[plugins-outputs-juggernaut-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `6379`

The port to connect on.

[[plugins-outputs-juggernaut-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.  Note that if you specify
a type, the event must also match that type.
Optional.

[[plugins-outputs-juggernaut-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

Redis initial connection timeout in seconds.

[[plugins-outputs-juggernaut-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-juggernaut-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

