[[plugins-outputs-kafka]]
=== kafka

Write events to a Kafka topic. 

This plugin uses Kafka Client 0.8.2.2. For broker compatibility, see the official https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix[Kafka compatibility reference].
 
If you're using a plugin version that was released after {version}, see the https://www.elastic.co/guide/en/logstash/master/plugins-inputs-kafka.html[latest plugin documentation] for updated information about Kafka compatibility. If you require features not yet available in this plugin (including client version upgrades), please file an issue with details about what you need. 

The only required configuration is the topic name. The default codec is json,
so events will be persisted on the broker in json format. If you select a codec of plain,
Logstash will encode your messages with not only the message but also with a timestamp and
hostname. If you do not want anything but your message passing through, you should make the output
configuration something like:
[source,ruby]
    output {
      kafka {
        codec => plain {
           format => "%{message}"
        }
      }
    }
For more information see http://kafka.apache.org/documentation.html#theproducer

Kafka producer configuration: http://kafka.apache.org/documentation.html#newproducerconfigs

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
kafka {
    topic_id => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-kafka-acks>> |<<string,string>>, one of `["0", "1", "all"]`|No|`"1"`
| <<plugins-outputs-kafka-batch_size>> |<<number,number>>|No|`16384`
| <<plugins-outputs-kafka-block_on_buffer_full>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-kafka-bootstrap_servers>> |<<string,string>>|No|`"localhost:9092"`
| <<plugins-outputs-kafka-buffer_memory>> |<<number,number>>|No|`33554432`
| <<plugins-outputs-kafka-client_id>> |<<string,string>>|No|
| <<plugins-outputs-kafka-codec>> |<<codec,codec>>|No|`"json"`
| <<plugins-outputs-kafka-compression_type>> |<<string,string>>, one of `["none", "gzip", "snappy"]`|No|`"none"`
| <<plugins-outputs-kafka-key_serializer>> |<<string,string>>|No|`"org.apache.kafka.common.serialization.StringSerializer"`
| <<plugins-outputs-kafka-linger_ms>> |<<number,number>>|No|`0`
| <<plugins-outputs-kafka-max_request_size>> |<<number,number>>|No|`1048576`
| <<plugins-outputs-kafka-message_key>> |<<string,string>>|No|
| <<plugins-outputs-kafka-metadata_fetch_timeout_ms>> |<<number,number>>|No|`60000`
| <<plugins-outputs-kafka-metadata_max_age_ms>> |<<number,number>>|No|`300000`
| <<plugins-outputs-kafka-receive_buffer_bytes>> |<<number,number>>|No|`32768`
| <<plugins-outputs-kafka-reconnect_backoff_ms>> |<<number,number>>|No|`10`
| <<plugins-outputs-kafka-retries>> |<<number,number>>|No|`0`
| <<plugins-outputs-kafka-retry_backoff_ms>> |<<number,number>>|No|`100`
| <<plugins-outputs-kafka-send_buffer_bytes>> |<<number,number>>|No|`131072`
| <<plugins-outputs-kafka-timeout_ms>> |<<number,number>>|No|`30000`
| <<plugins-outputs-kafka-topic_id>> |<<string,string>>|Yes|
| <<plugins-outputs-kafka-value_serializer>> |<<string,string>>|No|`"org.apache.kafka.common.serialization.StringSerializer"`
| <<plugins-outputs-kafka-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-kafka-acks]]
===== `acks` 

  * Value can be any of: `0`, `1`, `all`
  * Default value is `"1"`

The number of acknowledgments the producer requires the leader to have received
before considering a request complete.

acks=0,   the producer will not wait for any acknowledgment from the server at all.
acks=1,   This will mean the leader will write the record to its local log but
          will respond without awaiting full acknowledgement from all followers.
acks=all, This means the leader will wait for the full set of in-sync replicas to acknowledge the record.

[[plugins-outputs-kafka-batch_size]]
===== `batch_size` 

  * Value type is <<number,number>>
  * Default value is `16384`

The producer will attempt to batch records together into fewer requests whenever multiple
records are being sent to the same partition. This helps performance on both the client
and the server. This configuration controls the default batch size in bytes.

[[plugins-outputs-kafka-block_on_buffer_full]]
===== `block_on_buffer_full` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

When our memory buffer is exhausted we must either stop accepting new
records (block) or throw errors. By default this setting is true and we block,
however in some scenarios blocking is not desirable and it is better to immediately give an error.

[[plugins-outputs-kafka-bootstrap_servers]]
===== `bootstrap_servers` 

  * Value type is <<string,string>>
  * Default value is `"localhost:9092"`

This is for bootstrapping and the producer will only use it for getting metadata (topics,
partitions and replicas). The socket connections for sending the actual data will be
established based on the broker information returned in the metadata. The format is
`host1:port1,host2:port2`, and the list can be a subset of brokers or a VIP pointing to a
subset of brokers.

[[plugins-outputs-kafka-buffer_memory]]
===== `buffer_memory` 

  * Value type is <<number,number>>
  * Default value is `33554432`

The total bytes of memory the producer can use to buffer records waiting to be sent to the server.

[[plugins-outputs-kafka-client_id]]
===== `client_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The id string to pass to the server when making requests.
The purpose of this is to be able to track the source of requests beyond just
ip/port by allowing a logical application name to be included with the request

[[plugins-outputs-kafka-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"json"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-kafka-compression_type]]
===== `compression_type` 

  * Value can be any of: `none`, `gzip`, `snappy`
  * Default value is `"none"`

The compression type for all data generated by the producer.
The default is none (i.e. no compression). Valid values are none, gzip, or snappy.

[[plugins-outputs-kafka-key_serializer]]
===== `key_serializer` 

  * Value type is <<string,string>>
  * Default value is `"org.apache.kafka.common.serialization.StringSerializer"`

Serializer class for the key of the message

[[plugins-outputs-kafka-linger_ms]]
===== `linger_ms` 

  * Value type is <<number,number>>
  * Default value is `0`

The producer groups together any records that arrive in between request
transmissions into a single batched request. Normally this occurs only under
load when records arrive faster than they can be sent out. However in some circumstances
the client may want to reduce the number of requests even under moderate load.
This setting accomplishes this by adding a small amount of artificial delay—that is,
rather than immediately sending out a record the producer will wait for up to the given delay
to allow other records to be sent so that the sends can be batched together.

[[plugins-outputs-kafka-max_request_size]]
===== `max_request_size` 

  * Value type is <<number,number>>
  * Default value is `1048576`

The maximum size of a request

[[plugins-outputs-kafka-message_key]]
===== `message_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The key for the message

[[plugins-outputs-kafka-metadata_fetch_timeout_ms]]
===== `metadata_fetch_timeout_ms` 

  * Value type is <<number,number>>
  * Default value is `60000`

the timeout setting for initial metadata request to fetch topic metadata.

[[plugins-outputs-kafka-metadata_max_age_ms]]
===== `metadata_max_age_ms` 

  * Value type is <<number,number>>
  * Default value is `300000`

the max time in milliseconds before a metadata refresh is forced.

[[plugins-outputs-kafka-receive_buffer_bytes]]
===== `receive_buffer_bytes` 

  * Value type is <<number,number>>
  * Default value is `32768`

The size of the TCP receive buffer to use when reading data

[[plugins-outputs-kafka-reconnect_backoff_ms]]
===== `reconnect_backoff_ms` 

  * Value type is <<number,number>>
  * Default value is `10`

The amount of time to wait before attempting to reconnect to a given host when a connection fails.

[[plugins-outputs-kafka-retries]]
===== `retries` 

  * Value type is <<number,number>>
  * Default value is `0`

Setting a value greater than zero will cause the client to
resend any record whose send fails with a potentially transient error.

[[plugins-outputs-kafka-retry_backoff_ms]]
===== `retry_backoff_ms` 

  * Value type is <<number,number>>
  * Default value is `100`

The amount of time to wait before attempting to retry a failed produce request to a given topic partition.

[[plugins-outputs-kafka-send_buffer_bytes]]
===== `send_buffer_bytes` 

  * Value type is <<number,number>>
  * Default value is `131072`

The size of the TCP send buffer to use when sending data.

[[plugins-outputs-kafka-timeout_ms]]
===== `timeout_ms` 

  * Value type is <<number,number>>
  * Default value is `30000`

The configuration controls the maximum amount of time the server will wait for acknowledgments
from followers to meet the acknowledgment requirements the producer has specified with the
acks configuration. If the requested number of acknowledgments are not met when the timeout
elapses an error will be returned. This timeout is measured on the server side and does not
include the network latency of the request.

[[plugins-outputs-kafka-topic_id]]
===== `topic_id` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The topic to produce messages to

[[plugins-outputs-kafka-value_serializer]]
===== `value_serializer` 

  * Value type is <<string,string>>
  * Default value is `"org.apache.kafka.common.serialization.StringSerializer"`

Serializer class for the value of the message

[[plugins-outputs-kafka-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


