[[plugins-outputs-lumberjack]]
=== lumberjack

* Version: 3.1.2
* Released on: 2016-09-15
* https://github.com/logstash-plugins/logstash-output-lumberjack/blob/master/CHANGELOG.md#312[Changelog]



NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-lumberjack`.




&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
lumberjack {
    hosts => ...
    port => ...
    ssl_certificate => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-lumberjack-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-lumberjack-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-lumberjack-flush_size>> |<<number,number>>|No|`1024`
| <<plugins-outputs-lumberjack-hosts>> |<<array,array>>|Yes|
| <<plugins-outputs-lumberjack-id>> |<<string,string>>|No|
| <<plugins-outputs-lumberjack-idle_flush_time>> |<<number,number>>|No|`1`
| <<plugins-outputs-lumberjack-port>> |<<number,number>>|Yes|
| <<plugins-outputs-lumberjack-ssl_certificate>> |a valid filesystem path|Yes|
| <<plugins-outputs-lumberjack-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-lumberjack-codec]]
===== `codec`

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-lumberjack-enable_metric]]
===== `enable_metric`

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-lumberjack-flush_size]]
===== `flush_size`

  * Value type is <<number,number>>
  * Default value is `1024`

To make efficient calls to the lumberjack output we are buffering events locally.
if the number of events exceed the number the declared `flush_size` we will
send them to the logstash server.

[[plugins-outputs-lumberjack-hosts]]
===== `hosts`

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

list of addresses lumberjack can send to

[[plugins-outputs-lumberjack-id]]
===== `id`

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-lumberjack-idle_flush_time]]
===== `idle_flush_time`

  * Value type is <<number,number>>
  * Default value is `1`

The amount of time since last flush before a flush is forced.

This setting helps ensure slow event rates don't get stuck in Logstash.
For example, if your `flush_size` is 100, and you have received 10 events,
and it has been more than `idle_flush_time` seconds since the last flush,
Logstash will flush those 10 events automatically.

This helps keep both fast and slow log streams moving along in
near-real-time.

[[plugins-outputs-lumberjack-port]]
===== `port`

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

the port to connect to

[[plugins-outputs-lumberjack-ssl_certificate]]
===== `ssl_certificate`

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

ssl certificate to use

[[plugins-outputs-lumberjack-workers]]
===== `workers`

  * Value type is <<string,string>>
  * Default value is `1`




