[[plugins-outputs-mongodb]]
=== mongodb



&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
mongodb {
    collection => ... 
    database => ... 
    uri => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-mongodb-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-mongodb-collection>> |<<string,string>>|Yes|
| <<plugins-outputs-mongodb-database>> |<<string,string>>|Yes|
| <<plugins-outputs-mongodb-generateId>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-mongodb-isodate>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-mongodb-retry_delay>> |<<number,number>>|No|`3`
| <<plugins-outputs-mongodb-uri>> |<<string,string>>|Yes|
| <<plugins-outputs-mongodb-workers>> |<<number,number>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-mongodb-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-mongodb-collection]]
===== `collection` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The collection to use. This value can use `%{foo}` values to dynamically
select a collection based on data in the event.

[[plugins-outputs-mongodb-database]]
===== `database` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The database to use

[[plugins-outputs-mongodb-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags. Note this check is additional to type and tags.

[[plugins-outputs-mongodb-generateId]]
===== `generateId` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If true, an "_id" field will be added to the document before insertion.
The "_id" field will use the timestamp of the event and overwrite an existing
"_id" field in the event.

[[plugins-outputs-mongodb-isodate]]
===== `isodate` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If true, store the @timestamp field in mongodb as an ISODate type instead
of an ISO8601 string.  For more information about this, see
http://www.mongodb.org/display/DOCS/Dates

[[plugins-outputs-mongodb-retry_delay]]
===== `retry_delay` 

  * Value type is <<number,number>>
  * Default value is `3`

Number of seconds to wait after failure before retrying

[[plugins-outputs-mongodb-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.  Note that if you specify
a type, the event must also match that type.
Optional.

[[plugins-outputs-mongodb-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-mongodb-uri]]
===== `uri` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

a MongoDB URI to connect to
See http://docs.mongodb.org/manual/reference/connection-string/

[[plugins-outputs-mongodb-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

