[[plugins-outputs-nagios]]
=== nagios

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-output-nagios/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

The Nagios output is used for sending passive check results to Nagios via the
Nagios command file. This output currently supports Nagios 3.

For this output to work, your event _must_ have the following Logstash event fields:

 * `nagios_host`
 * `nagios_service`

These Logstash event fields are supported, but optional:

 * `nagios_annotation`
 * `nagios_level` (overrides `nagios_level` configuration option)

There are two configuration options:

 * `commandfile` - The location of the Nagios external command file. Defaults
   to '/var/lib/nagios3/rw/nagios.cmd'
 * `nagios_level` - Specifies the level of the check to be sent. Defaults to
   CRITICAL and can be overriden by setting the "nagios_level" field to one
   of "OK", "WARNING", "CRITICAL", or "UNKNOWN"
[source,ruby]
    output{
      if [message] =~ /(error|ERROR|CRITICAL)/ {
        nagios {
          # your config here
        }
      }
    }


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
nagios {
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-nagios-codec>> |<<codec,codec>>|No
| <<plugins-outputs-nagios-commandfile>> |<<,>>|No
| <<plugins-outputs-nagios-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-nagios-id>> |<<string,string>>|No
| <<plugins-outputs-nagios-nagios_level>> |<<string,string>>, one of `["0", "1", "2", "3"]`|No
| <<plugins-outputs-nagios-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-nagios-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-nagios-commandfile]]
===== `commandfile` 

  * Value type is <<string,string>>
  * Default value is `"/var/lib/nagios3/rw/nagios.cmd"`

The full path to your Nagios command file.

[[plugins-outputs-nagios-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-nagios-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-nagios-nagios_level]]
===== `nagios_level` 

  * Value can be any of: `0`, `1`, `2`, `3`
  * Default value is `"2"`

The Nagios check level. Should be one of 0=OK, 1=WARNING, 2=CRITICAL,
3=UNKNOWN. Defaults to 2 - CRITICAL.

[[plugins-outputs-nagios-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

