[[plugins-outputs-nagios]]
=== nagios

NOTE: This is a community-maintained plugin!

The Nagios output is used for sending passive check results to Nagios via the
Nagios command file. This output currently supports Nagios 3.

For this output to work, your event _must_ have the following Logstash event fields:

 * `nagios_host`
 * `nagios_service`

These Logstash event fields are supported, but optional:

 * `nagios_annotation`
 * `nagios_level` (overrides `nagios_level` configuration option)

There are two configuration options:

 * `commandfile` - The location of the Nagios external command file. Defaults
   to '/var/lib/nagios3/rw/nagios.cmd'
 * `nagios_level` - Specifies the level of the check to be sent. Defaults to
   CRITICAL and can be overriden by setting the "nagios_level" field to one
   of "OK", "WARNING", "CRITICAL", or "UNKNOWN"
[source,ruby]
    output{
      if [message] =~ /(error|ERROR|CRITICAL)/ {
        nagios {
          # your config here
        }
      }
    }


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
nagios {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-nagios-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-nagios-commandfile>> |<<,>>|No|`"/var/lib/nagios3/rw/nagios.cmd"`
| <<plugins-outputs-nagios-nagios_level>> |<<string,string>>, one of `["0", "1", "2", "3"]`|No|`"2"`
| <<plugins-outputs-nagios-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-nagios-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-nagios-commandfile]]
===== `commandfile` 

  <li> Value type is <<string,string>>
  * Default value is `"/var/lib/nagios3/rw/nagios.cmd"`

The full path to your Nagios command file.

[[plugins-outputs-nagios-nagios_level]]
===== `nagios_level` 

  * Value can be any of: `0`, `1`, `2`, `3`
  * Default value is `"2"`

The Nagios check level. Should be one of 0=OK, 1=WARNING, 2=CRITICAL,
3=UNKNOWN. Defaults to 2 - CRITICAL.

[[plugins-outputs-nagios-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


