[[plugins-outputs-nagios]]
=== nagios

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-output-nagios/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



The Nagios output is used for sending passive check results to Nagios via the
Nagios command file. This output currently supports Nagios 3.

For this output to work, your event _must_ have the following Logstash event fields:

 * `nagios_host`
 * `nagios_service`

These Logstash event fields are supported, but optional:

 * `nagios_annotation`
 * `nagios_level` (overrides `nagios_level` configuration option)

There are two configuration options:

 * `commandfile` - The location of the Nagios external command file. Defaults
   to '/var/lib/nagios3/rw/nagios.cmd'
 * `nagios_level` - Specifies the level of the check to be sent. Defaults to
   CRITICAL and can be overriden by setting the "nagios_level" field to one
   of "OK", "WARNING", "CRITICAL", or "UNKNOWN"
[source,ruby]
    output{
      if [message] =~ /(error|ERROR|CRITICAL)/ {
        nagios {
          # your config here
        }
      }
    }


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
nagios {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-nagios-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-nagios-commandfile>> |<<,>>|No|`"/var/lib/nagios3/rw/nagios.cmd"`
| <<plugins-outputs-nagios-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-nagios-id>> |<<string,string>>|No|
| <<plugins-outputs-nagios-nagios_level>> |<<string,string>>, one of `["0", "1", "2", "3"]`|No|`"2"`
| <<plugins-outputs-nagios-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-nagios-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-nagios-commandfile]]
===== `commandfile` 

  * Value type is <<string,string>>
  * Default value is `"/var/lib/nagios3/rw/nagios.cmd"`

The full path to your Nagios command file.

[[plugins-outputs-nagios-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-nagios-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-nagios-nagios_level]]
===== `nagios_level` 

  * Value can be any of: `0`, `1`, `2`, `3`
  * Default value is `"2"`

The Nagios check level. Should be one of 0=OK, 1=WARNING, 2=CRITICAL,
3=UNKNOWN. Defaults to 2 - CRITICAL.

[[plugins-outputs-nagios-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


