[[plugins-outputs-nagios_nsca]]
=== nagios_nsca



The nagios_nsca output is used for sending passive check results to Nagios
through the NSCA protocol.

This is useful if your Nagios server is not the same as the source host from
where you want to send logs or alerts. If you only have one server, this
output is probably overkill # for you, take a look at the 'nagios' output
instead.

Here is a sample config using the nagios_nsca output:
[source,ruby]
    output {
      nagios_nsca {
        # specify the hostname or ip of your nagios server
        host => "nagios.example.com"

        # specify the port to connect to
        port => 5667
      }
    }

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
nagios_nsca {
    nagios_status => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-nagios_nsca-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-nagios_nsca-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-nagios_nsca-message_format>> |<<string,string>>|No|`"%{@timestamp} %{host}: %{message}"`
| <<plugins-outputs-nagios_nsca-nagios_host>> |<<string,string>>|No|`"%{host}"`
| <<plugins-outputs-nagios_nsca-nagios_service>> |<<string,string>>|No|`"LOGSTASH"`
| <<plugins-outputs-nagios_nsca-nagios_status>> |<<string,string>>|Yes|
| <<plugins-outputs-nagios_nsca-port>> |<<number,number>>|No|`5667`
| <<plugins-outputs-nagios_nsca-send_nsca_bin>> |a valid filesystem path|No|`"/usr/sbin/send_nsca"`
| <<plugins-outputs-nagios_nsca-send_nsca_config>> |a valid filesystem path|No|
| <<plugins-outputs-nagios_nsca-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-nagios_nsca-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-nagios_nsca-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-nagios_nsca-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The nagios host or IP to send logs to. It should have a NSCA daemon running.

[[plugins-outputs-nagios_nsca-message_format]]
===== `message_format` 

  * Value type is <<string,string>>
  * Default value is `"%{@timestamp} %{host}: %{message}"`

The format to use when writing events to nagios. This value
supports any string and can include `%{name}` and other dynamic
strings.

[[plugins-outputs-nagios_nsca-nagios_host]]
===== `nagios_host` 

  * Value type is <<string,string>>
  * Default value is `"%{host}"`

The nagios 'host' you want to submit a passive check result to. This
parameter accepts interpolation, e.g. you can use `@source_host` or other
logstash internal variables.

[[plugins-outputs-nagios_nsca-nagios_service]]
===== `nagios_service` 

  * Value type is <<string,string>>
  * Default value is `"LOGSTASH"`

The nagios 'service' you want to submit a passive check result to. This
parameter accepts interpolation, e.g. you can use `@source_host` or other
logstash internal variables.

[[plugins-outputs-nagios_nsca-nagios_status]]
===== `nagios_status` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The status to send to nagios. Should be 0 = OK, 1 = WARNING, 2 = CRITICAL, 3 = UNKNOWN

[[plugins-outputs-nagios_nsca-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `5667`

The port where the NSCA daemon on the nagios host listens.

[[plugins-outputs-nagios_nsca-send_nsca_bin]]
===== `send_nsca_bin` 

  * Value type is <<path,path>>
  * Default value is `"/usr/sbin/send_nsca"`

The path to the 'send_nsca' binary on the local host.

[[plugins-outputs-nagios_nsca-send_nsca_config]]
===== `send_nsca_config` 

  * Value type is <<path,path>>
  * There is no default value for this setting.

The path to the send_nsca config file on the local host.
Leave blank if you don't want to provide a config file.

[[plugins-outputs-nagios_nsca-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-nagios_nsca-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-nagios_nsca-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


