[[plugins-outputs-newrelic]]
=== newrelic

NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-newrelic`.


This output sends logstash events to New Relic Insights as custom events.

You can learn more about New Relic Insights here:
https://docs.newrelic.com/docs/insights/new-relic-insights/understanding-insights/new-relic-insights

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
newrelic {
    account_id => ...
    insert_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-newrelic-account_id>> |<<string,string>>|Yes|
| <<plugins-outputs-newrelic-batch>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-newrelic-batch_events>> |<<number,number>>|No|`10`
| <<plugins-outputs-newrelic-batch_timeout>> |<<number,number>>|No|`5`
| <<plugins-outputs-newrelic-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-newrelic-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-newrelic-event_type>> |<<string,string>>|No|`"LogstashEvent"`
| <<plugins-outputs-newrelic-id>> |<<string,string>>|No|
| <<plugins-outputs-newrelic-insert_key>> |<<string,string>>|Yes|
| <<plugins-outputs-newrelic-proto>> |<<string,string>>|No|`"https"`
| <<plugins-outputs-newrelic-proxy_host>> |<<string,string>>|No|
| <<plugins-outputs-newrelic-proxy_password>> |<<password,password>>|No|`""`
| <<plugins-outputs-newrelic-proxy_port>> |<<number,number>>|No|`80`
| <<plugins-outputs-newrelic-proxy_user>> |<<string,string>>|No|
| <<plugins-outputs-newrelic-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-newrelic-account_id]]
===== `account_id` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your New Relic account ID. This is the 5 or 6-digit number found in the URL when you are logged into New Relic:
https://rpm.newrelic.com/accounts/[account_id]/... 

[[plugins-outputs-newrelic-batch]]
===== `batch` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Batch Processing - all optional
This plugin uses the New Relic Insights REST API to send data.
To make efficient REST API calls, we will buffer a certain number of events before flushing that out to Insights.

[[plugins-outputs-newrelic-batch_events]]
===== `batch_events` 

  * Value type is <<number,number>>
  * Default value is `10`

This setting controls how many events will be buffered before sending a batch of events.

[[plugins-outputs-newrelic-batch_timeout]]
===== `batch_timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

This setting controls how long the output will wait before sending a batch of a events, 
should the minimum specified in batch_events not be met yet.

[[plugins-outputs-newrelic-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-newrelic-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-newrelic-event_type]]
===== `event_type` 

  * Value type is <<string,string>>
  * Default value is `"LogstashEvent"`

The name for your event type. Use alphanumeric characters only.
If left out, your events will be stored under "logstashEvent".

[[plugins-outputs-newrelic-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-newrelic-insert_key]]
===== `insert_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Your Insights Insert Key. You will need to generate one if you haven't already, as described here:
https://docs.newrelic.com/docs/insights/new-relic-insights/adding-querying-data/inserting-custom-events-insights-api#register

[[plugins-outputs-newrelic-proto]]
===== `proto` 

  * Value type is <<string,string>>
  * Default value is `"https"`

Should the log events be sent to Insights over https instead of plain http (typically yes).

[[plugins-outputs-newrelic-proxy_host]]
===== `proxy_host` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Proxy info - all optional
If using a proxy, only proxy_host is required.

[[plugins-outputs-newrelic-proxy_password]]
===== `proxy_password` 

  * Value type is <<password,password>>
  * Default value is `""`

Proxy_password should be left out if connecting to your proxy unauthenticated.

[[plugins-outputs-newrelic-proxy_port]]
===== `proxy_port` 

  * Value type is <<number,number>>
  * Default value is `80`

Proxy_port will default to port 80 if left out.

[[plugins-outputs-newrelic-proxy_user]]
===== `proxy_user` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Proxy_user should be left out if connecting to your proxy unauthenticated.

[[plugins-outputs-newrelic-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


