[[plugins-outputs-opentsdb]]
=== opentsdb



This output allows you to pull metrics from your logs and ship them to
opentsdb. Opentsdb is an open source tool for storing and graphing metrics.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
opentsdb {
    metrics => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-opentsdb-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-opentsdb-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-opentsdb-metrics>> |<<array,array>>|Yes|
| <<plugins-outputs-opentsdb-port>> |<<number,number>>|No|`4242`
| <<plugins-outputs-opentsdb-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-opentsdb-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-opentsdb-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`

Enable debugging.

[[plugins-outputs-opentsdb-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-opentsdb-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The address of the opentsdb server.

[[plugins-outputs-opentsdb-metrics]]
===== `metrics` 

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

The metric(s) to use. This supports dynamic strings like %{source_host}
for metric names and also for values. This is an array field with key
of the metric name, value of the metric value, and multiple tag,values . Example:
[source,ruby]
    [
      "%{host}/uptime",
      %{uptime_1m} " ,
      "hostname" ,
      "%{host}
      "anotherhostname" ,
      "%{host}
    ]

The value will be coerced to a floating point value. Values which cannot be
coerced will zero (0)

[[plugins-outputs-opentsdb-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `4242`

The port to connect on your graphite server.

[[plugins-outputs-opentsdb-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-opentsdb-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-opentsdb-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


