[[plugins-outputs-opentsdb]]
=== opentsdb

* Version: 3.1.1
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-output-opentsdb/blob/master/CHANGELOG.md#311[Changelog]



NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-opentsdb`.


This output allows you to pull metrics from your logs and ship them to
opentsdb. Opentsdb is an open source tool for storing and graphing metrics.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
opentsdb {
    metrics => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-opentsdb-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-opentsdb-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-opentsdb-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-opentsdb-id>> |<<string,string>>|No|
| <<plugins-outputs-opentsdb-metrics>> |<<array,array>>|Yes|
| <<plugins-outputs-opentsdb-port>> |<<number,number>>|No|`4242`
| <<plugins-outputs-opentsdb-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-opentsdb-codec]]
===== `codec`

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-opentsdb-enable_metric]]
===== `enable_metric`

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-opentsdb-host]]
===== `host`

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The address of the opentsdb server.

[[plugins-outputs-opentsdb-id]]
===== `id`

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-opentsdb-metrics]]
===== `metrics`

  * This is a required setting.
  * Value type is <<array,array>>
  * There is no default value for this setting.

The metric(s) to use. This supports dynamic strings like %{source_host}
for metric names and also for values. This is an array field with key
of the metric name, value of the metric value, and multiple tag,values . Example:
[source,ruby]
    [
      "%{host}/uptime",
      %{uptime_1m} " ,
      "hostname" ,
      "%{host}
      "anotherhostname" ,
      "%{host}
    ]

The value will be coerced to a floating point value. Values which cannot be
coerced will zero (0)

[[plugins-outputs-opentsdb-port]]
===== `port`

  * Value type is <<number,number>>
  * Default value is `4242`

The port to connect on your graphite server.

[[plugins-outputs-opentsdb-workers]]
===== `workers`

  * Value type is <<string,string>>
  * Default value is `1`




