[[plugins-outputs-pagerduty]]
=== pagerduty

The PagerDuty output will send notifications based on pre-configured services
and escalation policies. Logstash can send "trigger", "acknowledge" and "resolve"
event types. In addition, you may configure custom descriptions and event details.
The only required field is the PagerDuty "Service API Key", which can be found on
the service's web page on pagerduty.com. In the default case, the description and
event details will be populated by Logstash, using `message`, `timestamp` and `host` data.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
pagerduty {
    service_key => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-pagerduty-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-pagerduty-description>> |<<string,string>>|No|`"Logstash event for %{host}"`
| <<plugins-outputs-pagerduty-details>> |<<hash,hash>>|No|`{"timestamp"=>"%{@timestamp}", "message"=>"%{message}"}`
| <<plugins-outputs-pagerduty-event_type>> |<<string,string>>, one of `["trigger", "acknowledge", "resolve"]`|No|`"trigger"`
| <<plugins-outputs-pagerduty-incident_key>> |<<string,string>>|No|`"logstash/%{host}/%{type}"`
| <<plugins-outputs-pagerduty-pdurl>> |<<string,string>>|No|`"https://events.pagerduty.com/generic/2010-04-15/create_event.json"`
| <<plugins-outputs-pagerduty-service_key>> |<<string,string>>|Yes|
| <<plugins-outputs-pagerduty-workers>> |<<number,number>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-pagerduty-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-pagerduty-description]]
===== `description` 

  * Value type is <<string,string>>
  * Default value is `"Logstash event for %{host}"`

Custom description

[[plugins-outputs-pagerduty-details]]
===== `details` 

  * Value type is <<hash,hash>>
  * Default value is `{"timestamp"=>"%{@timestamp}", "message"=>"%{message}"}`

The event details. These might be data from the Logstash event fields you wish to include.
Tags are automatically included if detected so there is no need to explicitly add them here.

[[plugins-outputs-pagerduty-event_type]]
===== `event_type` 

  * Value can be any of: `trigger`, `acknowledge`, `resolve`
  * Default value is `"trigger"`

Event type

[[plugins-outputs-pagerduty-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags. Note this check is additional to type and tags.

[[plugins-outputs-pagerduty-incident_key]]
===== `incident_key` 

  * Value type is <<string,string>>
  * Default value is `"logstash/%{host}/%{type}"`

The service key to use. You'll need to set this up in PagerDuty beforehand.

[[plugins-outputs-pagerduty-pdurl]]
===== `pdurl` 

  * Value type is <<string,string>>
  * Default value is `"https://events.pagerduty.com/generic/2010-04-15/create_event.json"`

PagerDuty API URL. You shouldn't need to change this, but is included to allow for flexibility
should PagerDuty iterate the API and Logstash hasn't been updated yet.

[[plugins-outputs-pagerduty-service_key]]
===== `service_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The PagerDuty Service API Key

[[plugins-outputs-pagerduty-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.  Note that if you specify
a type, the event must also match that type.
Optional.

[[plugins-outputs-pagerduty-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-pagerduty-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

