[[plugins-outputs-pagerduty]]
=== pagerduty

* Version: 3.0.3
* Released on: September 15, 2016
* https://github.com/logstash-plugins/logstash-output-pagerduty/blob/master/CHANGELOG.md#303[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

The PagerDuty output will send notifications based on pre-configured services
and escalation policies. Logstash can send "trigger", "acknowledge" and "resolve"
event types. In addition, you may configure custom descriptions and event details.
The only required field is the PagerDuty "Service API Key", which can be found on
the service's web page on pagerduty.com. In the default case, the description and
event details will be populated by Logstash, using `message`, `timestamp` and `host` data.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
pagerduty {
    service_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-pagerduty-codec>> |<<codec,codec>>|No
| <<plugins-outputs-pagerduty-description>> |<<string,string>>|No
| <<plugins-outputs-pagerduty-details>> |<<hash,hash>>|No
| <<plugins-outputs-pagerduty-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-pagerduty-event_type>> |<<string,string>>, one of `["trigger", "acknowledge", "resolve"]`|No
| <<plugins-outputs-pagerduty-id>> |<<string,string>>|No
| <<plugins-outputs-pagerduty-incident_key>> |<<string,string>>|No
| <<plugins-outputs-pagerduty-pdurl>> |<<string,string>>|No
| <<plugins-outputs-pagerduty-service_key>> |<<string,string>>|Yes
| <<plugins-outputs-pagerduty-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-pagerduty-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-pagerduty-description]]
===== `description` 

  * Value type is <<string,string>>
  * Default value is `"Logstash event for %{host}"`

Custom description

[[plugins-outputs-pagerduty-details]]
===== `details` 

  * Value type is <<hash,hash>>
  * Default value is `{"timestamp"=>"%{@timestamp}", "message"=>"%{message}"}`

The event details. These might be data from the Logstash event fields you wish to include.
Tags are automatically included if detected so there is no need to explicitly add them here.

[[plugins-outputs-pagerduty-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-pagerduty-event_type]]
===== `event_type` 

  * Value can be any of: `trigger`, `acknowledge`, `resolve`
  * Default value is `"trigger"`

Event type

[[plugins-outputs-pagerduty-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-pagerduty-incident_key]]
===== `incident_key` 

  * Value type is <<string,string>>
  * Default value is `"logstash/%{host}/%{type}"`

The service key to use. You'll need to set this up in PagerDuty beforehand.

[[plugins-outputs-pagerduty-pdurl]]
===== `pdurl` 

  * Value type is <<string,string>>
  * Default value is `"https://events.pagerduty.com/generic/2010-04-15/create_event.json"`

PagerDuty API URL. You shouldn't need to change this, but is included to allow for flexibility
should PagerDuty iterate the API and Logstash hasn't been updated yet.

[[plugins-outputs-pagerduty-service_key]]
===== `service_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The PagerDuty Service API Key

[[plugins-outputs-pagerduty-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


