[[plugins-outputs-pipe]]
=== pipe

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-output-pipe/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



Pipe output.

Pipe events to stdin of another program. You can use fields from the
event as parts of the command.
WARNING: This feature can cause logstash to fork off multiple children if you are not carefull with per-event commandline.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
pipe {
    command => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-pipe-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-pipe-command>> |<<string,string>>|Yes|
| <<plugins-outputs-pipe-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-pipe-id>> |<<string,string>>|No|
| <<plugins-outputs-pipe-message_format>> |<<string,string>>|No|
| <<plugins-outputs-pipe-ttl>> |<<number,number>>|No|`10`
| <<plugins-outputs-pipe-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-pipe-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-pipe-command]]
===== `command` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Command line to launch and pipe to

[[plugins-outputs-pipe-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-pipe-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-pipe-message_format]]
===== `message_format` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The format to use when writing events to the pipe. This value
supports any string and can include `%{name}` and other dynamic
strings.

If this setting is omitted, the full json representation of the
event will be written as a single line.

[[plugins-outputs-pipe-ttl]]
===== `ttl` 

  * Value type is <<number,number>>
  * Default value is `10`

Close pipe that hasn't been used for TTL seconds. -1 or 0 means never close.

[[plugins-outputs-pipe-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


