[[plugins-outputs-pipe]]
=== pipe

Pipe output.

Pipe events to stdin of another program. You can use fields from the
event as parts of the command.
WARNING: This feature can cause logstash to fork off multiple children if you are not carefull with per-event commandline.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
pipe {
    command => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-pipe-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-pipe-command>> |<<string,string>>|Yes|
| <<plugins-outputs-pipe-message_format>> |<<string,string>>|No|
| <<plugins-outputs-pipe-ttl>> |<<number,number>>|No|`10`
| <<plugins-outputs-pipe-workers>> |<<number,number>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-pipe-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-pipe-command]]
===== `command` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Command line to launch and pipe to

[[plugins-outputs-pipe-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags. Note this check is additional to type and tags.

[[plugins-outputs-pipe-message_format]]
===== `message_format` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The format to use when writing events to the pipe. This value
supports any string and can include `%{name}` and other dynamic
strings.

If this setting is omitted, the full json representation of the
event will be written as a single line.

[[plugins-outputs-pipe-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.  Note that if you specify
a type, the event must also match that type.
Optional.

[[plugins-outputs-pipe-ttl]]
===== `ttl` 

  * Value type is <<number,number>>
  * Default value is `10`

Close pipe that hasn't been used for TTL seconds. -1 or 0 means never close.

[[plugins-outputs-pipe-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-pipe-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

