[[plugins-outputs-redis]]
=== redis

* Version: 3.0.3
* Released on: October 13, 2016
* https://github.com/logstash-plugins/logstash-output-redis/blob/master/CHANGELOG.md#303[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This output will send events to a Redis queue using RPUSH.
The RPUSH command is supported in Redis v0.0.7+. Using
PUBLISH to a channel requires at least v1.3.8+.
While you may be able to make these Redis versions work,
the best performance and stability will be found in more
recent stable versions.  Versions 2.6.0+ are recommended.

For more information, see http://redis.io/[the Redis homepage]


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
redis {
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-redis-batch>> |<<boolean,boolean>>|No
| <<plugins-outputs-redis-batch_events>> |<<number,number>>|No
| <<plugins-outputs-redis-batch_timeout>> |<<number,number>>|No
| <<plugins-outputs-redis-codec>> |<<codec,codec>>|No
| <<plugins-outputs-redis-congestion_interval>> |<<number,number>>|No
| <<plugins-outputs-redis-congestion_threshold>> |<<number,number>>|No
| <<plugins-outputs-redis-data_type>> |<<string,string>>, one of `["list", "channel"]`|No
| <<plugins-outputs-redis-db>> |<<number,number>>|No
| <<plugins-outputs-redis-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-redis-host>> |<<array,array>>|No
| <<plugins-outputs-redis-id>> |<<string,string>>|No
| <<plugins-outputs-redis-key>> |<<string,string>>|No
| <<plugins-outputs-redis-password>> |<<password,password>>|No
| <<plugins-outputs-redis-port>> |<<number,number>>|No
| <<plugins-outputs-redis-reconnect_interval>> |<<number,number>>|No
| <<plugins-outputs-redis-shuffle_hosts>> |<<boolean,boolean>>|No
| <<plugins-outputs-redis-timeout>> |<<number,number>>|No
| <<plugins-outputs-redis-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-redis-batch]]
===== `batch` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Set to true if you want Redis to batch up values and send 1 RPUSH command
instead of one command per value to push on the list.  Note that this only
works with `data_type="list"` mode right now.

If true, we send an RPUSH every "batch_events" events or
"batch_timeout" seconds (whichever comes first).
Only supported for `data_type` is "list".

[[plugins-outputs-redis-batch_events]]
===== `batch_events` 

  * Value type is <<number,number>>
  * Default value is `50`

If batch is set to true, the number of events we queue up for an RPUSH.

[[plugins-outputs-redis-batch_timeout]]
===== `batch_timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

If batch is set to true, the maximum amount of time between RPUSH commands
when there are pending events to flush.

[[plugins-outputs-redis-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-redis-congestion_interval]]
===== `congestion_interval` 

  * Value type is <<number,number>>
  * Default value is `1`

How often to check for congestion. Default is one second.
Zero means to check on every event.

[[plugins-outputs-redis-congestion_threshold]]
===== `congestion_threshold` 

  * Value type is <<number,number>>
  * Default value is `0`

In case Redis `data_type` is `list` and has more than `@congestion_threshold` items,
block until someone consumes them and reduces congestion, otherwise if there are
no consumers Redis will run out of memory, unless it was configured with OOM protection.
But even with OOM protection, a single Redis list can block all other users of Redis,
until Redis CPU consumption reaches the max allowed RAM size.
A default value of 0 means that this limit is disabled.
Only supported for `list` Redis `data_type`.

[[plugins-outputs-redis-data_type]]
===== `data_type` 

  * Value can be any of: `list`, `channel`
  * There is no default value for this setting.

Either list or channel.  If `redis_type` is list, then we will set
RPUSH to key. If `redis_type` is channel, then we will PUBLISH to `key`.

[[plugins-outputs-redis-db]]
===== `db` 

  * Value type is <<number,number>>
  * Default value is `0`

The Redis database number.

[[plugins-outputs-redis-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-redis-host]]
===== `host` 

  * Value type is <<array,array>>
  * Default value is `["127.0.0.1"]`

The hostname(s) of your Redis server(s). Ports may be specified on any
hostname, which will override the global port config.
If the hosts list is an array, Logstash will pick one random host to connect to,
if that host is disconnected it will then pick another.

For example:
[source,ruby]
    "127.0.0.1"
    ["127.0.0.1", "127.0.0.2"]
    ["127.0.0.1:6380", "127.0.0.1"]

[[plugins-outputs-redis-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-redis-key]]
===== `key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of a Redis list or channel. Dynamic names are
valid here, for example `logstash-%{type}`.

[[plugins-outputs-redis-name]]
===== `name`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `"default"`

Name is used for logging in case there are multiple instances.

[[plugins-outputs-redis-password]]
===== `password` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

Password to authenticate with.  There is no authentication by default.

[[plugins-outputs-redis-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `6379`

The default port to connect on. Can be overridden on any hostname.

[[plugins-outputs-redis-queue]]
===== `queue`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the Redis queue (we'll use RPUSH on this). Dynamic names are
valid here, for example `logstash-%{type}`

[[plugins-outputs-redis-reconnect_interval]]
===== `reconnect_interval` 

  * Value type is <<number,number>>
  * Default value is `1`

Interval for reconnecting to failed Redis connections

[[plugins-outputs-redis-shuffle_hosts]]
===== `shuffle_hosts` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Shuffle the host list during Logstash startup.

[[plugins-outputs-redis-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

Redis initial connection timeout in seconds.

[[plugins-outputs-redis-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

