[[plugins-outputs-riak]]
=== riak

* Version: 3.0.0
* Released on: 2016-09-10
* https://github.com/logstash-plugins/logstash-output-riak/blob/master/CHANGELOG.md#300[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4


NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-riak`.


Riak is a distributed k/v store from Basho.
It's based on the Dynamo model.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
riak {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-riak-bucket>> |<<array,array>>|No|`["logstash-%{+YYYY.MM.dd}"]`
| <<plugins-outputs-riak-bucket_props>> |<<hash,hash>>|No|
| <<plugins-outputs-riak-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-riak-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-riak-enable_search>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-riak-enable_ssl>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-riak-id>> |<<string,string>>|No|
| <<plugins-outputs-riak-indices>> |<<array,array>>|No|
| <<plugins-outputs-riak-key_name>> |<<string,string>>|No|
| <<plugins-outputs-riak-nodes>> |<<hash,hash>>|No|`{"localhost"=>"8098"}`
| <<plugins-outputs-riak-proto>> |<<string,string>>, one of `["http", "pb"]`|No|`"http"`
| <<plugins-outputs-riak-ssl_opts>> |<<hash,hash>>|No|
| <<plugins-outputs-riak-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-riak-bucket]]
===== `bucket` 

  * Value type is <<array,array>>
  * Default value is `["logstash-%{+YYYY.MM.dd}"]`

The bucket name to write events to
Expansion is supported here as values are 
passed through event.sprintf
Multiple buckets can be specified here
but any bucket-specific settings defined
apply to ALL the buckets.

[[plugins-outputs-riak-bucket_props]]
===== `bucket_props` 

  * Value type is <<hash,hash>>
  * There is no default value for this setting.

Bucket properties (NYI)
Logstash hash of properties for the bucket
i.e.
[source,ruby]
    bucket_props => {
        "r" => "one"
        "w" => "one"
        "dw", "one
     }
or
[source,ruby]
    bucket_props => { "n_val" => "3" }
Properties will be passed as-is

[[plugins-outputs-riak-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-riak-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-riak-enable_search]]
===== `enable_search` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Search
Enable search on the bucket defined above

[[plugins-outputs-riak-enable_ssl]]
===== `enable_ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

SSL
Enable SSL

[[plugins-outputs-riak-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-riak-indices]]
===== `indices` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Indices
Array of fields to add 2i on
e.g.
[source,ruby]
    `indices => ["source_host", "type"]
Off by default as not everyone runs eleveldb

[[plugins-outputs-riak-key_name]]
===== `key_name` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The event key name
variables are valid here.

Choose this carefully. Best to let riak decide.

[[plugins-outputs-riak-nodes]]
===== `nodes` 

  * Value type is <<hash,hash>>
  * Default value is `{"localhost"=>"8098"}`

The nodes of your Riak cluster
This can be a single host or
a Logstash hash of node/port pairs
e.g
[source,ruby]
    {
        "node1" => "8098"
        "node2" => "8098"
    }

[[plugins-outputs-riak-proto]]
===== `proto` 

  * Value can be any of: `http`, `pb`
  * Default value is `"http"`

The protocol to use
HTTP or ProtoBuf
Applies to ALL backends listed above
No mix and match

[[plugins-outputs-riak-ssl_opts]]
===== `ssl_opts` 

  * Value type is <<hash,hash>>
  * There is no default value for this setting.

SSL Options
Options for SSL connections
Only applied if SSL is enabled
Logstash hash that maps to the riak-client options
here: https://github.com/basho/riak-ruby-client/wiki/Connecting-to-Riak
You'll likely want something like this:

[source, ruby]
    ssl_opts => {
       "pem" => "/etc/riak.pem"
       "ca_path" => "/usr/share/certificates"
    }

Per the riak client docs, the above sample options
will turn on SSL `VERIFY_PEER`

[[plugins-outputs-riak-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


