[[plugins-outputs-riemann]]
=== riemann


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-riemann`.


Riemann is a network event stream processing system.

While Riemann is very similar conceptually to Logstash, it has
much more in terms of being a monitoring system replacement.

Riemann is used in Logstash much like statsd or other metric-related
outputs

You can learn about Riemann here:

* http://riemann.io/
You can see the author talk about it here:
* http://vimeo.com/38377415


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
riemann {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-riemann-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-riemann-debug>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-riemann-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-riemann-map_fields>> |<<boolean,boolean>>|No|`false`
| <<plugins-outputs-riemann-port>> |<<number,number>>|No|`5555`
| <<plugins-outputs-riemann-protocol>> |<<string,string>>, one of `["tcp", "udp"]`|No|`"tcp"`
| <<plugins-outputs-riemann-riemann_event>> |<<hash,hash>>|No|
| <<plugins-outputs-riemann-sender>> |<<string,string>>|No|`"%{host}"`
| <<plugins-outputs-riemann-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-riemann-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-riemann-debug]]
===== `debug` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`


Enable debugging output?

[[plugins-outputs-riemann-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The address of the Riemann server.

[[plugins-outputs-riemann-map_fields]]
===== `map_fields` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

If set to true automatically map all logstash defined fields to riemann event fields.
All nested logstash fields will be mapped to riemann fields containing all parent keys
separated by dots and the deepest value.

As an example, the logstash event:
[source,ruby]
   {
     "@timestamp":"2013-12-10T14:36:26.151+0000",
     "@version": 1,
     "message":"log message",
     "host": "host.domain.com",
     "nested_field": {
                       "key": "value"
                     }
   }
Is mapped to this riemann event:
[source,ruby]
  {
    :time 1386686186,
    :host host.domain.com,
    :message log message,
    :nested_field.key value
  }

It can be used in conjunction with or independent of the riemann_event option.
When used with the riemann_event any duplicate keys receive their value from
riemann_event instead of the logstash event itself.

[[plugins-outputs-riemann-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `5555`

The port to connect to on your Riemann server.

[[plugins-outputs-riemann-protocol]]
===== `protocol` 

  * Value can be any of: `tcp`, `udp`
  * Default value is `"tcp"`

The protocol to use
UDP is non-blocking
TCP is blocking

Logstash's default output behaviour
is to never lose events
As such, we use tcp as default here

[[plugins-outputs-riemann-riemann_event]]
===== `riemann_event` 

  * Value type is <<hash,hash>>
  * There is no default value for this setting.

A Hash to set Riemann event fields
(http://riemann.io/concepts.html).

The following event fields are supported:
`description`, `state`, `metric`, `ttl`, `service`

Tags found on the Logstash event will automatically be added to the
Riemann event.

Any other field set here will be passed to Riemann as an event attribute.

Example:
[source,ruby]
    riemann {
        riemann_event => {
            "metric"  => "%{metric}"
            "service" => "%{service}"
        }
    }

`metric` and `ttl` values will be coerced to a floating point value.
Values which cannot be coerced will zero (0.0).

`description`, by default, will be set to the event message
but can be overridden here.

[[plugins-outputs-riemann-sender]]
===== `sender` 

  * Value type is <<string,string>>
  * Default value is `"%{host}"`

The name of the sender.
This sets the `host` value
in the Riemann event

[[plugins-outputs-riemann-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


