[[plugins-outputs-sns]]
=== sns



SNS output.

Send events to Amazon's Simple Notification Service, a hosted pub/sub
framework.  It supports various subscription types, including email, HTTP/S, SMS, and SQS.

For further documentation about the service see:

  http://docs.amazonwebservices.com/sns/latest/api/

This plugin looks for the following fields on events it receives:

 * `sns` - If no ARN is found in the configuration file, this will be used as
 the ARN to publish.
 * `sns_subject` - The subject line that should be used.
 Optional. The "%{host}" will be used if `sns_subject` is not present. The subject
 will be truncated to 100 characters. If `sns_subject` is set to a non-string value a JSON version of that value will be saved.
 * `sns_message` - Optional string of message to be sent. If this is set to a non-string value it will be encoded with the specified `codec`. If this is not set the entire event will be encoded with the codec.
 with the @message truncated so that the length of the JSON fits in
 `32768` bytes.

## Upgrading to 2.0.0

This plugin used to have a `format` option for controlling the encoding of messages prior to being sent to SNS.
This plugin now uses the logstash standard https://www.elastic.co/guide/en/logstash/current/configuration.html#codec[codec] option for encoding instead.
If you want the same 'plain' format as the v0/1 codec (`format => "plain"`) use `codec => "s3_plain"`.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
sns {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-sns-access_key_id>> |<<string,string>>|No|
| <<plugins-outputs-sns-arn>> |<<string,string>>|No|
| <<plugins-outputs-sns-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-outputs-sns-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-sns-proxy_uri>> |<<string,string>>|No|
| <<plugins-outputs-sns-publish_boot_message_arn>> |<<string,string>>|No|
| <<plugins-outputs-sns-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"]`|No|`"us-east-1"`
| <<plugins-outputs-sns-secret_access_key>> |<<string,string>>|No|
| <<plugins-outputs-sns-session_token>> |<<string,string>>|No|
| <<plugins-outputs-sns-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-sns-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-sns-arn]]
===== `arn` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Optional ARN to send messages to. If you do not set this you must
include the `sns` field in your events to set the ARN on a per-message basis!

[[plugins-outputs-sns-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-sns-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-sns-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-sns-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-sns-publish_boot_message_arn]]
===== `publish_boot_message_arn` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

When an ARN for an SNS topic is specified here, the message
"Logstash successfully booted" will be sent to it when this plugin
is registered.

Example: arn:aws:sns:us-east-1:770975001275:logstash-testing


[[plugins-outputs-sns-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`
  * Default value is `"us-east-1"`



[[plugins-outputs-sns-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-sns-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.



[[plugins-outputs-sns-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-sns-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-sns-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


