[[plugins-outputs-solr_http]]
=== solr_http


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-output-solr_http`.


This output lets you index&store your logs in Solr. If you want to get
started quickly you should use version 4.4 or above in schemaless mode,
which will try and guess your fields automatically. To turn that on,
you can use the example included in the Solr archive:
[source,shell]
    tar zxf solr-4.4.0.tgz
    cd example
    mv solr solr_ #back up the existing sample conf
    cp -r example-schemaless/solr/ .  #put the schemaless conf in place
    java -jar start.jar   #start Solr

You can learn more at https://lucene.apache.org/solr/[the Solr home page]

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
solr_http {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-solr_http-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-solr_http-document_id>> |<<string,string>>|No|`nil`
| <<plugins-outputs-solr_http-flush_size>> |<<number,number>>|No|`100`
| <<plugins-outputs-solr_http-idle_flush_time>> |<<number,number>>|No|`1`
| <<plugins-outputs-solr_http-solr_url>> |<<string,string>>|No|`"http://localhost:8983/solr"`
| <<plugins-outputs-solr_http-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-solr_http-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-solr_http-document_id]]
===== `document_id` 

  * Value type is <<string,string>>
  * Default value is `nil`

Solr document ID for events. You'd typically have a variable here, like
'%{foo}' so you can assign your own IDs

[[plugins-outputs-solr_http-flush_size]]
===== `flush_size` 

  * Value type is <<number,number>>
  * Default value is `100`

Number of events to queue up before writing to Solr

[[plugins-outputs-solr_http-idle_flush_time]]
===== `idle_flush_time` 

  * Value type is <<number,number>>
  * Default value is `1`

Amount of time since the last flush before a flush is done even if
the number of buffered events is smaller than flush_size

[[plugins-outputs-solr_http-solr_url]]
===== `solr_url` 

  * Value type is <<string,string>>
  * Default value is `"http://localhost:8983/solr"`

URL used to connect to Solr

[[plugins-outputs-solr_http-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


