[[plugins-outputs-sqs]]
=== sqs

NOTE: This is a community-maintained plugin!

Push events to an Amazon Web Services Simple Queue Service (SQS) queue.

SQS is a simple, scalable queue system that is part of the 
Amazon Web Services suite of tools.

Although SQS is similar to other queuing systems like AMQP, it
uses a custom API and requires that you have an AWS account.
See http://aws.amazon.com/sqs/ for more details on how SQS works,
what the pricing schedule looks like and how to setup a queue.

To use this plugin, you *must*:

 * Have an AWS account
 * Setup an SQS queue
 * Create an identify that has access to publish messages to the queue.

The "consumer" identity must have the following permissions on the queue:

 * sqs:ChangeMessageVisibility
 * sqs:ChangeMessageVisibilityBatch
 * sqs:GetQueueAttributes
 * sqs:GetQueueUrl
 * sqs:ListQueues
 * sqs:SendMessage
 * sqs:SendMessageBatch

Typically, you should setup an IAM policy, create a user and apply the IAM policy to the user.
A sample policy is as follows:
[source,ruby]
     {
       "Statement": [
         {
           "Sid": "Stmt1347986764948",
           "Action": [
             "sqs:ChangeMessageVisibility",
             "sqs:ChangeMessageVisibilityBatch",
             "sqs:DeleteMessage",
             "sqs:DeleteMessageBatch",
             "sqs:GetQueueAttributes",
             "sqs:GetQueueUrl",
             "sqs:ListQueues",
             "sqs:ReceiveMessage"
           ],
           "Effect": "Allow",
           "Resource": [
             "arn:aws:sqs:us-east-1:200850199751:Logstash"
           ]
         }
       ]
     }

See http://aws.amazon.com/iam/ for more details on setting up AWS identities.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
sqs {
    queue => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-sqs-access_key_id>> |<<string,string>>|No|
| <<plugins-outputs-sqs-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-outputs-sqs-batch>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-sqs-batch_events>> |<<number,number>>|No|`10`
| <<plugins-outputs-sqs-batch_timeout>> |<<number,number>>|No|`5`
| <<plugins-outputs-sqs-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-sqs-proxy_uri>> |<<string,string>>|No|
| <<plugins-outputs-sqs-queue>> |<<string,string>>|Yes|
| <<plugins-outputs-sqs-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "sa-east-1", "us-gov-west-1", "cn-north-1"]`|No|`"us-east-1"`
| <<plugins-outputs-sqs-secret_access_key>> |<<string,string>>|No|
| <<plugins-outputs-sqs-session_token>> |<<string,string>>|No|
| <<plugins-outputs-sqs-use_ssl>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-sqs-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-sqs-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order:

1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config
2. External credentials file specified by `aws_credentials_file`
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
5. IAM Instance Profile (available when running inside EC2)

[[plugins-outputs-sqs-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

[source,ruby]
----------------------------------
 :access_key_id: "12345"
 :secret_access_key: "54321"
----------------------------------

[[plugins-outputs-sqs-batch]]
===== `batch` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Set to true if you want send messages to SQS in batches with `batch_send`
from the amazon sdk

[[plugins-outputs-sqs-batch_events]]
===== `batch_events` 

  * Value type is <<number,number>>
  * Default value is `10`

If `batch` is set to true, the number of events we queue up for a `batch_send`.

[[plugins-outputs-sqs-batch_timeout]]
===== `batch_timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

If `batch` is set to true, the maximum amount of time between `batch_send` commands when there are pending events to flush.

[[plugins-outputs-sqs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-sqs-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-outputs-sqs-queue]]
===== `queue` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of SQS queue to push messages into. Note that this is just the name of the queue, not the URL or ARN.

[[plugins-outputs-sqs-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`
  * Default value is `"us-east-1"`



[[plugins-outputs-sqs-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-outputs-sqs-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Session token for temporary credentials

[[plugins-outputs-sqs-use_ssl]]
===== `use_ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`



[[plugins-outputs-sqs-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


