[[plugins-outputs-sqs]]
=== sqs

* Version: 4.0.1
* Released on: February 15, 2017
* https://github.com/logstash-plugins/logstash-output-sqs/blob/master/CHANGELOG.md#401[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

Push events to an Amazon Web Services (AWS) Simple Queue Service (SQS) queue.

SQS is a simple, scalable queue system that is part of the Amazon Web
Services suite of tools. Although SQS is similar to other queuing systems
such as Advanced Message Queuing Protocol (AMQP), it uses a custom API and
requires that you have an AWS account. See http://aws.amazon.com/sqs/ for
more details on how SQS works, what the pricing schedule looks like and how
to setup a queue.

The "consumer" identity must have the following permissions on the queue:

  * `sqs:GetQueueUrl`
  * `sqs:SendMessage`
  * `sqs:SendMessageBatch`

Typically, you should setup an IAM policy, create a user and apply the IAM
policy to the user. See http://aws.amazon.com/iam/ for more details on
setting up AWS identities. A sample policy is as follows:

[source,json]
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sqs:GetQueueUrl",
        "sqs:SendMessage",
        "sqs:SendMessageBatch"
      ],
      "Resource": "arn:aws:sqs:us-east-1:123456789012:my-sqs-queue"
    }
  ]
}

==== Batch Publishing
This output publishes messages to SQS in batches in order to optimize event
throughput and increase performance. This is done using the
[`SendMessageBatch`](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html)
API. When publishing messages to SQS in batches, the following service limits
must be respected (see
[Limits in Amazon SQS](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/limits-messages.html)):

  * The maximum allowed individual message size is 256KiB.
  * The maximum total payload size (i.e. the sum of the sizes of all
    individual messages within a batch) is also 256KiB.

This plugin will dynamically adjust the size of the batch published to SQS in
order to ensure that the total payload size does not exceed 256KiB.

WARNING: This output cannot currently handle messages larger than 256KiB. Any
single message exceeding this size will be dropped.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
sqs {
    queue => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-sqs-access_key_id>> |<<string,string>>|No
| <<plugins-outputs-sqs-aws_credentials_file>> |<<string,string>>|No
| <<plugins-outputs-sqs-batch_events>> |<<number,number>>|No
| <<plugins-outputs-sqs-codec>> |<<codec,codec>>|No
| <<plugins-outputs-sqs-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-sqs-id>> |<<string,string>>|No
| <<plugins-outputs-sqs-message_max_size>> |<<bytes,bytes>>|No
| <<plugins-outputs-sqs-proxy_uri>> |<<string,string>>|No
| <<plugins-outputs-sqs-queue>> |<<string,string>>|Yes
| <<plugins-outputs-sqs-region>> |<<string,string>>, one of `["us-east-1", "us-east-2", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "eu-west-2", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1", "ca-central-1"]`|No
| <<plugins-outputs-sqs-secret_access_key>> |<<string,string>>|No
| <<plugins-outputs-sqs-session_token>> |<<string,string>>|No
| <<plugins-outputs-sqs-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-sqs-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order:

1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config
2. External credentials file specified by `aws_credentials_file`
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
5. IAM Instance Profile (available when running inside EC2)

[[plugins-outputs-sqs-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

[source,ruby]
----------------------------------
    :access_key_id: "12345"
    :secret_access_key: "54321"
----------------------------------


[[plugins-outputs-sqs-batch]]
===== `batch`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `true`

Set to `true` to send messages to SQS in batches (with the
`SendMessageBatch` API) or `false` to send messages to SQS individually
(with the `SendMessage` API). The size of the batch is configurable via
`batch_events`.

[[plugins-outputs-sqs-batch_events]]
===== `batch_events` 

  * Value type is <<number,number>>
  * Default value is `10`

The number of events to be sent in each batch. Set this to `1` to disable
the batch sending of messages.

[[plugins-outputs-sqs-batch_timeout]]
===== `batch_timeout`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<number,number>>
  * There is no default value for this setting.



[[plugins-outputs-sqs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-sqs-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-sqs-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-sqs-message_max_size]]
===== `message_max_size` 

  * Value type is <<bytes,bytes>>
  * Default value is `"256KiB"`

The maximum number of bytes for any message sent to SQS. Messages exceeding
this size will be dropped. See
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/limits-messages.html.

[[plugins-outputs-sqs-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-outputs-sqs-queue]]
===== `queue` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The name of the target SQS queue. Note that this is just the name of the
queue, not the URL or ARN.

[[plugins-outputs-sqs-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-east-2`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `eu-west-2`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `ap-northeast-2`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`, `ap-south-1`, `ca-central-1`
  * Default value is `"us-east-1"`

The AWS Region

[[plugins-outputs-sqs-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-outputs-sqs-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Session token for temporary credential

[[plugins-outputs-sqs-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

