[[plugins-outputs-sqs]]
=== sqs

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-output-sqs/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



Push events to an Amazon Web Services Simple Queue Service (SQS) queue.

SQS is a simple, scalable queue system that is part of the 
Amazon Web Services suite of tools.

Although SQS is similar to other queuing systems like AMQP, it
uses a custom API and requires that you have an AWS account.
See http://aws.amazon.com/sqs/ for more details on how SQS works,
what the pricing schedule looks like and how to setup a queue.

To use this plugin, you *must*:

 * Have an AWS account
 * Setup an SQS queue
 * Create an identify that has access to publish messages to the queue.

The "consumer" identity must have the following permissions on the queue:

 * sqs:ChangeMessageVisibility
 * sqs:ChangeMessageVisibilityBatch
 * sqs:GetQueueAttributes
 * sqs:GetQueueUrl
 * sqs:ListQueues
 * sqs:SendMessage
 * sqs:SendMessageBatch

Typically, you should setup an IAM policy, create a user and apply the IAM policy to the user.
A sample policy is as follows:
[source,ruby]
     {
       "Statement": [
         {
           "Sid": "Stmt1347986764948",
           "Action": [
             "sqs:ChangeMessageVisibility",
             "sqs:ChangeMessageVisibilityBatch",
             "sqs:GetQueueAttributes",
             "sqs:GetQueueUrl",
             "sqs:ListQueues",
             "sqs:SendMessage",
             "sqs:SendMessageBatch"
           ],
           "Effect": "Allow",
           "Resource": [
             "arn:aws:sqs:us-east-1:200850199751:Logstash"
           ]
         }
       ]
     }

See http://aws.amazon.com/iam/ for more details on setting up AWS identities.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
sqs {
    queue => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-sqs-access_key_id>> |<<string,string>>|No|
| <<plugins-outputs-sqs-aws_credentials_file>> |<<string,string>>|No|
| <<plugins-outputs-sqs-batch>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-sqs-batch_events>> |<<number,number>>|No|`10`
| <<plugins-outputs-sqs-batch_timeout>> |<<number,number>>|No|`5`
| <<plugins-outputs-sqs-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-sqs-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-sqs-id>> |<<string,string>>|No|
| <<plugins-outputs-sqs-proxy_uri>> |<<string,string>>|No|
| <<plugins-outputs-sqs-queue>> |<<string,string>>|Yes|
| <<plugins-outputs-sqs-region>> |<<string,string>>, one of `["us-east-1", "us-west-1", "us-west-2", "eu-central-1", "eu-west-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "us-gov-west-1", "cn-north-1", "ap-south-1"]`|No|`"us-east-1"`
| <<plugins-outputs-sqs-secret_access_key>> |<<string,string>>|No|
| <<plugins-outputs-sqs-session_token>> |<<string,string>>|No|
| <<plugins-outputs-sqs-use_ssl>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-sqs-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-sqs-access_key_id]]
===== `access_key_id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

This plugin uses the AWS SDK and supports several ways to get credentials, which will be tried in this order:

1. Static configuration, using `access_key_id` and `secret_access_key` params in logstash plugin config
2. External credentials file specified by `aws_credentials_file`
3. Environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. Environment variables `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY`
5. IAM Instance Profile (available when running inside EC2)

[[plugins-outputs-sqs-aws_credentials_file]]
===== `aws_credentials_file` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Path to YAML file containing a hash of AWS credentials.
This file will only be loaded if `access_key_id` and
`secret_access_key` aren't set. The contents of the
file should look like this:

[source,ruby]
----------------------------------
    :access_key_id: "12345"
    :secret_access_key: "54321"
----------------------------------


[[plugins-outputs-sqs-batch]]
===== `batch` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Set to true if you want send messages to SQS in batches with `batch_send`
from the amazon sdk

[[plugins-outputs-sqs-batch_events]]
===== `batch_events` 

  * Value type is <<number,number>>
  * Default value is `10`

If `batch` is set to true, the number of events we queue up for a `batch_send`.

[[plugins-outputs-sqs-batch_timeout]]
===== `batch_timeout` 

  * Value type is <<number,number>>
  * Default value is `5`

If `batch` is set to true, the maximum amount of time between `batch_send` commands when there are pending events to flush.

[[plugins-outputs-sqs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-sqs-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-sqs-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-sqs-proxy_uri]]
===== `proxy_uri` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

URI to proxy server if required

[[plugins-outputs-sqs-queue]]
===== `queue` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

Name of SQS queue to push messages into. Note that this is just the name of the queue, not the URL or ARN.

[[plugins-outputs-sqs-region]]
===== `region` 

  * Value can be any of: `us-east-1`, `us-west-1`, `us-west-2`, `eu-central-1`, `eu-west-1`, `ap-southeast-1`, `ap-southeast-2`, `ap-northeast-1`, `ap-northeast-2`, `sa-east-1`, `us-gov-west-1`, `cn-north-1`, `ap-south-1`
  * Default value is `"us-east-1"`

The AWS Region

[[plugins-outputs-sqs-secret_access_key]]
===== `secret_access_key` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Secret Access Key

[[plugins-outputs-sqs-session_token]]
===== `session_token` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The AWS Session token for temporary credential

[[plugins-outputs-sqs-use_ssl]]
===== `use_ssl` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Should we require (true) or disable (false) using SSL for communicating with the AWS API
The AWS SDK for Ruby defaults to SSL so we preserve that

[[plugins-outputs-sqs-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


