[[plugins-outputs-statsd]]
=== statsd



statsd is a network daemon for aggregating statistics, such as counters and timers,
and shipping over UDP to backend services, such as Graphite or Datadog.

The most basic coverage of this plugin is that the 'namespace', 'sender', and
'metric' names are combined into the full metric path like so:

    `namespace.sender.metric`

The general idea is that you send statsd count or latency data and every few
seconds it will emit the aggregated values to the backend. Example aggregates are
`average`, `max`, `stddev`, etc.

You can learn about statsd here:

* http://codeascraft.etsy.com/2011/02/15/measure-anything-measure-everything/[Etsy blog post announcing statsd]
* https://github.com/etsy/statsd[statsd on github]

A simple example usage of this is to count HTTP hits by response code; to learn
more about that, check out the ../tutorials/metrics-from-logs[log metrics tutorial]

The default final metric sent to statsd would look like this:

    `namespace.sender.metric`

With regards to this plugin, the default namespace is "logstash", the default sender
is the `${host}` field, and the metric name depends on what is set as the metric name
in the `increment`, `decrement`, `timing`, `count, `set` or `gauge` variable. 


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
statsd {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-statsd-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-statsd-count>> |<<hash,hash>>|No|`{}`
| <<plugins-outputs-statsd-decrement>> |<<array,array>>|No|`[]`
| <<plugins-outputs-statsd-gauge>> |<<hash,hash>>|No|`{}`
| <<plugins-outputs-statsd-host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-statsd-increment>> |<<array,array>>|No|`[]`
| <<plugins-outputs-statsd-namespace>> |<<string,string>>|No|`"logstash"`
| <<plugins-outputs-statsd-port>> |<<number,number>>|No|`8125`
| <<plugins-outputs-statsd-sample_rate>> |<<number,number>>|No|`1`
| <<plugins-outputs-statsd-sender>> |<<string,string>>|No|`"%{host}"`
| <<plugins-outputs-statsd-set>> |<<hash,hash>>|No|`{}`
| <<plugins-outputs-statsd-timing>> |<<hash,hash>>|No|`{}`
| <<plugins-outputs-statsd-workers>> |<<number,number>>|No|`1`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-statsd-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-statsd-count]]
===== `count` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

A count metric. `metric_name => count` as hash

[[plugins-outputs-statsd-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`

Enable debugging.

[[plugins-outputs-statsd-decrement]]
===== `decrement` 

  * Value type is <<array,array>>
  * Default value is `[]`

A decrement metric. Metric names as array.

[[plugins-outputs-statsd-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-statsd-gauge]]
===== `gauge` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

A gauge metric. `metric_name => gauge` as hash.

[[plugins-outputs-statsd-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The address of the statsd server.

[[plugins-outputs-statsd-increment]]
===== `increment` 

  * Value type is <<array,array>>
  * Default value is `[]`

An increment metric. Metric names as array.

[[plugins-outputs-statsd-namespace]]
===== `namespace` 

  * Value type is <<string,string>>
  * Default value is `"logstash"`

The statsd namespace to use for this metric.

[[plugins-outputs-statsd-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `8125`

The port to connect to on your statsd server.

[[plugins-outputs-statsd-sample_rate]]
===== `sample_rate` 

  * Value type is <<number,number>>
  * Default value is `1`

The sample rate for the metric.

[[plugins-outputs-statsd-sender]]
===== `sender` 

  * Value type is <<string,string>>
  * Default value is `"%{host}"`

The name of the sender. Dots will be replaced with underscores.

[[plugins-outputs-statsd-set]]
===== `set` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

A set metric. `metric_name => "string"` to append as hash

[[plugins-outputs-statsd-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-statsd-timing]]
===== `timing` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

A timing metric. `metric_name => duration` as hash

[[plugins-outputs-statsd-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-statsd-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.


