[[plugins-outputs-webhdfs]]
=== webhdfs

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-output-webhdfs/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This plugin sends Logstash events into files in HDFS via
the https://hadoop.apache.org/docs/r1.0.4/webhdfs.html[webhdfs] REST API.

==== Dependencies
This plugin has no dependency on jars from hadoop, thus reducing configuration and compatibility
problems. It uses the webhdfs gem from Kazuki Ohta and TAGOMORI Satoshi (@see: https://github.com/kzk/webhdfs).
Optional dependencies are zlib and snappy gem if you use the compression functionality.

==== Operational Notes
If you get an error like:

    Max write retries reached. Exception: initialize: name or service not known {:level=>:error}

make sure that the hostname of your namenode is resolvable on the host running Logstash. When creating/appending
to a file, webhdfs somtime sends a `307 TEMPORARY_REDIRECT` with the `HOSTNAME` of the machine its running on.

==== Usage
This is an example of Logstash config:

[source,ruby]
----------------------------------
input {
  ...
}
filter {
  ...
}
output {
  webhdfs {
    host => "127.0.0.1"                 # (required)
    port => 50070                       # (optional, default: 50070)
    path => "/user/logstash/dt=%{+YYYY-MM-dd}/logstash-%{+HH}.log"  # (required)
    user => "hue"                       # (required)
  }
}
----------------------------------

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
webhdfs {
    host => ...
    path => ...
    user => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-webhdfs-codec>> |<<codec,codec>>|No
| <<plugins-outputs-webhdfs-compression>> |<<string,string>>, one of `["none", "snappy", "gzip"]`|No
| <<plugins-outputs-webhdfs-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-webhdfs-flush_size>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-host>> |<<string,string>>|Yes
| <<plugins-outputs-webhdfs-id>> |<<string,string>>|No
| <<plugins-outputs-webhdfs-idle_flush_time>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-open_timeout>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-path>> |<<string,string>>|Yes
| <<plugins-outputs-webhdfs-port>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-read_timeout>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-retry_interval>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-retry_known_errors>> |<<boolean,boolean>>|No
| <<plugins-outputs-webhdfs-retry_times>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-single_file_per_thread>> |<<boolean,boolean>>|No
| <<plugins-outputs-webhdfs-snappy_bufsize>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-snappy_format>> |<<string,string>>, one of `["stream", "file"]`|No
| <<plugins-outputs-webhdfs-standby_host>> |<<string,string>>|No
| <<plugins-outputs-webhdfs-standby_port>> |<<number,number>>|No
| <<plugins-outputs-webhdfs-use_httpfs>> |<<boolean,boolean>>|No
| <<plugins-outputs-webhdfs-user>> |<<string,string>>|Yes
| <<plugins-outputs-webhdfs-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-webhdfs-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-webhdfs-compression]]
===== `compression` 

  * Value can be any of: `none`, `snappy`, `gzip`
  * Default value is `"none"`

Compress output. One of ['none', 'snappy', 'gzip']

[[plugins-outputs-webhdfs-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-webhdfs-flush_size]]
===== `flush_size` 

  * Value type is <<number,number>>
  * Default value is `500`

Sending data to webhdfs if event count is above, even if `store_interval_in_secs` is not reached.

[[plugins-outputs-webhdfs-host]]
===== `host` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The server name for webhdfs/httpfs connections.

[[plugins-outputs-webhdfs-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-webhdfs-idle_flush_time]]
===== `idle_flush_time` 

  * Value type is <<number,number>>
  * Default value is `1`

Sending data to webhdfs in x seconds intervals.

[[plugins-outputs-webhdfs-open_timeout]]
===== `open_timeout` 

  * Value type is <<number,number>>
  * Default value is `30`

WebHdfs open timeout, default 30s.

[[plugins-outputs-webhdfs-path]]
===== `path` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The path to the file to write to. Event fields can be used here,
as well as date fields in the joda time format, e.g.:
`/user/logstash/dt=%{+YYYY-MM-dd}/%{@source_host}-%{+HH}.log`

[[plugins-outputs-webhdfs-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `50070`

The server port for webhdfs/httpfs connections.

[[plugins-outputs-webhdfs-read_timeout]]
===== `read_timeout` 

  * Value type is <<number,number>>
  * Default value is `30`

The WebHdfs read timeout, default 30s.

[[plugins-outputs-webhdfs-retry_interval]]
===== `retry_interval` 

  * Value type is <<number,number>>
  * Default value is `0.5`

How long should we wait between retries.

[[plugins-outputs-webhdfs-retry_known_errors]]
===== `retry_known_errors` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Retry some known webhdfs errors. These may be caused by race conditions when appending to same file, etc.

[[plugins-outputs-webhdfs-retry_times]]
===== `retry_times` 

  * Value type is <<number,number>>
  * Default value is `5`

How many times should we retry. If retry_times is exceeded, an error will be logged and the event will be discarded.

[[plugins-outputs-webhdfs-single_file_per_thread]]
===== `single_file_per_thread` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Avoid appending to same file in multiple threads.
This solves some problems with multiple logstash output threads and locked file leases in webhdfs.
If this option is set to true, %{[@metadata][thread_id]} needs to be used in path config settting.

[[plugins-outputs-webhdfs-snappy_bufsize]]
===== `snappy_bufsize` 

  * Value type is <<number,number>>
  * Default value is `32768`

Set snappy chunksize. Only neccessary for stream format. Defaults to 32k. Max is 65536
@see http://code.google.com/p/snappy/source/browse/trunk/framing_format.txt

[[plugins-outputs-webhdfs-snappy_format]]
===== `snappy_format` 

  * Value can be any of: `stream`, `file`
  * Default value is `"stream"`

Set snappy format. One of "stream", "file". Set to stream to be hive compatible.

[[plugins-outputs-webhdfs-standby_host]]
===== `standby_host` 

  * Value type is <<string,string>>
  * Default value is `false`

Standby namenode for ha hdfs.

[[plugins-outputs-webhdfs-standby_port]]
===== `standby_port` 

  * Value type is <<number,number>>
  * Default value is `50070`

Standby namenode port for ha hdfs.

[[plugins-outputs-webhdfs-use_httpfs]]
===== `use_httpfs` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Use httpfs mode if set to true, else webhdfs.

[[plugins-outputs-webhdfs-user]]
===== `user` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The Username for webhdfs.

[[plugins-outputs-webhdfs-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


