[[plugins-outputs-websocket]]
=== websocket

* Version: 3.0.1
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-output-websocket/blob/master/CHANGELOG.md#301[Changelog]



NOTE: This plugin does not ship with Logstash by default, but it is easy to install by running `bin/logstash-plugin install logstash-output-websocket`.


This output runs a websocket server and publishes any
messages to all connected websocket clients.

You can connect to it with ws://<host\>:<port\>/

If no clients are connected, any messages received are ignored.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
websocket {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-websocket-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-websocket-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-outputs-websocket-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-outputs-websocket-id>> |<<string,string>>|No|
| <<plugins-outputs-websocket-port>> |<<number,number>>|No|`3232`
| <<plugins-outputs-websocket-workers>> |<<,>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-websocket-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-websocket-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-websocket-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The address to serve websocket data from

[[plugins-outputs-websocket-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.

[[plugins-outputs-websocket-port]]
===== `port` 

  * Value type is <<number,number>>
  * Default value is `3232`

The port to serve websocket data from

[[plugins-outputs-websocket-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


