[[plugins-outputs-xmpp]]
=== xmpp

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-output-xmpp/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This output allows you ship events over XMPP/Jabber.

This plugin can be used for posting events to humans over XMPP, or you can
use it for PubSub or general message passing for logstash to logstash.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
xmpp {
    message => ...
    password => ...
    user => ...
}
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-outputs-xmpp-codec>> |<<codec,codec>>|No
| <<plugins-outputs-xmpp-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-outputs-xmpp-host>> |<<string,string>>|No
| <<plugins-outputs-xmpp-id>> |<<string,string>>|No
| <<plugins-outputs-xmpp-message>> |<<string,string>>|Yes
| <<plugins-outputs-xmpp-password>> |<<password,password>>|Yes
| <<plugins-outputs-xmpp-rooms>> |<<array,array>>|No
| <<plugins-outputs-xmpp-user>> |<<string,string>>|Yes
| <<plugins-outputs-xmpp-users>> |<<array,array>>|No
| <<plugins-outputs-xmpp-workers>> |<<,>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-xmpp-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-xmpp-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-outputs-xmpp-host]]
===== `host` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The xmpp server to connect to. This is optional. If you omit this setting,
the host on the user/identity is used. (foo.com for user@foo.com)

[[plugins-outputs-xmpp-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-outputs-xmpp-message]]
===== `message` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The message to send. This supports dynamic strings like `%{host}`

[[plugins-outputs-xmpp-password]]
===== `password` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

The xmpp password for the user/identity.

[[plugins-outputs-xmpp-rooms]]
===== `rooms` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

if muc/multi-user-chat required, give the name of the room that
you want to join: room@conference.domain/nick

[[plugins-outputs-xmpp-user]]
===== `user` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The user or resource ID, like foo@example.com.

[[plugins-outputs-xmpp-users]]
===== `users` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

The users to send messages to

[[plugins-outputs-xmpp-workers]]
===== `workers` 

  * Value type is <<string,string>>
  * Default value is `1`

TODO remove this in Logstash 6.0
when we no longer support the :legacy type
This is hacky, but it can only be herne


