[[plugins-outputs-xmpp]]
=== xmpp

This output allows you ship events over XMPP/Jabber.

This plugin can be used for posting events to humans over XMPP, or you can
use it for PubSub or general message passing for logstash to logstash.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
xmpp {
    message => ... 
    password => ... 
    user => ... 
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-xmpp-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-xmpp-host>> |<<string,string>>|No|
| <<plugins-outputs-xmpp-message>> |<<string,string>>|Yes|
| <<plugins-outputs-xmpp-password>> |<<password,password>>|Yes|
| <<plugins-outputs-xmpp-rooms>> |<<array,array>>|No|
| <<plugins-outputs-xmpp-user>> |<<string,string>>|Yes|
| <<plugins-outputs-xmpp-users>> |<<array,array>>|No|
| <<plugins-outputs-xmpp-workers>> |<<number,number>>|No|`1`
|=======================================================================


==== Details

&nbsp;

[[plugins-outputs-xmpp-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-xmpp-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags. Note this check is additional to type and tags.

[[plugins-outputs-xmpp-host]]
===== `host` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

The xmpp server to connect to. This is optional. If you omit this setting,
the host on the user/identity is used. (foo.com for user@foo.com)

[[plugins-outputs-xmpp-message]]
===== `message` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The message to send. This supports dynamic strings like `%{host}`

[[plugins-outputs-xmpp-password]]
===== `password` 

  * This is a required setting.
  * Value type is <<password,password>>
  * There is no default value for this setting.

The xmpp password for the user/identity.

[[plugins-outputs-xmpp-rooms]]
===== `rooms` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

if muc/multi-user-chat required, give the name of the room that
you want to join: room@conference.domain/nick

[[plugins-outputs-xmpp-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.  Note that if you specify
a type, the event must also match that type.
Optional.

[[plugins-outputs-xmpp-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-xmpp-user]]
===== `user` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The user or resource ID, like foo@example.com.

[[plugins-outputs-xmpp-users]]
===== `users` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

The users to send messages to

[[plugins-outputs-xmpp-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

