[[plugins-outputs-zabbix]]
=== zabbix


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-output-zabbix`.


The Zabbix output is used to send item data (key/value pairs) to a Zabbix
server.  The event `@timestamp` will automatically be associated with the
Zabbix item data.

The Zabbix Sender protocol is described at
https://www.zabbix.org/wiki/Docs/protocols/zabbix_sender/2.0
Zabbix uses a kind of nested key/value store.

[source,txt]
    host
      ├── item1
      │     └── value1
      ├── item2
      │     └── value2
      ├── ...
      │     └── ...
      ├── item_n
      │     └── value_n

Each "host" is an identifier, and each item is associated with that host.
Items are typed on the Zabbix side.  You can send numbers as strings and
Zabbix will Do The Right Thing.

In the Zabbix UI, ensure that your hostname matches the value referenced by
`zabbix_host`. Create the item with the key as it appears in the field
referenced by `zabbix_key`.  In the item configuration window, ensure that the
type dropdown is set to Zabbix Trapper. Also be sure to set the type of
information that Zabbix should expect for this item.

This plugin does not currently send in batches.  While it is possible to do
so, this is not supported.  Be careful not to flood your Zabbix server with
too many events per second.

NOTE: This plugin will log a warning if a necessary field is missing. It will
not attempt to resend if Zabbix is down, but will log an error message.

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
zabbix {
    zabbix_host => ...
    zabbix_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-outputs-zabbix-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-outputs-zabbix-timeout>> |<<number,number>>|No|`1`
| <<plugins-outputs-zabbix-workers>> |<<number,number>>|No|`1`
| <<plugins-outputs-zabbix-zabbix_host>> |<<string,string>>|Yes|
| <<plugins-outputs-zabbix-zabbix_key>> |<<string,string>>|Yes|
| <<plugins-outputs-zabbix-zabbix_server_host>> |<<string,string>>|No|`"localhost"`
| <<plugins-outputs-zabbix-zabbix_server_port>> |<<number,number>>|No|`10051`
| <<plugins-outputs-zabbix-zabbix_value>> |<<string,string>>|No|`"message"`
|=======================================================================



==== Details

&nbsp;

[[plugins-outputs-zabbix-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for output data. Output codecs are a convenient method for encoding your data before it leaves the output, without needing a separate filter in your Logstash pipeline.

[[plugins-outputs-zabbix-exclude_tags]]
===== `exclude_tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events without any of these tags.
Optional.

[[plugins-outputs-zabbix-tags]]
===== `tags`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<array,array>>
  * Default value is `[]`

Only handle events with all of these tags.
Optional.

[[plugins-outputs-zabbix-timeout]]
===== `timeout` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of seconds to wait before giving up on a connection to the Zabbix
server. This number should be very small, otherwise delays in delivery of
other outputs could result.

[[plugins-outputs-zabbix-type]]
===== `type`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `""`

The type to act on. If a type is given, then this output will only
act on messages with the same type. See any input plugin's `type`
attribute for more.
Optional.

[[plugins-outputs-zabbix-workers]]
===== `workers` 

  * Value type is <<number,number>>
  * Default value is `1`

The number of workers to use for this output.
Note that this setting may not be useful for all outputs.

[[plugins-outputs-zabbix-zabbix_host]]
===== `zabbix_host` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The field name which holds the Zabbix host name. This can be a sub-field of
the @metadata field.

[[plugins-outputs-zabbix-zabbix_key]]
===== `zabbix_key` 

  * This is a required setting.
  * Value type is <<string,string>>
  * There is no default value for this setting.

The field name which holds the Zabbix key. This can be a sub-field of
the @metadata field.

[[plugins-outputs-zabbix-zabbix_server_host]]
===== `zabbix_server_host` 

  * Value type is <<string,string>>
  * Default value is `"localhost"`

The IP or resolvable hostname where the Zabbix server is running

[[plugins-outputs-zabbix-zabbix_server_port]]
===== `zabbix_server_port` 

  * Value type is <<number,number>>
  * Default value is `10051`

The port on which the Zabbix server is running

[[plugins-outputs-zabbix-zabbix_value]]
===== `zabbix_value` 

  * Value type is <<string,string>>
  * Default value is `"message"`

The field name which holds the value you want to send.


