[[plugins-codecs-cef]]
=== cef


NOTE: This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install logstash-codec-cef`.

Implementation of a Logstash codec for the ArcSight Common Event Format (CEF).
Based on Revision 20 of Implementing ArcSight CEF, dated from June 05, 2013.
https://protect724.hp.com/servlet/JiveServlet/downloadBody/1072-102-6-4697/CommonEventFormat.pdf

&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
cef {
  }
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-codecs-cef-fields>> |<<array,array>>|No|`[]`
| <<plugins-codecs-cef-name>> |<<string,string>>|No|`"Logstash"`
| <<plugins-codecs-cef-product>> |<<string,string>>|No|`"Logstash"`
| <<plugins-codecs-cef-severity>> |<<string,string>>|No|`"6"`
| <<plugins-codecs-cef-signature>> |<<string,string>>|No|`"Logstash"`
| <<plugins-codecs-cef-vendor>> |<<string,string>>|No|`"Elasticsearch"`
| <<plugins-codecs-cef-version>> |<<string,string>>|No|`"1.0"`
|=======================================================================



==== Details

&nbsp;

[[plugins-codecs-cef-fields]]
===== `fields` 

  * Value type is <<array,array>>
  * Default value is `[]`

Fields to be included in CEV extension part as key/value pairs

[[plugins-codecs-cef-name]]
===== `name` 

  * Value type is <<string,string>>
  * Default value is `"Logstash"`

Name field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

[[plugins-codecs-cef-product]]
===== `product` 

  * Value type is <<string,string>>
  * Default value is `"Logstash"`

Device product field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

[[plugins-codecs-cef-sev]]
===== `sev`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * Default value is `"6"`

Deprecated severity field for CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

This field is used only if :severity is unchanged set to the default value.

Defined as field of type string to allow sprintf. The value will be validated
to be an integer in the range from 0 to 10 (including).
All invalid values will be mapped to the default of 6.

[[plugins-codecs-cef-severity]]
===== `severity` 

  * Value type is <<string,string>>
  * Default value is `"6"`

Severity field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

Defined as field of type string to allow sprintf. The value will be validated
to be an integer in the range from 0 to 10 (including).
All invalid values will be mapped to the default of 6.

[[plugins-codecs-cef-signature]]
===== `signature` 

  * Value type is <<string,string>>
  * Default value is `"Logstash"`

Signature ID field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

[[plugins-codecs-cef-vendor]]
===== `vendor` 

  * Value type is <<string,string>>
  * Default value is `"Elasticsearch"`

Device vendor field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.

[[plugins-codecs-cef-version]]
===== `version` 

  * Value type is <<string,string>>
  * Default value is `"1.0"`

Device version field in CEF header. The new value can include `%{foo}` strings
to help you build a new value from other parts of the event.


