[[plugins-codecs-fluent]]
=== fluent

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-codec-fluent/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description

This codec handles fluentd's msgpack schema.

For example, you can receive logs from `fluent-logger-ruby` with:
[source,ruby]
    input {
      tcp {
        codec => fluent
        port => 4000
      }
    }

And from your ruby code in your own application:
[source,ruby]
    logger = Fluent::Logger::FluentLogger.new(nil, :host => "example.log", :port => 4000)
    logger.post("some_tag", { "your" => "data", "here" => "yay!" })

Notes:

* the fluent uses a second-precision time for events, so you will never see
  subsecond precision on events processed by this codec.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
fluent {
  }
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-codecs-fluent-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-codecs-fluent-id>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-codecs-fluent-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-codecs-fluent-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------



