[[plugins-codecs-fluent]]
=== fluent

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-codec-fluent/blob/master/CHANGELOG.md#302[Changelog]
* Compatible: 5.1.1.1, 5.0.0, 2.4.1, 2.4.0, 2.3.4



This codec handles fluentd's msgpack schema.

For example, you can receive logs from `fluent-logger-ruby` with:
[source,ruby]
    input {
      tcp {
        codec => fluent
        port => 4000
      }
    }

And from your ruby code in your own application:
[source,ruby]
    logger = Fluent::Logger::FluentLogger.new(nil, :host => "example.log", :port => 4000)
    logger.post("some_tag", { "your" => "data", "here" => "yay!" })

Notes:

* the fluent uses a second-precision time for events, so you will never see
  subsecond precision on events processed by this codec.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
fluent {
  }
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-codecs-fluent-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-codecs-fluent-id>> |<<string,string>>|No|
|=======================================================================


==== Details

&nbsp;

[[plugins-codecs-fluent-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-codecs-fluent-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin instance, this `ID` is used for tracking
information for a specific configuration of the plugin.

```
output {
 stdout {
   id => "ABC"
 }
}
```

If you don't explicitely set this variable Logstash will generate a unique name.


