[[plugins-codecs-msgpack]]
=== msgpack

* Version: 3.0.2
* Released on: July 14, 2016
* https://github.com/logstash-plugins/logstash-codec-msgpack/blob/master/CHANGELOG.md#302[Changelog]



==== Getting Help

For questions about the plugin, open a topic in the http://discuss.elastic.co[Discuss] forums. For bugs or feature requests, open an issue in https://github.com/elastic/logstash[Github].
For the list of Elastic supported plugins, please consult the https://www.elastic.co/support/matrix#show_logstash_plugins[Elastic Support Matrix].

==== Description



&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
msgpack {
  }
--------------------------



Available configuration options:

[cols="<,<,<",options="header",]
|=======================================================================
|Setting |Input type|Required
| <<plugins-codecs-msgpack-enable_metric>> |<<boolean,boolean>>|No
| <<plugins-codecs-msgpack-format>> |<<string,string>>|No
| <<plugins-codecs-msgpack-id>> |<<string,string>>|No
|=======================================================================


==== Details

&nbsp;

[[plugins-codecs-msgpack-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-codecs-msgpack-format]]
===== `format` 

  * Value type is <<string,string>>
  * Default value is `nil`



[[plugins-codecs-msgpack-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particulary useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------



