[[plugins-codecs-rubydebug]]
=== rubydebug

* Version: 3.0.2
* Released on: 2016-07-14
* https://github.com/logstash-plugins/logstash-codec-rubydebug/blob/master/CHANGELOG.md#302[Changelog]



The rubydebug codec will output your Logstash event data using
the Ruby Awesome Print library.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:

Required configuration options:

[source,json]
--------------------------
rubydebug {
  }
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-codecs-rubydebug-enable_metric>> |<<boolean,boolean>>|No|`true`
| <<plugins-codecs-rubydebug-id>> |<<string,string>>|No|
| <<plugins-codecs-rubydebug-metadata>> |<<boolean,boolean>>|No|`false`
|=======================================================================


==== Details

&nbsp;

[[plugins-codecs-rubydebug-enable_metric]]
===== `enable_metric` 

  * Value type is <<boolean,boolean>>
  * Default value is `true`

Disable or enable metric logging for this specific plugin instance
by default we record all the metrics we can, but you can disable metrics collection
for a specific plugin.

[[plugins-codecs-rubydebug-id]]
===== `id` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a unique `ID` to the plugin configuration. If no ID is specified, Logstash will generate one. 
It is strongly recommended to set this ID in your configuration. This is particularly useful 
when you have two or more plugins of the same type, for example, if you have 2 grok filters. 
Adding a named ID in this case will help in monitoring Logstash when using the monitoring APIs.

[source,ruby]
---------------------------------------------------------------------------------------------------
output {
 stdout {
   id => "my_plugin_id"
 }
}
---------------------------------------------------------------------------------------------------


[[plugins-codecs-rubydebug-metadata]]
===== `metadata` 

  * Value type is <<boolean,boolean>>
  * Default value is `false`

Should the event's metadata be included?


