---
name: github-commands-comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: elastic/oblt-actions/elastic/github-commands@645d97cb15a7742c25352c2bd4d1e2ea0590c746 # v1
