---
name: github-commands-comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: elastic/oblt-actions/elastic/github-commands@31fd8582a94d1829536be22c624697f851fdf60e # v1
