---
name: github-commands-comment

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: elastic/oblt-actions/elastic/github-commands@edaa58bb2b83660bbe514736dc8f073d3d74db01 # v1
