---
# This workflow converts the versioned plugin docs from asciidoc to markdown
# every time a commit is pushed to the versioned_plugin_docs branch.
name: Convert versions plugin docs to markdown

on:
  workflow_dispatch: ~
  push:
    branches:
      - versioned_plugin_docs

permissions:
  contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            ref: versioned_plugin_docs
            path: logstash-docs
            persist-credentials: false
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            repository: elastic/docs
            ref: master
            path: docs
            persist-credentials: false
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            repository: elastic/adoc-to-md
            ref: ci-adjustments
            path: adoc-to-md
            token: ${{ secrets.ADOC_TO_MD_PAT }}
            persist-credentials: false
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            repository: elastic/asciidocalypse
            ref: main-archive
            path: asciidocalypse
            token: ${{ secrets.ADOC_TO_MD_PAT }}
            persist-credentials: false

        - name: Create docker image

          run: |
            cd ./adoc-to-md/src/docker
            ./create_image.sh

        - name: Debug
          run: ls logstash-docs/docs/versioned-plugins

        - name: Migrate
          run: |
            cd ./asciidocalypse/migration-zone/logstash-versioned-plugins/scripts
            ./migrate.sh

        # - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        #   with:
        #     name: migrated-docs
        #     if-no-files-found: error
        #     retention-days: 1
        #     path: asciidocalypse/migration-zone/logstash-versioned-plugins
